### ISSUE TITLE
Some means of indicating selected camera for JSISteerableCamera

### ISSUE THREAD

**Issue by Mihara** [Mihara/RasterPropMonitor#120]
That is quite tricky actually.

**Comment by MOARdV** [comment]
One idea for implementing this (I haven't dug through all the code to see if it's actually do-able) - have an optional delegate (I think that's the C# term for function pointer) available in the background handler that returns a string.  MonitorPage will store that delegate.  RasterPropMonitorComputer will be provided a reference to that delegate (or null if it's not valid for the current page) which it can then call when the appropriate page info is requested.

**Comment by MOARdV** [comment]
Got a system that works.  It's not great, but it'll do for now.
