### ISSUE TITLE
Request from K3|Chris for a different altitude alarm.

### ISSUE THREAD

**Issue by Mihara** [Mihara/RasterPropMonitor#131]
Anyway, I got a radar alt gauge with a light using "ALTITUDEALARM" (130m radar alt, negative vertical speed) but that vertical speed could use some tweaking, it's sensitive enough to trigger going down the runway level, I haven't seen the actual code but I assume it checks for negative vspeed, not say -0.5m/s or something like that, would be a nice improvement to stop my altitude alarm going off.

**Comment by MOARdV** [comment]
K3|Chris will be able to make suitable alarms using the custom compound variables.
