### ISSUE TITLE
Docking Guidance

### ISSUE THREAD

**Issue by artwhaley** [Mihara/RasterPropMonitor#140]
Sorry for starting this conversation on the forum.  I wasn't sure if proposing a feature was an 'issue' or not.  Anyway- to repost the questions:

1. May I make a docking port alignment guide to go into the RPM project?

2. Would you like it in it's own handler that duplicates the camera code, or may I add it to the steerable camera?  ((my preference is to add it into the existing handler))

3. Should it default to on whenever it sees you using the docking port reference camera (with a config file option to disable the feature), or should it default to off and only show up if the config file turns it on?  ((my preference is for enabled by default, with an option to disable it))

4. Should the guides stay centered on the display or move and possible get clipped off the screen if the camera is panned or tilted?  ((my preference is for remaining centered regardless of camera orientation))

**Comment by MOARdV** [comment]
NavyFish is releasing a version of Docking Port Alignment Indicator with RPM support, so I think this feature will be redundant (no sense duplicating NavyFish's code if RPM support is coming with that mod).

**Comment by MOARdV** [comment]
DPAI RPM integration is available for public testing now, so I'm closing this issue.
