### ISSUE TITLE
.90 compatibility

### ISSUE THREAD

**Issue by artwhaley** [Mihara/RasterPropMonitor#141]
It appears that something in RPM doesn't play nice with .90.  With a freshly downloaded copy of RPM, I  tested both my custom props, and the MK1 with the RPM MFD's, and they're both showing a grey texture on the screen with some strange artifacting, but no RPM display.  

If I can help, let me know, but I don't know enough about the low level part of the plugin to diagnose the problem myself.

**Comment by MOARdV** [comment]
Closing, since my changes have been merged.
