### ISSUE TITLE
Fix for my last fix...

### ISSUE THREAD

**Issue by artwhaley** [Mihara/RasterPropMonitor#145]
So, I was apparently being dumb when I coded up my bits to fiddle with the target relative variables, and somehow didn't notice all the log spam until after the .90 update.  

On TGTRELX , Y and Z , 

I commented out the check to see if it was targeting a docking port and skipped straight to using  targetDockingNode .  It's an easy fix  - I just need to reenable that if, and then provide an else for what to do if it's not a docking port.  (If it even makes sense to return these values for anything other than docking ports?  Could just let it fall through to the 'return 0' targetDockingNode is null?)

But, I'm a total newb at github, and wanted to ask the easiest way to handle making the changes and being able to test them before MOARdV's .90 commit is included.  My fork is synced with the master... so I won't be able to compile and test in .90...   if I just copy MOARdV's changes into my fork...  when I commit it will try to merge those changes again...  I guess I could fork MOARdV's fork...  and then commit to there...  so my changes get added with his when his commit...  

I'm CERTAIN there's an easy way to do this that I'm just missing.  Sorry for wasting your time on a dumb question!  But I'd like to get my mistake cleaned up before you release the official .90 update!

**Comment by MOARdV** [comment]
I missed that you had created this issue.  I haven't heard anything from @Mihara , so I'll go merge my pull request into the main here some time tomorrow (giving Mihara an opportunity to veto beforehand), so you can sync and pick up its changes before you add your fix.

**Comment by MOARdV** [comment]
Okay, I've got the fix for this in my branch.  I'll be pulling it across with the other changes I've queued.
