### ISSUE TITLE
Update for the Crew tab.

### ISSUE THREAD

**Issue by enceos** [Mihara/RasterPropMonitor#146]
Its a pain in the ass today checking the Crew professions in flight. It would be SO AWESOME if the RPM "Crew" Tab displayed the real professions of Kerbals instead of fictional (commander, medic..) along with their lvl of experience.

**Comment by MOARdV** [comment]
I'm working on variables to support this.

**Comment by MOARdV** [comment]
Crew tab is updated, and the DLL supports the new variables.  I'll get a RPM 0.19 dev build up in the next day or so.
