### ISSUE TITLE
Unlimited info gauges in HUD

### ISSUE THREAD

**Issue by DracheTek** [Mihara/RasterPropMonitor#164]
Dear Mihara&MoarDv:
I am currently working on putting unlimited amount of information gauges on HUD so as to achieve some features such as NAV and ILS. It is very much easily achieved by doing some muscle works to add more vertBar and other stuffs in codes, but Now I am working on constructing VertBar, headingBar, Horizon and everything on the screen a type, and render by reading single elements or node in those items.
https://github.com/DracheTek/RPMOverhaul
that s my work so far, the reading process in start function is the most problematic. those stacked foreach's will read all GAUGE nodes and store ALL gauge nodes. The result is that even if I change active page all gauges will be posted on HUD. 
How do I arrange the reading function to make it stick to active page? Thank you very much for any response.

**Comment by MOARdV** [comment]
In the stacked foreach, look for only the prop that belongs to your module.  For an example, look at JSISwitchableVariableLabel.cs.  Also, I do not believe that your InfoGauge class needs to be an InternalModule, nor does it need to have [KSPField] for its fields.  The class should be rebuilt each time it is loaded.

**Comment by MOARdV** [comment]
Closing issue, since there's been no further comments.  Core HUD allows multiple vertical bars in v0.21.0
