### ISSUE TITLE
multiple JSIExternalCameraSelector on 1 part

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#165]
hullcams has the one booster cam that points 2 ways, hc_booster, if RPM could handle multiple JSIExternalCameraSelector modules on a part, we could correctly use it :)

**Comment by MOARdV** [comment]
Can you link to the mod, so I can make sure I'm looking at the right one?  This may be possible, but I will need to have the right part to be certain.

**Comment by anxcon** [comment]
http://forum.kerbalspaceprogram.com/threads/46365-0-90-Hullcam-VDS-0-90-update-Updated-16-Dec

**Comment by anxcon** [comment]
// It is, unfortunately, impossible to correctly set up this particular model
// to have two RPM cameras at once. It needs to actually have at least one more
// named transform for this.
@PART[hc_booster]
{
	MODULE
	{
		name = JSIExternalCameraSelector
		cameraContainer = hc_booster
		rotateCamera = -90,-90,0
		translateCamera = 0.06,0.1,0
		cameraIDPrefix = ExtCam
	}
}

is the MM script in RPMs cfg
or might this mean the model itself has to be changed?
if its the model, suggestions for someone to ask to fix?:)

**Comment by MOARdV** [comment]
Ah, I see.  The comment at the top explains the problem.  There is only one named transform in the part, so RPM can not add a second camera.  The person who created the model for Hullcam would need to update the model.  You would need to ask on the Hullcam thread about that.

**Comment by anxcon** [comment]
ah ok sorry :) thanks
