### ISSUE TITLE
Previous frames in the cameras aren't erased

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#172]
video:

https://youtu.be/5SnkpESnvYE

**Comment by MOARdV** [comment]
Wow.  That's impressive, especially since I'm pretty sure we do a clear every frame.  I'll look into this.

**Comment by MOARdV** [comment]
Nope, we don't clear screen (until now).  We must have been lucky that someone upstream of us cleared the render texture every frame.
