### ISSUE TITLE
New IVAs need RPM patches

### ISSUE THREAD

**Issue by Dinokin** [Mihara/RasterPropMonitor#174]
https://www.dropbox.com/s/5gnc3r6mbhqi5gw/Captura%20de%20tela%202015-05-01%2018.01.56.png?dl=0

:D

**Comment by MOARdV** [comment]
I've updated the name, since I think some other cockpits are going to need updates, as well.

**Comment by Dinokin** [comment]
nope, i tested all command pods.
rpm patches are only needed in mk1 inline and mk3 pods.

**Comment by MOARdV** [comment]
Enceos on the forum has made at least some updates - I'll roll those into v0.19.4.
