### ISSUE TITLE
Packadged 19.2.1 identifies itself as 19.1 to KSP Add-on Version Checker

### ISSUE THREAD

**Issue by Neouni** [Mihara/RasterPropMonitor#187]
https://github.com/Mihara/RasterPropMonitor/releases/download/v0.19.2/RasterPropMonitor.0.19.2.1.zip

RasterPropMonitor.Version:
{
  "NAME": "RasterPropMonitor",
  "URL": "https://raw.githubusercontent.com/Mihara/RasterPropMonitor/master/GameData/JSI/RasterPropMonitor/RasterPropMonitor.version",
  "DOWNLOAD": "https://github.com/Mihara/RasterPropMonitor/releases",
  "VERSION": {
    "MAJOR": 0,
    "MINOR": 19,
    "PATCH": 1
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 0
  }
}

**Comment by MOARdV** [comment]
Yeah, I missed that in the chaos of updating the mod.  You may safely edit the version file to 0.19.2

**Comment by MOARdV** [comment]
Updated the GitHub release to 0.19.2.2

**Comment by MOARdV** [comment]
Fixed on KerbalStuff as well.
