### ISSUE TITLE
Inconsistent versioning on KerbalStuff causes grief for CKAN users

### ISSUE THREAD

**Issue by Dazpoet** [Mihara/RasterPropMonitor#188]
Hi, I'm one of the people keeping an eye on CKANs metadata and I wonder if it would be possible to keep using a v< version-number > naming schema for versions added on KerbalStuff in the future?

The way CKAN indexes things uses a pattern that always assumes that `v< version-number >` is  greater than just `< version-number >` so even if there comes a much newer version our bot won't present it to users since it considers it lower if there is no leading `v`.

There have been some discussion about how we can solve this problem from our side but right now we don't have a working solution which is why we ask mod authors for help until such a time as we can work around it.

Hoping you'll take it into consideration
//Daz

**Comment by MOARdV** [comment]
I will try to maintain consistency, but since I follow a manual release process, I make no guarantee that it will always maintain the v<version> format.
