### ISSUE TITLE
request RPM compatable IVAs for SXT

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#194]
http://forum.kerbalspaceprogram.com/threads/79542-90-SXT-Lack-s-Stock-Extension-N-1-and-Aero-update-SXT-20-15FEV15-KSC-v3

SXT has a few IVAs that imo are unique, and i have no clue how to adjust / redesign to build in RPM, so if someone ever gets a desire to, or teach me how to :)

**Comment by MOARdV** [comment]
I don't see any likelihood that I'll be working on SXT IVAs anytime in the future (I don't use their pods), so any RPM updates will need to be done by someone else in the community.
