### ISSUE TITLE
New DRE incompatability

### ISSUE THREAD

**Issue by futrtrubl** [Mihara/RasterPropMonitor#198]
Looks like AlarmHEATIndicator or CUSTOM_ALCOR_PODTEMPERATUREALARM_ON or something has issues with the new DRE. There is a full log posted in the DRE thread about it.

**Comment by MOARdV** [comment]
I tracked down the log in question.  The specific error line starts [ModuleManager] - that's not an RPM bug.  Please take it up with sarbian in the Module Manager thread.
