### ISSUE TITLE
JSITransparentPod

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#201]
I’ve run into some serious issues with the “JSITransparentPod” module in the KSP 1.0.x
Looks like the scale of all the transforms in internal is now set to the “1”. That breaks almost every prop and also resets the settings of the font size in the module “JSIVariableLabel”

![fual7tp](https://cloud.githubusercontent.com/assets/6713671/7600651/0b857054-f92f-11e4-9747-5c140cdb4ae2.png)
![hmsgtfm](https://cloud.githubusercontent.com/assets/6713671/7600649/0b852be4-f92f-11e4-8d8f-99ec8bf93874.png)
![lkiqgxf](https://cloud.githubusercontent.com/assets/6713671/7600650/0b854732-f92f-11e4-930e-c15ad411ffc8.png)
![mrjmau7](https://cloud.githubusercontent.com/assets/6713671/7600653/0b87f7ac-f92f-11e4-8d18-6502cfa610ca.png)
![per274m](https://cloud.githubusercontent.com/assets/6713671/7600652/0b858238-f92f-11e4-9f38-953332a17071.png)

http://forum.kerbalspaceprogram.com/threads/94947-1-0-2-Exploration-Rover-System-by-A-S-E-T-%2809-05-15%29?p=1929010&viewfull=1#post1929010

**Comment by MOARdV** [comment]
That's pretty wild looking.  I haven't seen any problem with JSITransparentPod, but I've only looked at it with Sumghai's Fustek station parts, which don't have a lot of displays.

**Comment by MOARdV** [comment]
I'm getting errors trying to download the latest version of the ERS, so I'll have to postpone investigating this for the time being.

**Comment by Alexustas** [comment]
MediaFire link:
http://www.mediafire.com/download/942a7xa3qioeam2/ERS_v0.2.3.zip

**Comment by MOARdV** [comment]
It's my computer that's the problem - it looks like something in the latest round of Microsoft Windows patches broke downloads in IE.  Once I undid the patches, my downloads started working.

**Comment by MOARdV** [comment]
Okay, I got my computer working again, and it looks like this is a very easy fix.
