### ISSUE TITLE
JSITransparentPod (again)

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#205]
Looks like bug with the JSITransparentPod still wasn’t fixed. As I can see the size of the transforms of the prop is usually normal but JSIVariableLabel still doesn’t work fine.

I reinstalled ksp and installed only RPM 0.19.3 via CKAN, Module Manager (2.6.3), SCANSat (12.0) and my ASET folder and made this video:

https://youtu.be/Z6Q9HYEYI4w

**Comment by MOARdV** [comment]
Drat.  It looks like IVA is okay, but the exterior isn't.  I'll look at it some more.
