### ISSUE TITLE
AVC support

### ISSUE THREAD

**Issue by Blu3wolf** [Mihara/RasterPropMonitor#217]
Could Automatic Version Checker be used to identify which versions of this mod work on specific versions of KSP?

Related - is the current 0.19.3 release compatible with KSP 1.0.x?

**Comment by MOARdV** [comment]
RPM v0.19.3 is compatible with KSP 1.0.2, as it says on both the GitHub release page and KerbalStuff.  I do not test it against older versions, and I won't support bugs filed against older versions.

There is a version file already in the RPM distribution that Mihara added that may be part of AVC, and I am keeping it current as I release RPM updates.

**Comment by MOARdV** [comment]
It looks like AVC is already supported.  GameData/JSI/RasterPropMonitor/RasterPropMonitor.version

I won't be adding MiniAVC support.

**Comment by Blu3wolf** [comment]
Cheers for the responses!

The .version file is what I was looking for - I think I just need better glasses!

Muchly appreciated!
