### ISSUE TITLE
"MAPPED_ " variables problem 

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#218]
seems like we have some problem with MAPPED_ variables.
When the game starts they did not began to calculate, but instead of the value withdrawn the name of the variable on the MFD screen 
If you go back to SpaceCenter and perform "Reload Database", then everything starts to work as it should.

video:
https://youtu.be/56G9EvvQIhI

log & config
https://www.dropbox.com/s/rjod3p9i6y5aikv/log_and_cfg.zip?dl=0

RPM 0.19.3 (release)

**Comment by MOARdV** [comment]
I haven't seen a failure locally, and I didn't see anything in the log that gave me any ideas.  I made a change to how the custom and mapped variables are processed, so maybe a 0.19.5 dev build will provide a clue what's going on (or, if you can share the MFD / page configs, I can look at it here with more debugging info).

**Comment by Alexustas** [comment]
strange story. after I told about this problem, it disappeared and I wanted to say that it was a false alarm. But when I installed the latest build of the RPM (0.19.5), the problem comes back. All MAPPED_ variables displays its names. the problem disappears only after  performing  RELOAD DATABASE

ASET_PROPS
https://www.dropbox.com/s/5ghkf1i65ce8bpv/ASET_Props-dev.zip?dl=0

**Comment by MOARdV** [comment]
It worked for me this morning with the dev props.  One thing I see is that the file name has a space at the end ("CustomRemappedVariables_ALCOR_MFDs .cfg", not "CustomRemappedVariables_ALCOR_MFDs.cfg").  I don't know if that would matter.

Can you post the log (KSP.log) from a time when it doesn't load?

**Comment by MOARdV** [comment]
Never mind - it just happened to me.  I see the Config(RPM_MAPPED_VARIABLE) entries at the beginning, but the RPMC module doesn't mention seeing them, so it's like it didn't show up in KSP's database for some reason.

**Comment by MOARdV** [comment]
I have not seen this bug since I renamed the remapped variables file to eliminate the blank at the end of the file name.  I don't know if this is a coincidence, or if it's relevant.

**Comment by Alexustas** [comment]
confirmed. I've corrected the filename  and the problem disappeared. everything works as expected. Thanks!

**Comment by MOARdV** [comment]
Good news!  Odd bug, but at least it's not me. :)
