### ISSUE TITLE
Limit tourist functionality

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#219]
They can't EVA.  Maybe they shouldn't be able to control the RPM props?

**Comment by sumghai** [comment]
Agreed.

Additionally, a warning message could appear if a tourist Kerbal in IVA tries to do so:

"Tourists cannot operate instruments"

**Comment by anxcon** [comment]
might not be for this mod, but would be nice if tourists could only fit in passenger parts not command pods :)

**Comment by MOARdV** [comment]
@anxcon, that'd be a nice feature, but it's definitely outside the scope of RPM.  Mihara had plans to make it possible to move Kerbals inside the craft in IVA, but I'd prefer that being a separate plugin, so RPM doesn't collect too many features outside the scope of IVA controls and props.
