### ISSUE TITLE
FusTek JSITransparentPod-powered IVAs not appearing in VAB/SPH

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#220]
@sharpspoonful has reported that the FusTek IVAs using JSITransparentPod aren't appearing in the VAB/SPH (although they show up fine in the flight scene):

http://i.imgur.com/7RVJtu3.jpg
http://i.imgur.com/G4VrwDN.jpg
http://i.imgur.com/L6YIVqU.jpg

**Notes**
 - In KSP 0.90, IVAs did appear in the VAB/SPH and flight scene
 - @sharpspoonful and I don't believe this is related to #157 
 - FusTek modules affected:
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonyHabModule.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonyHabModuleAdapter.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonySciModule.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonySciModuleAdapter.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonyUtilModule.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KarmonyUtilModule_Adapter.cfg
    - https://github.com/sumghai/FusTek_StationParts/blob/master/GameData/FusTek/Station%20Parts/Parts/KupolaObsModule.cfg

**Comment by MOARdV** [comment]
I grabbed the snapshot of the FusTek parts to make sure mine are current.

It looks like the IVA shows up if the part is the root part, but if it's not, the IVA isn't created (as in, JSITransparentPod calls part.CreateInternalModel, and the internal model is still null).  I don't know why this would be the case, or why they're created in the VAB after going to flight.  I guess there's more digging to do.

**Comment by sumghai** [comment]
Do you think adding the RPM core PartModule would help? :
````
MODULE
     {
         name = RasterPropMonitorComputer
     }
````
The modules are going to need them anyway for the custom RPM displays.

**Comment by MOARdV** [comment]
I suspect adding it will not help this problem - the transparency code is executing, but if the part is not the root part, the IVA doesn't seem to exist (meaning - RPM tells KSP to create the IVA, and when RPM checks to see if the IVA exists afterwards, it doesn't).  However, since I don't know what's going on, I can't say for certain whether it would help.  It certainly won't hurt, since you'll need to add that module for the interior, anyway.

**Comment by sumghai** [comment]
I see.

So there's currently no way to determine why IVA spawning in the VAB only works for root parts?

**Comment by MOARdV** [comment]
Correct.  I do not have an answer (yet).  I'll try the plugin developers subforum on the KSP forum to see if someone has pointers for things to look for.

**Comment by MOARdV** [comment]
Another data point - if I re-root the model, exit the VAB, and re-enter, the newly-rooted part's IVA shows up.  It's not clear if re-rooting is sufficient, or if exiting / re-entering is the trigger.  Before I go down that rabbit hole, I've got one other thing to explore.

**Comment by MOARdV** [comment]
Oh, joy!  I can iterate over the part config nodes to find this part's node, so I can extract the INTERNAL node from it, which I can then use to spawn the IVA.  It's a bit roundabout (why are the ConfigNode fields no longer populated on non-root parts?), but it works, and it's not a detectable performance hit.

**Comment by MOARdV** [comment]
Barring contraindications, I'm closing this bug as fixed.
