### ISSUE TITLE
Distance to top of atmo

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#221]
From Alexustas:

I have one more very small request.
 got a need in variable containing the difference between the current height and the height of the top edge of the atmosphere:

 ... = ORBITBODYATMOSPHERETOP -ALTITUDE

**Comment by Alexustas** [comment]
I would really like this variable to work in both directions. At the time of the ascent (for user being able to know hour much is left until the end of the atmosphere) and at the time of the reentry to know when it will hit the atmosphere.

**Comment by MOARdV** [comment]
Okay. I won't clamp the value.  It will report a negative distance above the top of the atmosphere.  That will be in the next update.
