### ISSUE TITLE
HORZVELOCITYRIGHT and FORWARD aren't correct

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#225]
Currently, there's "RIGHT" and "FORWARD", but "FORWARD" is relative to craft forward, which is up for a vertical landing craft.  Use different names (`HORZVELOCITYX` and `HORZVELOCITYY`, where `X` is an alias for `RIGHT`, and `Y` is the vector that's a cross of local UP and RIGHT, so it's craft-orientation independent.

Per Alexustas:

> I’m working on the new version of Landing Assist MFD screen, and I wish to make a marker displaying X and Y components of horizontal speed of the vessel, like the ‘retrograde’ marker on the navball. I planned to use HORZVELOCITYRIGHT and HORZVELOCITYFORWARD variables. HORZVELOCITYRIGHT works predictably and can be used for the X of the marker, but HORZVELOCITYFORWARD doesn’t, because when descending vertically, HORZVELOCITYFORWARD is equal to VERTSPEED.[B] I really need[/B] a variable for horizontal speed in [B]Y[/B] axis.

**Comment by MOARdV** [comment]
Changing this to a bug - RIGHT and FORWARD are being computed based on the craft's frame of reference, but they should be computed based on a surface-relative frame.

**Comment by Alexustas** [comment]
I'm already using HORZVELOCITYFORWARD in my ERS rover for indicating forward-back movement and  HORZVELOCITYRIGHT for indicating sideways drift.

**Comment by MOARdV** [comment]
The fix I'm making accounts for rovers and space planes.  For space planes and rovers where the vessel "forward" vector is horizontal, FORWARD still works the same (I confirmed with a space plane).  For vessels with "forward" pointing "up" (ALCOR, for instance), the FORWARD value will report horizontal velocity component perpendicular to the RIGHT value (Y, if right is X and we're talking a 2D plane).  The current RIGHT value is not accurate, since it's based on craft roll, so it reports vertical speed if the craft is rolled onto its side.
