### ISSUE TITLE
CKAN has a bogus link for KSP 0.90 compatibe RPM Core

### ISSUE THREAD

**Issue by Shaggygoblin** [Mihara/RasterPropMonitor#228]
I am running 0.90 until a few more mods are updated to 1.0.2.
Currently, CKAN has RPM (dev) and RPM Core (stable) listed.
Both seem to fail the download, as it appears to be looking for a v0.19.1 iat the v0.19.2 link/zip.
To be able to continue using B9, I need the most recent .90 compatible build. Is that the Dev build or another? I have no issue manually installing, I just need to know which one to Git.

**Comment by MOARdV** [comment]
The dev build on GitHub ([this one](https://github.com/Mihara/RasterPropMonitor/releases/tag/v0.19)) is the only official KSP 0.90 release for RPM.

**Comment by Shaggygoblin** [comment]
OK.  Just had to ask due to CKAN choking on the download.  The one you linked is the same one I grabbed earlier and all went well with it.  Will see if I can get the link fixed by someone in the CKAN thread.  Cheers and thanks!
