### ISSUE TITLE
Is it possible script textures into a page?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#233]
When a pre-defined variable is met, is it possible to make a texture appear instead of just text?
Is it also possible to have animated gauges (like the Advanced Monitors from ALCOR) on a page?
I'm trying to make a new Plane type ADI and status page and I would really love it if I can have animated engine displays:
![ed diagram](https://cloud.githubusercontent.com/assets/12616126/7822099/3f47899c-03eb-11e5-90c3-a86ff09721f7.png)

Thanks for the amazing mod!

**Comment by MOARdV** [comment]
Not in core RPM at the present.  It would probably be better if it were implemented as a custom background handler DLL (like SCANsat and DPAI do) so it could control exactly what it wants rendered, and how it's rendered, since as a core feature, it would need to be fairly general-purpose.

**Comment by DeputyLOL** [comment]
what about something like the bar charts, but in a gauge shape?
I have very limited knowledge about modding and I am only starting to understand the basics.
I only found out about the bar chart features after I posted! (btw is it possible to change the height of the bar chart?)

**Comment by MOARdV** [comment]
The bar gauges are pretty flexible - you can control the placement and size of each, the range of values it displays, the size and color of the border, the color of the interior, and the way it fills in (in from a side, out from the middle).  A round gauge would be somewhat more complex computationally, since it's not a simple rectangle.  That's not to say it can't or won't be done - I've wanted something like that myself a few times, so I suspect it'll show up eventually.

**Comment by DeputyLOL** [comment]
Thanks, I know I can config size, placement and type but I can't find how to change the height is it in: borderWidth or borderPosition?
What about having a texture from a file appear when a variable is met? Is that possible?

Also I have an issue, this page seems to be affecting other pages. I have a page with an indicator lamp that goes red when an engine flames out. I have another page that is an aircraft ADI and whenever the indicator goes red the ADI does as well. They are on separate pages. Any idea whats causing it?
![2015-05-30_00001](https://cloud.githubusercontent.com/assets/12616126/7897764/7d6e0a32-06e0-11e5-8f02-f0848b371316.jpg)
![2015-05-30_00002](https://cloud.githubusercontent.com/assets/12616126/7897765/8250b41e-06e0-11e5-89c8-9d221162077c.jpg)

**Comment by MOARdV** [comment]
Yeah, I know what's causing it.  Thanks for finding that - I'll have it fixed for the new dev build later today.

**Comment by DeputyLOL** [comment]
Thanks : D

**Comment by DeputyLOL** [comment]
I don't know if this is RPM or not but I've been meaning to ask. I've got a bunch of alarms in my cockpit (using ALCOR model). When they go off they get quieter and quieter until they are barely audible, then they will suddenly get loud again. It will repeat the loud to quite to loud again. 
It's more obvious with looping sounds, but it affects all the alarms even those that don't loop. This has resulted in me missing alarms cause I cant hear them.

**Comment by DeputyLOL** [comment]
They are also audible from outside the cockpit

**Comment by MOARdV** [comment]
Not sure about the audio - I'll look into it.  I haven't used audio alarms much myself, although I thought that they shouldn't fire when you're not in the pod's IVA.

**Comment by DeputyLOL** [comment]
they don't start outside of the pod, they just continue playing even if the variable is no longer met, the alarm will stop playing when you go back to IVA and the alarm isn't on anymore.

**Comment by DeputyLOL** [comment]
You can probably close this now....
