### ISSUE TITLE
kerbal GPS on RPM screen

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#236]
http://forum.kerbalspaceprogram.com/threads/24646-1-0-Figaro-Global-Navigation-Satellite-System-Launch-a-Working-GPS-System

not sure if RPM can access data from this, but it would be nice (if installed) to see satellites in view, and use them to display long/lat/alt - currently all data shows on right click menu of any part that has the module KerbalGPS (the receiving module), so i would think assign it to all pods and some small bit of code to access the variable?:)

current long/lat/alt is ok when the mod isn't installed, but if it is, adds new depth? :)

**Comment by MOARdV** [comment]
I will need to look into the mod and see how readily its data can be read.

**Comment by MOARdV** [comment]
The values that Figaro exposes are all strings, not numeric, which limits their usefulness.  There's one that concatenates latitude and longitude, one for altitude, and one each for number of visible satellites and estimated error.  The latter three (alt, # sat, and error) can likely be converted back to numbers fairly easily, but having to disassemble the lat/lon string and then convert it back to a number is more effort than I want to devote.  If a future version of the mod exposes this information in a numeric format, I'd be willing to revisit the possibility.
