### ISSUE TITLE
Allow control of parachutes / RealChutes in IVA

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#239]
Fairly simple - for stock parachutes, there'll be Deploy and Cut callbacks / state methods.  For Real Chutes, there will also be an Arm/Disarm toggle function (no-op for parachutes, unless we want to artificially disallow Deploy if Arm is false, which might be a fun feature to add).

**Comment by Kerbas-ad-astra** [comment]
It might also be good to be able to modify deployment minimum pressure and altitude.  I've had a few occasions where I needed to adjust the pressure or altitude when I stage my chutes early and had to prevent them from opening during reentry.

**Comment by MOARdV** [comment]
Good idea, although it's tough to add a control like that if it requires input beyond a preset value, unless it changes the setting in steps.

**Comment by Kerbas-ad-astra** [comment]
Steps wouldn't be bad -- I can't imagine needing to be more precise than 10 feet, or even 100 feet for the deployment altitude, or 0.01 atm (or even 0.05) for the pressure.  (Multiple step sizes available would be super-nice, so I don't have to click a zillion times to get anywhere.)

**Comment by MOARdV** [comment]
For the time being, I'm going to kick the question of tuning the parachutes controls down the road.  What I've added so far covers the basics, and it doesn't require a significant effort to bring to the player.  Adding parachute tuning requires adding a menu to the MFD, or adding even more callbacks.  While both are possible, I want to get the basic feature into the wild and tested out, first.  I'll open a future issue to track enhancements to the basic feature.
