### ISSUE TITLE
Creating and toggling a custom variable from a switch?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#247]
I'm building a cockpit and I'd like to know if it is possible to control a custom variable from a button or switch. I have a lot of alarms in my cockpit and I want to have a single switch that will disable all of them. 
All I need is for a variable to be 1 when the switch is on and 0 when the switch is off, so I can then add it to all my other variable and make the alarms only come on when the switch is on. Please let me know.

**Comment by Alexustas** [comment]
RPM_CUSTOM_VARIABLE

	{
	  name = ALARM_LOWFUEL
	  operator = AND

	  SOURCE_VARIABLE
	  {
		name = SYSR_LIQUIDFUELPERCENT 
		range = 0.01, 0.1
	  }
	  SOURCE_VARIABLE
	  {
		name = SYSR_ELECTRICCHARGE
		range = 0.01, 1000000
	  }
	  SOURCE_VARIABLE
	  {
		name = PERSISTENT_<name of persisten>
		range = 0.1, 1.1
	  }
	}

**Comment by MOARdV** [comment]
Exactly as Alexustas said.  You obviously will need to tie the switch to the controlling persistent variable.

**Comment by DeputyLOL** [comment]
Thanks for the help but i'm not making progress. how do I tie the switch to the controlling persistent variable?

**Comment by DeputyLOL** [comment]
I so far have got this:

PROP
{
   name = JSIswitch_ALARMTOGGLE

   MODULE
   {
	name = JSIActionGroupSwitch
	animationName = SwitchWCoverAnim
	switchTransform = SwitchColider
	actionName = dummy
	perPodPersistenceName = ALARMTOGGLE
	switchSound = Squad/Sounds/sound_click_latch
	
   }

   MODULE
   {
      name = JSIPropTextureShift
      transformToShift = SwitchNamePlate
      layerToShift = _MainTex _Emissive
      x = 0.25
      y = 0.25
   }

}
 
}

Am I missing something?

**Comment by MOARdV** [comment]
That will set your persistent variable to ALARMTOGGLE, so in the snippet Alexustas provided, you'd change the PERSISTENT var to PERSISTENT_ALARMTOGGLE.  You also need to be using the v0.20.0 dev build I put up a couple days ago so you can use PERISTENT_

**Comment by Alexustas** [comment]
and one bracket at the end  is unnecessary )

**Comment by Alexustas** [comment]
ALARMTOGGLE switcher config:

PROP
{
name = JSIswitch_ALARMTOGGLE

MODULE
{
name = JSIActionGroupSwitch
animationName = SwitchWCoverAnim
switchTransform = SwitchColider
actionName = dummy
perPodPersistenceName = ALARMTOGGLE
switchSound = Squad/Sounds/sound_click_latch

}

MODULE
{
name = JSIPropTextureShift
transformToShift = SwitchNamePlate
layerToShift = _MainTex _Emissive
x = 0.25
y = 0.25
}
}
----------------------------------------------------------------
CUSTOM_  "Low Fuel Alarm"  variable config:

RPM_CUSTOM_VARIABLE

{
  name = DeputyLOL_ALARM_LOWFUEL
  operator = AND
  SOURCE_VARIABLE
  {
    name = SYSR_LIQUIDFUELPERCENT 
    range = 0.01, 0.1
  }
  SOURCE_VARIABLE
  {
    name = SYSR_ELECTRICCHARGE
    range = 0.01, 1000000
  }
  SOURCE_VARIABLE
  {
    name = PERSISTENT_ALARMTOGGLE
    range = 0.1, 1.1
  }
}
----------------------------------------------------------------
"Low fuel" indicator config:

PROP
{
  name = LowFuelIndicator

	MODULE 
	{
		name = JSIVariableAnimator
		animationName = TabloIndicatorAnim
		variableName = CUSTOM_DeputyLOL_ALARM_LOWFUEL
		scale = 0,1
		refreshRate = 5
		threshold = 0.1,1.1
		reverse = true
		alarmSound = ASET/ASET_Props/Sounds/apollospec
	}

	MODULE
	{
		name = JSIPropTextureShift
		transformToShift = TabloPlate
		layerToShift = _MainTex _Emissive
		x = 0.0
		y = 0.125
	}
 
}

**Comment by DeputyLOL** [comment]
I think i got all of that! I just have one more question and that is, how do i download developer build.
(this is my first time)

**Comment by MOARdV** [comment]
On DropBox:

https://www.dropbox.com/s/hqlnhlbosbnruyq/RasterPropMonitor-dev.0.20.0.zip?dl=0

(I only now started putting a link to it on the first page of the RPM forum, otherwise, you'd have to go looking for the message where I announced it)

**Comment by DeputyLOL** [comment]
thank you so much :-D

**Comment by DeputyLOL** [comment]
YES!!! It works! I love this mod! Thank you guys so much!

**Comment by MOARdV** [comment]
@DeputyLOL  - you okay if I close this out?  It looks like you got your answer.

**Comment by DeputyLOL** [comment]
Hold up. Something very bad just happened. I was adding a new variable and reloaded modual manager to see if it worked. My game crashed so I reloaded it and found something very disturbing. The switch that toggles the new variable still works but isn't animated. All the RPM scenes disappeared and it says action group error. I hadn't changed anything with that switch I had just added a new in related variable. What's more press Alt + f11 didn't open the modular manager console so I couldn't reload it. What was worse is that I can't delete the modualmanager.dll from gamedata, it says I need admin permission and I am the admin. Lastly when I tried to move it from the gamedata folder, my entire computer freaked out and just went blue. Any ideas?

**Comment by DeputyLOL** [comment]
I am restarting my computer now.

**Comment by DeputyLOL** [comment]
ok I have no idea what happened but it appears to have fixed its self and everything is working perfectly. It was probably my computer. You can close this now if you want. thanks for the help.
Btw, should I add another issue about the alarms getting quieter and being audible outside the cockpit pit?

**Comment by MOARdV** [comment]
I opened a new issue so I don't forget about it.

**Comment by DeputyLOL** [comment]
ok thanks. you close this now if you want
