### ISSUE TITLE
Audio alarm problems

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#250]
DeputyLOL in Issue #233 

>I don't know if this is RPM or not but I've been meaning to ask. I've got a bunch of alarms in my cockpit (using ALCOR model). When they go off they get quieter and quieter until they are barely audible, then they will suddenly get loud again. It will repeat the loud to quite to loud again. 
 It's more obvious with looping sounds, but it affects all the alarms even those that don't loop. This has resulted in me missing alarms cause I cant hear them.

**Comment by Alexustas** [comment]
here is a video (w/sound of course):
https://youtu.be/dV4GZ1q9o0Y

**Comment by DeputyLOL** [comment]
The problem only seems to start either:
1. When you activate 1st stage
2. When you turn engines on
3. When you start moving

I did a test and found activating an alarm before starting the first stage makes it keep its original volume.
Don't know if this helps.

**Comment by DeputyLOL** [comment]
I think I found the issue... The source of the alarms stay where the aircraft is spawned. They do this outside of IVA so I think that they might do the same inside.

I did a test, I activated an alarm, went outside IVA(alarm still playing) and then started moving down the runway. The alarm got quieter, but then when I zoomed my camera out to where I started the alarm was loud again.

**Comment by MOARdV** [comment]
@DeputyLOL - thanks for the characterization of this bug.  I really appreciate it.  I'll hopefully get some free time today to look at the bug and confirm a fix for it.

**Comment by MOARdV** [comment]
Finally looking at this - I can't reproduce it in flight (space craft in orbit) - audio goes away if I switch outside, and it returns if I go inside.  There's no fading either.  I'll rig an alarm in an aircraft cockpit and see if I can get it to trigger there.

**Comment by MOARdV** [comment]
Checked with a pod on the runway.  I triggered the alarm, and I didn't notice any fading (craft moving forward at about 20 m/s).  Audio disappears when I switch to external.

**Comment by Alexustas** [comment]
I facing this problem  permanently.  you can use ALKOR to determine the causes of this glitch. here is the link https://www.dropbox.com/s/e4nc7eebiwge5gd/ALCOR-9-3_test.zip?dl=0

**Comment by MOARdV** [comment]
I don't know why my test audio didn't do this, but I did hear it with the ALCOR alarm.  And it'll be fixed in v0.21.0.
