### ISSUE TITLE
Add FAR support

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#256]
At the very least, FAR-computed dynamic pressure and terminal velocity from FAR's FARAPI.  There are probably other values there that may be of use (AoA and sideslip).

**Comment by Alexustas** [comment]
RPMCVARIABLEHANDLER
{
    name = FARPM
    method = ProcessVariable

    variable = FARPM_DYNAMIC_PRESSURE_Q,0
    variable = FARPM_LIFT_COEFFICIENT_CL,0
    variable = FARPM_DRAG_COEFFICIENT_CD,0
    variable = FARPM_REFAREA,0
    variable = FARPM_MACHNUMBER,0
    variable = FARPM_TERMINALVELOCITY,0
    variable = FARPM_BALLISTIC_COEFFICIENT,0
    variable = FARPM_ANGLE_OF_ATTACK,0
    variable = FARPM_SIDESLIP,0
    variable = FARPM_THRUST_SPECIFIC_FUEL_CONSUMPTION,0
    variable = FARPM_STALL_FRACTION,0
}

**Comment by MOARdV** [comment]
I don't see that in FAR - did someone already make a plugin?

**Comment by Alexustas** [comment]
i've found "FARPM.cfg" in "FerramAerospaceResearch" folder

**Comment by MOARdV** [comment]
Oh, so there is.  I was looking for a DLL.  Maybe I should look at the FAR source code more closely.  Thanks for spotting that.

**Comment by MOARdV** [comment]
Okay, since FAR already has an RPM module, I'll just do something like I've done with MechJeb - if core RPM supplies a value, it'll use FAR if it's installed (which limits it, currently, to dynamic pressure and mach number, with terminal velocity once I add that, as well).

**Comment by MOARdV** [comment]
Mach Number is actually using the built-in mach number, AFAICT.  The values that look applicable are terminal velocity, and dynamic pressure, as well as angle of attack and sideslip, once I confirm that I compute them correctly in core RPM.
