### ISSUE TITLE
Vertical Bar Problems

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#262]
What is the size limit of the texture I can use for a vertical bar? I think I have set everything up alright. I made an altitude bar that went from 0 to 20000 but all that appeared is a white square with a red line.
The texture is 11517 pixels tall and 168 pixels wide.
This is what I put:
				vertBar1Texture = AdvancedCockpit/BasicMFD/HUDPFD/ADI_rightscaletest
				vertBar1UseLog10 = false
				vertBar1Variable = RADARALTOCEAN
				vertBar1Position = 480,160,64,320
				vertBar1Limit = 0,20000
				vertBar1TextureLimit = 11471,71
				vertBar1TextureSize = 640

Also is it possible to have more 2 bars?

**Comment by MOARdV** [comment]
Textures are limited by Unity and DX / OpenGL.  I think the limit for Unity in DX9 mode (the default mode) is 4096 pixels.

As for multiple bars - there can be two vertical bars at present.  When I get around to redesigning the HUD, I'll relax that limitation and allow multiple bars.

**Comment by DeputyLOL** [comment]
I got it to work at 9999 pixels.
I think its just limited to a 4 figure long value. Thanks for the reply though.

**Comment by MOARdV** [comment]
@DeputyLOL - I am currently working on supporting more than two bars in the HUD.  Is there any need you can think of for more than one horizontal bar (the compass strip)?  Or will multiple vertical bars be enough?

**Comment by DeputyLOL** [comment]
I could use another horizontal bar for a roll or yaw gauge or something.
I cant think of much for a horizontal bar, im sure others could though.

**Comment by DeputyLOL** [comment]
I don't know if it is me but the new HUD system has an issue regarding the horizon ladder, it works normally but it is a big square that rotates and appears over the vertical bars.

**Comment by MOARdV** [comment]
I changed the way the HUD is rendered, but one thing I didn't get working (yet) is a viewport window so that the ladder stays contained in its block.  So, yeah, if you've got a big ladder, it's going to spill over onto everything around it.  I plan to fix that before release.

**Comment by DeputyLOL** [comment]
ok thanks for letting me know

**Comment by MOARdV** [comment]
I think all of the issues specific to this have been solved, other than the ladder drawing out-of-bounds, which is tracked in Issue #272, so I'm closing this issue.
