### ISSUE TITLE
New request.  Prograde-retrograde markers

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#269]
I have one more request.
Is it possible to add a variable to animate Prograde-retrograde markers on MFD screen or any other prop. (and it will be wonderful if for all the other  markers appears on navboll). I'm using variables FARPM_ANGLE_OF_ATTACK and FARPM_SIDESLIP offered by FAR for this purposes,  but this creates a hard dependency on third-party mod, which is not very desirableI have one more request.

**Comment by MOARdV** [comment]
@Alexustas : Are the FAR variables what you need (AoA and sideslip)?  I can implement those in core RPM, and I can import the FAR variables when they're available (so an RPM SIDESLIP variable will use FAR if FAR is available, or else it will use RPM's sideslip if RPM is not installed).

**Comment by Alexustas** [comment]
Sounds good! 
What about the rest of the markers that appear at navboll?

**Comment by MOARdV** [comment]
I am not sure what to name them, but it should be easy to compute them.  You want the angle between the front of the craft and each of those markers, in both the vertical axis (AoA / pitch) and horizontal axis (sideslip / yaw)

**Comment by Alexustas** [comment]
Yes. this is what I need

**Comment by MOARdV** [comment]
Dev build with the many new variables is on [DropBox](https://www.dropbox.com/s/hlqkq6ybbiacfhi/RasterPropMonitor-dev.0.22.0.zip?dl=0).  I think I got the signs of the values right - I was getting cross-eyed looking at it too long.  All variables names start with either `PITCH` or `YAW`, followed by `PROGRADE`, `RETROGRADE`, `RADIALIN`, `RADIALOUT`, `NORMALPLUS`, or `NORMALMINUS` (ie, PITCHPROGRADE or YAWRADIALIN).
