### ISSUE TITLE
PODSKINTEMPERATURE variable / KSP 1.0.3

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#271]
Since Squad now distinguishes between interior temp and skin temp, might as well add the variable.  This issue will also manage KSP 1.0.3 compatibility.

**Comment by Tahvohck** [comment]
Would it be possible to add flux values for this and other temperatures that don't have it defined? I think that's only EXTERNALTEMPERATURE as of the current v0.21.0 build. I see in the code that this is probably not possible with the public API, but it'd be nice to have for consistency.

**Comment by MOARdV** [comment]
If the values are available, I could add the flux.  I haven't looked too closely at that yet.
