### ISSUE TITLE
Periodic variables (PERIOD_#Hz)

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#279]
New request. Could you please make variables that change their value from "0" to "1" some specified times in the second? 
I want to use them to make some flickering strings on the MFDs. 
The 1/2 or 1/4 interval would be perfect.

**Comment by MOARdV** [comment]
For example, PERIOD_2HZ would change 0 - 1 - 0 - 1 every second?  (2Hz cycle, so transitions low-high twice per second).

**Comment by Alexustas** [comment]
Yes!

**Comment by MOARdV** [comment]
I think it would be easy, actually (at least, until I try to make it work :) )

**Comment by MOARdV** [comment]
Okay.  Easy enough.
