### ISSUE TITLE
JSIPropTextureShift - works with DDS texture coordinate system?

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#281]
My understanding is that JSIPropTextureShift was originally conceived with PNG and TGA textures in mind.

Since 1.0.x, KSP has supported DDS textures; however, images in DDS format are typically flipped vertically compared to PNGs (Unity apparently flips them back the right way before rendering).

If JSIPropTextureShift is used to shift DDS textures, would the X and Y-shift work correctly?

**Comment by MOARdV** [comment]
Texture coordinates are in normalized device (video card) texture space, which is file format independent, so the origin of the image in the file (top left / bottom left) doesn't matter.  I'm already using JSIPropTextureShift with DDS images in my own IVA development.

**Comment by sumghai** [comment]
Ah, excellent :)
