### ISSUE TITLE
Camera post-processing effects

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#285]
Camera view effects ideas: "night vision" (convert to gray scale, adjust gamma, and display in either black/white or green).  "noise" - dirty up the image with some noise effects.  "interference" - rolling interference effects across the screen, maybe some jitter like a bad analog TV signal.  Others?

**Comment by Alexustas** [comment]
Oh, yes! myself wanted to ask you about this for a long time. Please, do it! 
And if it possible, will be very good if you can realize the effect of the "low-resolution" camera

**Comment by sumghai** [comment]
I think I'd be interested in digital noise images, too, if that hasn't been mentioned:

http://www.shutterstock.com/s/%22digital+noise%22/search.html

**Comment by MOARdV** [comment]
Digital noise should be feasible.  I guess I'd better start looking at how to write cheap post-processing shaders (and maybe see if I can slip some DX11 / OpenGL 4 shaders in for more modern hardware - I know I can generate some more efficient shaders that way).

**Comment by Tahvohck** [comment]
If it's possible to make planets show up with resource overlays in a camera view, that would be pretty amazing. I imagine that would be somewhat heavy in terms of processing though.

**Comment by MOARdV** [comment]
This depends on a resolution for Issue #477 - I don't want to add a bunch of shaders until I can get them working in the Unity 5 framework.

**Comment by MOARdV** [comment]
Okay, this is starting to look like a fun feature.  I've implemented a grayscale conversion shader, and I've worked out a way to expose shader variables in the config file, *and* I've made it so defined variables can be used for those values.  So, for instance:

```
cameraEffectShader = RPM/Grayscale
cameraEffectVariables = _Gain,MAPPED_MOARdV_GAIN_NOISE
```

selects the RPM/Grayscale shader for post-processing effects, and it defines the shader variable `_Gain` as `MAPPED_MOARdV_GAIN_NOISE`.  I then defined that variable with

```
RPM_MAPPED_VARIABLE
{
   sourceVariable = RANDOM
   sourceRange = 0,1
   mappedVariable = MOARdV_GAIN_NOISE
   mappedRange = 0.8,1.2
}
```

and now I have a B&W display that flickers in brightness continuously between 0.8x and 1.2x normal luminance.  `_Gain` could also be tied to a JSINumericInput variable to provide a manual brightness knob (and, using a MATH variable, you could add the manual brightness to the variable above to keep the continuous flicker, but still have adjustable brightness).

I'll write a "night vision" shader that does the same thing, but only writes to the green channel instead of all 3, and then I'll start researching how to do some of the other effects.

**Comment by MOARdV** [comment]
Okay, there's a grayscale, a greenscale (same a grayscale, but only green), and a 5x5 gaussian blur.  All of them have gain options.  The blur doesn't have a huge impact - typical monitor screens I've seen are configured for 512 x 512 or 640 x 640, so a 5x5 blur is a small region.  It smooths edges, but it does not look like a low-resolution image.  So, I added an option to set the JSISteerableCamera resolution independently of the monitor resolution. For example, 128 x 128 pixel camera on 512 x 512 monitor gives a blurry camera image.

**Comment by Alexustas** [comment]
> Okay, there's a grayscale, a greenscale (same a grayscale, but only green), and a 5x5 gaussian blur.

**JUST WONDERWRFUL !**

And what about the noise/grain effects?

**Comment by MOARdV** [comment]
> And what about the noise/grain effects?

Give me a little more time. :)

Most likely, noise will require a noise texture.  I will include a variable to allow shifting the noise texture vertically, and a variable to control blending between the camera image and the noise texture.  It'll be simple, but it will give us a chance to see how it looks, and if it is "good enough".  The first shader will be for color images (no grayscale conversion).

**Comment by MOARdV** [comment]
Okay.  First try at a noise shader is working for me.  Sample build is on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  I have updated the wiki with [JSISteerableCamera](https://github.com/Mihara/RasterPropMonitor/wiki/JSISteerableCamera), which explains how to use the noise effect shader (and other shaders).  Please let me know if the instructions are not good enough.

**Comment by MOARdV** [comment]
I still have to see if I can do the analog TV effects (bad V-hold, etc), and I need to figure out how to do the digital noise / decompression artifacts effect, but I think this is basically done (I won't be doing the resource overlay - that's way outside the scope of a post-processing shader).

**Comment by Alexustas** [comment]
Thank you!

https://youtu.be/ljfN0ZSPEfc

**Comment by MOARdV** [comment]
I am tweaking the behavior of gain.  Right now, gain is

```
R' = (R * _Gain);
```

I am changing it to
```
gainBoost = max(0, _Gain-1.0) * 0.15;
R' = (R * _Gain) + gainBoost;
```
This will make the black textures (like space) brighter when gain is applied.  Viewing the dimmed starfield, I like the improvement.  You may need to adjust gain values with this change.
