### ISSUE TITLE
my MFD is broken with last 0.21 dev-build

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#286]
Here is "before/after" album
http://imgur.com/a/wJxxN#0

Looks like all screens are forced to be square ((... and some sub-pixel shifting

ALCOR and Props DL:
https://www.dropbox.com/s/wfhp9vpelgndjdj/ASET-dev_02-07-2015.zip?dl=0

**Comment by MOARdV** [comment]
I am pretty sure I know what the problem with the font is.  I forgot to fix that before the commit.

I am pretty sure I know what the other problem is, too.

**Comment by MOARdV** [comment]
The screen aspect ratio was easy to fix - I forgot to do that when setting up the text camera.

The font texture problem wasn't what I thought it was - it looks like the old font renderer used point filtering, while the new renderer defaulted to bilinear filtering.  I changed it to point filtering, which fixes the problem but adds aliasing to the texts.

**Comment by MOARdV** [comment]
I believe I have fixed the problems.  Updated dev build on DropBox:

https://www.dropbox.com/s/zzjuxnnn7mwf07x/RasterPropMonitor-dev.0.21.0.zip?dl=0

**Comment by Alexustas** [comment]
Yes! FIXED! Thank You!

**Comment by MOARdV** [comment]
Happy to help.  Next time, I'll remember to check your IVAs before publishing big changes.
