### ISSUE TITLE
Improve text rendering

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#287]
The basics are there, and it works, but currently we have to use point filtering on the font texture, which leads to the difficulties reading the default HUD text.  Using bilinear filtering makes it smoother, but it causes texels from adjoining characters to bleed over.  I need to take a refresher on texture atlasing to see if I can get bilinear filtering to work, so the texts are easier to read,

**Comment by sumghai** [comment]
Alternatively, would trilinear filtering be of any help?

**Comment by MOARdV** [comment]
Since the font textures are (supposed to be) mapped 1:1 as far as texture pixels to screen pixels, a trilinear filter won't help, since the font texture doesn't have mipmaps.  The worst problem with the HUD texture is that it's a one pixel wide white strip with a one pixel wide black border.  HUD screen are about 640 pixels square, but they're usually drawn much smaller, so there's subpixel aliasing happening.

If I could generate a mipmap chain for the screen's render texture, and then use trilinear filtering on that, then, yes, trilinear filtering would help.  The last time I tried that, though, the OpenGL path showed a black screen.  It may have been that I didn't set it up right - I really should revisit that change.

**Comment by MOARdV** [comment]
It looks like the text rendering is already as good as it gets.  I've tweaked it to use bilinear filtering, but also to sample the texels correctly to prevent texture atlas bleed-through, but the HUD text (in particular) remains difficult to see.  I believe the main problem with it is that it's a 1 pixel wide color band with 1 pixel wide black borders.  Getting a new texture that's 2 pixels wide would likely be the best solution for readability (and possibly removing the black bands - I don't think they should be on a HUD font.  I'll pull the text rendering change into the v0.21.1 bugfix and punt on the texture generation, since I don't know where Mihara got the original font and I'm not going to generate one by hand.

**Comment by sumghai** [comment]
> I don't know where Mihara got the original font and I'm not going to generate one by hand

According to [this wiki page](https://github.com/Mihara/RasterPropMonitor/wiki/Making-a-prop-for-RasterPropMonitor#creating-a-bitmap-font), it seems that the default RPM font is [Fixedsys Excelsior](http://www.fixedsysexcelsior.com/).

**Comment by MOARdV** [comment]
> According to this wiki page, it seems that the default RPM font is Fixedsys Excelsior.

That's the default font, but the HUD uses a different font, and that's the problem, since it aliases badly.

**Comment by sumghai** [comment]
Ah, I see. My bad! >.<

**Comment by Mihara** [comment]
To make it worse, I can't seem to remember where I got the hud font from at all. I did make all the grids myself though, but using a web-based tool that appears to no longer exist.
