### ISSUE TITLE
Background handler improper configuration error not very helpful

### ISSUE THREAD

**Issue by Tahvohck** [Mihara/RasterPropMonitor#289]
I've only seen this on JSIPrimaryFlightDisplay so far, but I'll update this if I see it on other modules. This is basically what the issue title says, in that "INITIALIZATION ERROR, CHECK CONFIGURATION." is not very helpful on its own. Given that reloading the database is time-consuming at best (if restarting the game) and error-inducing at worst (if reloading from *in* the game), can the code be changed to say what config node key is missing/incorrectly configured/etc?

**Comment by Tahvohck** [comment]
Tracked through the code and found both why it's not helpful output (that is, that an error is being thrown and caught in JSIPrimaryFlightDisplay, then not passing the error itself), and why, I *think*, I was getting the error in the first place. I'll investigate a little bit more, but it seems that "navBallModel" is not actually optional and crashes the initialization.
Or, I'm simply changing more things at once than I think. Checking things one at a time sucks when reloading the database.

**Comment by MOARdV** [comment]
The in-game messages aren't intended to be detailed.  The intent is that you (as the IVA maker) check the output log (or, even easier, KSP.log), to see what the specifics are.  I have been improving the log messages to make them more specific to make it easier to fix.

As far as navBallModel - that *should* be optional, but I don't know if that code path has been tested any time recently.

**Comment by Tahvohck** [comment]
For the first part, fair enough. I confess to being a little frustrated. I was referring to KSP.log, however, and have ~~attached~~ [uploaded](http://pastebin.com/1vzJ5vZQ) ~~both~~ the relevant subsection ~~and the whole log~~.

And yeah, testing is showing that omitting that option borks it all to hell.

**Comment by MOARdV** [comment]
It looks like the defaults in the code were never updated when the directory structure was rearranged.  It's a trivial fix that'll be in the next release (or dev build).  Sorry it was such a headache - the error log is unhelpful in this case, too, so I'll make sure the log is improved while I'm at it.

**Comment by MOARdV** [comment]
The underlying bug is fixed (the default navball model/texture locations not being updated), and I am continuing to improve the error logging as I touch code, so I will close this issue with the release of v0.21.2 (although I may have fixed the bug in v0.21.1).
