### ISSUE TITLE
Alarms can't be shutdown

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#291]
I downloaded the latest dev build and now I cant cancel alarms. I click it and it will pause for a split second then turn on again. Any ideas?

**Comment by MOARdV** [comment]
No ideas yet.  I'll look into it.

**Comment by DeputyLOL** [comment]
I think I found a possible cause. Alarms start playing when they flash. 
So the sound will start playing again when it changes state from lit to unlit and unlit to lit. 
Something to-do with flashing delay?

**Comment by MOARdV** [comment]
They're expected to start playing if the alarm transitions from "off" to "on".  It might be that the flash delay and the alarm weren't intended to co-exist.

**Comment by MOARdV** [comment]
No, it was a bug.  It looks like I introduced a problem getting carried away handling the "silence the alarm" callback.
