### ISSUE TITLE
Chatterer integration

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#292]
As per [this](http://forum.kerbalspaceprogram.com/threads/30803-FusTek-Station-Parts-Dev-Thread-%28continuation-of-fusty-s-original-work%29?p=2044398&viewfull=1#post2044398):

> @MOARdV:
>
> You know what would be cool? If the PTT button could trigger a Chatterer "conversation". Hmmm... 

A non-critical but nice-to-have minor feature :)

**Comment by MOARdV** [comment]
I've put the feature request in on the Chatterer mod - it'll require changes there to support it here.

**Comment by sumghai** [comment]
Excellent, I'll keep an eye on things over there.

**Comment by MOARdV** [comment]
It looks like this will be available for the next RPM release, provided atlhonic accepts the pull request I will generate in a little bit.  So far, I'm adding four methods in RPM: 

* VesselXmit - returns true if the pod is "talking" or sending an SSTV transmission.
* VesselRecv - returns true if Capcom is talking to the pod.
* RadioIdle - returns true when both of the previous are false.
* InitiateChatter - the "Push to Talk" method.

**Comment by MOARdV** [comment]
The changelist was merged with Chatterer, and I've tested it locally.  The release version of Chatterer v0.9.8 should include the interface for RPM to work with it.
