### ISSUE TITLE
MechJeb RPM bugs and FAR bugs in v0.21.0

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#293]
Looks like in RPM 0.21 MECHJEBAVAILABLE variable is always equal to 1 if MechJeb Mod is just installed (even if there are no actual AR202 device installed on the craft). This messes up some of my props =(

**Comment by MOARdV** [comment]
Hmmm.  I'll have to double-check what the old MECHJEBAVAILABLE was actually doing - I thought it was only checking for the presence of the mod.

**Comment by MOARdV** [comment]
Derp.  Yeah, this was a stupid mistake.  And easy to fix (already fixed - now I need to figure out a release schedule).

**Comment by Alexustas** [comment]
Additional bug report.
If MechJeb is installed but there are no MechJeb device on the ship it spams the “[Error]: RasterPropMonitorComputer: Processing error while processing TERMINALVELOCITY: Non-static field requires a target” to the debug menu and TERMINALVELOCITY returns NAN. 
And one more thing. Maybe it’s FAR bug, but with it installed TERMINAL VELOCITY pretty much always shows “NaN m/s” at the FAR Flight data window and TERMINALVELOCITY returns “Infinity”. And there are no errors in the debug screen.

**Comment by MOARdV** [comment]
Drat.  Okay, I know what the problem with MJ is - I always use MM to install it on all pods, so I never had a craft that didn't have MJ installed, unless MJ wasn't there at all.

I didn't see the FAR bug when I tested it out - I will go back and check that again.

**Comment by MOARdV** [comment]
Oh - I see what you mean with terminal velocity in FAR.  I didn't realize it returned NaN before launch.  I'll change RPM so it returns a value consistent with FAR.

**Comment by Alexustas** [comment]
Could you please release your next dev build as soon as it will be ready so I will be able to check it?)

**Comment by MOARdV** [comment]
Dev build with these fixes here: (dropbox) https://www.dropbox.com/s/2qf38gxg70sgbor/RasterPropMonitor-dev.0.21.1.zip?dl=0

**Comment by Alexustas** [comment]
i've make quick check and it's all work great. 
Only (when FAR is installed) in debug window constantly printed "[Log]: JSIFAR: GetTerminalVelocity() = .....". I suppose it will be removed in release version.
Thank You! excellent work!
