### ISSUE TITLE
New version breaks RPM cockpit

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#294]
Im not really sure what broke but now nothing in the cockpit works at all. 
(except nav utilities HSI indicator)

All the buttons, gauges, screens and lights are all blank and broken.
I have reverted to the dev build and everything works fine. Please let me know what I need to change in order to get this to work.

**Comment by MOARdV** [comment]
There are very few changes between the last dev version and the release version.  Off the top of my head, I can't think of anything that would have broken it.  Did you try a clean install of RPM, or was it installed over an existing installation?

**Comment by MOARdV** [comment]
Can you put the KSP log somewhere? (KSP install directory)/KSP.log

**Comment by DeputyLOL** [comment]
It was a clean install, I deleted JSI folder and put the new one in.

**Comment by DeputyLOL** [comment]
and I don't see a log. The game didn't crash, the cockpit just didn't work.

**Comment by MOARdV** [comment]
The log is generated automatically by KSP - on windows, it'll be in the same location as ksp.exe.

**Comment by DeputyLOL** [comment]
hold up, Norton is deleting RPM.

**Comment by DeputyLOL** [comment]
there are loads of crash reports but I don't see a KSP.log. is it cause im using steam version?

**Comment by MOARdV** [comment]
No, I use the steam version, too.  There should be a KSP.exe in your game install directory if you look in Windows Explorer.  Right next to it, there should be a text file called KSP.log.  (It might also be called 'KSP' with an icon that looks like a sheet of paper)

**Comment by DeputyLOL** [comment]
when I searched for KSP.log it came up with a KSP.txt, is that what your looking for?

**Comment by DeputyLOL** [comment]
Yep found it

**Comment by DeputyLOL** [comment]
im going to start the game with the new version so it will record it. if it doesn't work then it should record

**Comment by DeputyLOL** [comment]
WELP! Works now! Sorry for wasting your time. You can close this now....
