### ISSUE TITLE
parachute safety indicator (pending RealChute)

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#296]
http://forum.kerbalspaceprogram.com/threads/128005-Visual-indicator-of-parachute-safety

this was on forums, so i thought i'd link the idea here
doesn't RPM have access to all of the variables to decide if its safe? speed, atmo pressure, etc?

perhaps one of the indicator lights (for SAS/RCS) for chute safety
off if in space, cuz chutes have no effect
red if unsafe and stupid to use as theyll burn off / cables cant hold
green when safe
yellow when near safe (still unsafe, but letting you know its close)
say 0% off, 0-90% red, 90-95% yellow, 95-100% green

**Comment by MOARdV** [comment]
RPM wouldn't select colors or anything like that - that'd be up to the IVA creator to decide how to display the info.  It looks like the stock ModuleParachute returns text, so I'd have to translate those to values and reconcile what happens if it's safe for one parachute, but not another (assuming that can happen - I don't use the stock parachutes, so I'll have to do some research).

**Comment by anxcon** [comment]
not wanting to add more work, but since related figure i should mention, perhaps the same for realchutes as well.....not sure if that should be tied to 1 value (applying for realchutes if installed else stock) since technically both can exist same time...but 2 dif indicators for dif mods seems weird....idk random thoughts

**Comment by MOARdV** [comment]
I haven't checked whether RealChutes has a "safe to deploy" information item yet.  Hopefully there is something similar.

**Comment by MOARdV** [comment]
Implemented for stock.  RealChute needs some additional data made accessible before I can implement it, so I'll keep this open for now pending a response from stupid_chris on whether he'll expose a method or variable.

**Comment by MOARdV** [comment]
RealChute 1.3.2.4 exposed the required values, so this is finally complete.
