### ISSUE TITLE
Allow multiple CONTEXTREDIRECT nodes in a page

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#297]
Request from Tahvohck, originally from a PM question.  Update the CONTEXTREDIRECT parser to allow multiple CONTEXTREDIRECT nodes, instead of a single one.  It's a trivial change to the implementation, and allows for some more advanced ModuleManager things to be done.

**Comment by Tahvohck** [comment]
Confirming that the dev implementation works on here as well, so you don't have to relay *all* my PMs.
