### ISSUE TITLE
Nav Utilities HSI variables.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#300]
Along the lines of my last request, is it possible to have the glide slope variables from the HSI mod to add to our PFD as a vertices bar. You could also have another use for a horizontal bar as well. If not then that is fine, I don't want to take up all your time.

**Comment by DeputyLOL** [comment]
Also is it possible to make a vertical bar appear above the ladder?

**Comment by MOARdV** [comment]
"Above" the ladder, as in superimposed over it, or "Above" as in "the top of the screen, where the heading strip is"?

In either case, yes.  As long as the vertical bar uses a transparent background, it could be placed anywhere on the screen, and it will show up on top of the ladder.  It will not be rotated with the ladder, however.

I'll look into the HSI mod to see what it does, and whether it can be included in RPM, or if I need to do a plugin similar to FAR and MechJeb.

**Comment by DeputyLOL** [comment]
Ok, I meant the first one. I ask this as the current ladder glitch makes it spill over my other vertical bars. I wanted to add a flight director (basically a fancy looking prograde marker) like the ones seen in aluxsus AHI that uses the FAR AoA and Sideslip variables.

**Comment by MOARdV** [comment]
That marker might be done as text using nudges to move it around.  I'm going to try to get the hud ladder mess sorted out in the next week or so, so hopefully that problem will go away.

**Comment by MOARdV** [comment]
It looks like the following variables are all visible in NavUtilities: selectedGlideSlope, bearing (bearing to beacon), dme (distance to beacon), elevationAngle, locDeviation (localizer deviation?), gsDeviation (glideslope deviation), runwayHeading.  I should be able to put something together fairly easily, but I'm not instrument certified in KSP, so I don't know that I can properly test them out. :)

**Comment by DeputyLOL** [comment]
ok thank you, is there a chance of having a horizontal bar for the HUD to display localiser deviation?

**Comment by DeputyLOL** [comment]
was this implemented in v0.22?

**Comment by MOARdV** [comment]
No - I moved it out of v0.22.0 because I had already piled up a lot of changes.  Depending on how things go when I start on v0.23.0, it is a good candidate for that release, provided I can get someone who can test the values and make sure they make sense.

**Comment by DeputyLOL** [comment]
I might be able to help test them.

**Comment by DeputyLOL** [comment]
I should know what the variables mean, I just need a way of actually testing them

**Comment by MOARdV** [comment]
I've done some more investigation, and I think it makes more sense for NavUtilities to expose the variables directly, since it already interfaces with RasterPropMonitor.  I've opened an issue there to see if kujuman is still developing, or if I should make changes for NU and send a pull request.  If it's the latter, I think the license on that mod would allow for me to release the updated DLL separately.

**Comment by DeputyLOL** [comment]
Cook

**Comment by DeputyLOL** [comment]
I don't think hes developing it anymore.... is this going to be taken further?

**Comment by MOARdV** [comment]
I can look into it.  It will be a few days - work is very busy at the moment, so I have less free time for developing.

**Comment by DeputyLOL** [comment]
I understand, that's ok.
There's no rush.

**Comment by DeputyLOL** [comment]
Noticed a slight problem with the NAV screens. Every since updating to 1.0.5 they are very dim. The other screens are fine.

**Comment by MOARdV** [comment]
Yeah, I don't think that's me - RPM isn't doing anything differently, or it'd affect everyone.

**Comment by DeputyLOL** [comment]
ok, sorry.

**Comment by DeputyLOL** [comment]
I know your busy so you can close this if you want. Nav doesn't seem to be updating anymore, so you don't need to bother making an outdated mod work with RPM.

**Comment by DeputyLOL** [comment]
It looks like kujuman is planning on updating Nav Utilities! Do you think we can re open this and get the variables added?

**Comment by MOARdV** [comment]
At this point, I'm going to decline.  I've got at least two mods that RPM interfaces with that I don't personally use, which means I don't know when they break until someone else tells me.  I don't have the time to keep track of those mods to test RPM each time they update.  Adding another mod to my support load will cut into my limited KSP time.

**Comment by DeputyLOL** [comment]
Ok I understand. It's a shame because kujuman was willing to support it. :(

**Comment by MOARdV** [comment]
I'm willing to help someone else with a plugin to do the interface like SCANsat and DPAI use, but someone else will have to be responsible for maintaining it.

**Comment by DeputyLOL** [comment]
Yeah I know. Thinking about it though, the mod its self already does most of the work. The only things I need from it are the variables that it uses, I can then work from them.
