### ISSUE TITLE
Multiple Vertical Bar Question

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#301]
I have a Vertical bar displays altitude and I have a system that alerts me when I have descended passed a certain altitude. Is it possible to display a marker that moves up and down with the altitude bar? 
The altitudes are 500, 1000 and 1500 or off. These might be changed.
The altimeter goes from 0 to 20100.

**Comment by MOARdV** [comment]
At present, no, there's not.  Depending on exactly how you want them to appear, you could make the marker part of the altitude bar texture, but I haven't added a way to show / move extra textures.

Although Alexustas has done some really impressive things using custom variables, a symbols font, and the page definition file, and I've done some simpler moving text effects that way, as well.

**Comment by DeputyLOL** [comment]
I was thinking of using a second vertical bar with the texture on it. Is there some way of doing equations with variables? ALTITUDE - (PERSISTENT_MINIMUMS * 500) would give the desired results. As persistent goes from 0 to 3. I've also noticed a bug regarding animations in the cockpit, when I load the cockpit, some of the don't work. When I change the display on one of the screens they all jump to life again.

**Comment by MOARdV** [comment]
No equations - that was something Mihara didn't want to do early on, and I agree with it for most situations.  I may add to the custom variable system so it can do math operations in addition to logic operations, but I haven't gone there yet, since that's a big can of worms to dig through, and I don't want to have to write a robust interpreter..

**Comment by DeputyLOL** [comment]
Fair enough

**Comment by DeputyLOL** [comment]
How about adding a feature to disable or enable a certain vertical bar when a variable is met?

**Comment by MOARdV** [comment]
> How about adding a feature to disable or enable a certain vertical bar when a variable is met?

That's something I hadn't considered - but that should be trivial to do.

>I've also noticed a bug regarding animations in the cockpit, when I load the cockpit, some of the don't work. When I change the display on one of the screens they all jump to life again.

Are you using JSI HUDs / PFDs, or custom configs?  That sounds like the refreshDataRate isn't getting set correctly somewhere.  I haven't seen that happen.

**Comment by DeputyLOL** [comment]
Not just on the screen I'm using HUD, but alarms don't work and gauges freeze. Switches still work. When I press any button in the MFD, everything snaps back to normal. It's not a very big problem but it is a bit annoying. It may or may not be my laptop playing tricks again but I'd thought I'd mention it.

**Comment by MOARdV** [comment]
alexustas also reported the bug with controls not working right on load - that is fixed in v0.21.2.  The disable / enable feature for the vertical bars will wait for v0.22.0, since I'm trying to keep v0.21.2 limited to fixes.  I'll open a new issue to track it specifically.
