### ISSUE TITLE
Request: Move storedStrings into the internal module

### ISSUE THREAD

**Issue by Tahvohck** [Mihara/RasterPropMonitor#303]
It seems to me that storedStrings should be defined on a per-prop level instead of a per-part level. That way different props can store different relevant strings, and MM patches don't have to get complex just to only alter pods that have a certain prop.

**Comment by MOARdV** [comment]
Per-prop data is very difficult with the current architecture, unfortunately.  I did a hack to get it working with the external camera info on the HUD, and it's pretty messy.  I plan to find a cleaner way to implement it at some point, at which time this will be easier to do.

**Comment by Tahvohck** [comment]
The storedStrings variable shouldn't really be changed in flight though, right? So putting it inside of the RasterPropMonitor MODULE block would both make it easily accessible and not cause any issues that I can think of. Granted, people might be doing weird things with storedStrings I wasn't aware of.
