### ISSUE TITLE
Part IDs

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#304]
A lot like the cameras have an ID, could you make so that other parts can also have an ID. E.g. Engines can have separate switches and engine gauges so that instead of having 1 switch and 1 gauge for all 4 engines you could have one each. I understand that it probably would be very difficult to do and if it it then I'll understand, but if it could be done then it would be amazing.

**Comment by MOARdV** [comment]
Sorry I never got around to answering this question.

It's possible to create a part module that has an ID number that can be changed in the VAB, but I don't know how usable per-part variables would be.  Having to keep track of part IDs and separate them also by role (RCS, fuel tank, oxidizer tank, LFE, command pod, solar panel) might get very burdensome - I'd have to track per-part values, and keep track of when parts are added or removed, and I'd have to resolve conflicts when multiple parts have the same ID.  I would need to spend a fair bit of time sorting through the issues before I'd commit to it, but the short answer is it would complicate the plugin code, possibly substantially.

**Comment by DeputyLOL** [comment]
I think the main one to work on would be the engines. Have a way to control the thrust separately and be able to turn certain ones on and off. If its too much hassle then don't sweat it.

**Comment by MOARdV** [comment]
If it's restricted to engines, it becomes much more manageable.

**Comment by DeputyLOL** [comment]
Control over individual engines would be very useful.
Other things though could be landing gears/legs.
Would this reach to modded parts though?

**Comment by MOARdV** [comment]
As long as the modded parts used the stock modules (ModuleEngines or ModuleEnginesFX for example), they would work.  I'm not sure if Firespitter propellers use that module for thrust, or if it's entirely contained in its own module, for instance.

**Comment by DeputyLOL** [comment]
ok
would they be able to be controlled separately?

**Comment by MOARdV** [comment]
I am going to punt on the general-purpose part IDs feature (engines will have individual control when I have the time for it).  The user would have to add the module to all parts of interest (using modulemanager), because adding it to every part would make an absolute mess of things in the editor.  Since it's a manual opt-in feature, it becomes an extreme corner case in the use model, which means a support effort on something few people will see.  I can't justify that time commitment.
