### ISSUE TITLE
TARGETALTITUDE reports 0 for planetary bodies

### ISSUE THREAD

**Issue by Tahvohck** [Mihara/RasterPropMonitor#305]
Not sure if this is intended, but TARGETALTITUDE doesn't report any altitude for planet and moons.

**Comment by MOARdV** [comment]
TARGETALTITUDE doesn't really make sense for planets and moons - they aren't at a particular altitude (over themselves).  They should return -1.

**Comment by Tahvohck** [comment]
They all have altitudes relative to the body they're orbiting though, with the exception of Kerbol. While it's unlikely to ever be helpful, displaying that altitude would at least make interfaces/interface definition files cleaner, since you wouldn't need to "special case" any lines that report it away.

**Comment by MOARdV** [comment]
After thinking about this some more, I think TARGETALTITUDE reporting altitude (relative to the parent body) makes sense, provided one is orbiting the targeted body's parent (in other words, the targeted celestial and the vessel are in the same SoI).  At the very least, as long as the targeted body isn't what the vessel is orbiting (which I don't think is possible, anyway).
