### ISSUE TITLE
null exemptions right after docking

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#307]
User sp1989 tests my last update and that's what he wrote:
"I did however find a bug docking in space. I got a few null exemptions right after docking. As soon as the docking ports meet the the "JSI Configurator" exemption. So I enclosed my log. and some pictures. Other then that everything was really smooth for me.". 
Here's his log:
https://www.dropbox.com/s/j9pm1i59c04ycoi/Player.log?dl=0
screenshots

![jlefkao](https://cloud.githubusercontent.com/assets/6713671/8754855/30c06580-2ce8-11e5-964c-8618e18aa85c.png)
![pssyphq](https://cloud.githubusercontent.com/assets/6713671/8754858/34442e94-2ce8-11e5-9899-c7a078bee767.png)

Here's the update that he tested.
https://www.dropbox.com/s/fusnfaez46ljo5w/ASET_dev-13-07-2015.zip?dl=0

**Comment by MOARdV** [comment]
That's really annoying ... but also, it looks easy to fix.
