### ISSUE TITLE
JSIVariableAnimator module sometimes doesn’t start at the start of the mission

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#308]
I noticed this bug by myself and one of my testers also confirmed the same problem. It seems like at the start of the mission props animation sometimes doesn’t work (and sometimes it does, don’t know why). Looks like the JSIVariableAnimator module doesn’t start at all.
Everything comes alive only after you choose any page on MFD.

**Comment by MOARdV** [comment]
I have my suspicions on this, actually.  I will release a dev build for v0.21.2 with fixes to make sure.

**Comment by MOARdV** [comment]
Dev build with fixes is available on [DropBox](https://www.dropbox.com/s/27sywu3nzw1tjbk/RasterPropMonitor-dev.0.21.2.zip?dl=0).

**Comment by Alexustas** [comment]
Fixed! Thank you very much!
