### ISSUE TITLE
Support of BDArmory

### ISSUE THREAD

**Issue by DracheTek** [Mihara/RasterPropMonitor#314]
Back to 0.17 I think I have created a parameter list to count weapon load of the famous BDArmory, and track current weapon from weapon manager. Would you think it interested?

**Comment by MOARdV** [comment]
I'm not going to incorporate BDArmory support in RPM.  If you've got an add-on that provides information from BDArmory in RasterPropMonitor, you are welcome to release it as an add-on for the two mods.
