### ISSUE TITLE
Changing text on screen.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#315]
Would it be possible to have text track a certain variable but also be controlled by another. (Basically like the vertical bars being enabled and disabled).

I plan to make a vertical bar change from an altitude to radar altitude when the craft drops below 2500 meters (and a certain switch is on). The numbers that display what the vertical bar is showing would also need to change from altitude to radar altitude.
Is there anyway to make the text switch between different variables when a certain different variable is met?

**Comment by MOARdV** [comment]
What you want is a way to display one of two variables, depending on whether a third variable meets certain conditions?  Such as "Show RADARALTOCEAN if ENABLERADARALTIMETER is true, otherwise show ALTITUDE"?  It doesn't exist right now, but I can probably figure out how to make it work, particularly if the switched variables are required to be the same type (a number or a text string).

**Comment by Alexustas** [comment]
First, you need to create a CUSTOM-varible like this:

RPM_CUSTOM_VARIABLE
	{
	  name =DEPUTY_SWITCHTORADARALTIMTER
	  operator = OR
	  
	  SOURCE_VARIABLE
	  {
		name = RADARALT
		range = 0, 2500
	  }
	  SOURCE_VARIABLE
	  {
		name = PERSITENT_<name of your altitude mode switcher perPodPersistent>
		range = 0.1, 1.1
	  }
}

Then in MFD config:

[#{2:"FFFFFFFF";"00000000";"00000000"}]{0:SIP4}[@x-64][#{2:"00000000";"00000000";"FFFFFFFF"}]{1:SIP4} $&$  RADARALT ALTITUDE CUSTOM_DEPUTY_SWITCHTORADARALTIMTER

**Comment by MOARdV** [comment]
I'm going to add (another) custom variable feature that works similarly to the updated variable-controlled monitor page switcher, where you can define a variable selector that will return a variable depending on one or more conditions.  The example above would simplify to a single SELECT_ALTIMETER variable, with the SELECT defined to return ALTITUDE by default, or RADARALTOCEAN if the switch variable is in range.  I think doing so may simplify MFD page design (and, correspondingly, make them less costly to process).

**Comment by DeputyLOL** [comment]
that sounds cool. Sorry, I forgot to thank alexustas for his solution, so... THANK YOU, IT WORKED!
I think this feature would be useful but I changed my design so that a small radar altimeter appears in the bottom of the screen when below 2500ft. Instead of replacing the altitude bar.
