### ISSUE TITLE
How to generate PDF documentation from the wiki?

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#317]
@Mihara - what method did you use to generate the PDF documentation for RPM?  I'd like to start releasing the documentation again, but I don't know how.

**Comment by Mihara** [comment]
I used this horrifying kludge: https://gist.github.com/Mihara/31fae4ab8e4296fa1df6

If it's a problem to replicate this setup, I could just make the doc file for you, it's essentially automatic.
