### ISSUE TITLE
monitors lose bright when usen -force-opengl

### ISSUE THREAD

**Issue by Dinokin** [Mihara/RasterPropMonitor#318]
![2015-07-25_00001](https://cloud.githubusercontent.com/assets/7002693/8888109/796e5cc2-3276-11e5-9940-7e492cc5fd29.jpg)

**Comment by MOARdV** [comment]
This might be an issue with OpenGL in Unity's Windows implementation - both the default DX and OpenGL use the same shader.  The Linux people who've used it haven't reported a problem.  I'll look into it.

**Comment by MOARdV** [comment]
This looks like it's differences between the DX and OpenGL code paths below my level of control.
