### ISSUE TITLE
Stop text from shifting when text to the left of it appears.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#319]
I've looked through the wiki for this but couldn't find anything, is there a way to 'anchor' text?
I have text that appears on screen but when it does appear it shifts everything to the right of it to the right.
My work around solution is to either place them to the right of something that stays on (like airspeed indicator) and nudge it to the left. Or to place it on a different line and nudge it up or down. This is starting to get messy and confusing. 
If there is someway for the text to keep its spot while inactive then that could be a big help.

**Comment by MOARdV** [comment]
The current method for doing that is using string formatting.  ie

    {0:"GEAR";"    ";"    "} $&$ GEAR

(where the spaces in the negative and zero fields are the same length as the text).  If you've got variable length text, you can set aside space thus:

    {0,4:"GEAR";"";""} $&$ GEAR

(where the second number indicates the number of spaces the text occupies; a negative values changes it to right-justified).

**Comment by DeputyLOL** [comment]
Lovely thanks alot!
