### ISSUE TITLE
Using variables to toggle/change systems (E.g. SAS, brakes...)

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#321]
Is it possible to trigger systems using variables?
I mean when certain variables are met, something like the SAS is automagically turned on or off, without the need of a switch.

One of the systems I am trying to create is something called 'autobrakes' used on real life planes.
Autobrakes basically automatically applies the brakes when landing, you have a switch to enable and disable it, but this is usually left on. The brakes would enable when:
1. The aircraft is on the ground
2. The throttle is set to idle

I have ideas for other systems but for now I just want to know if they are possible.

**Comment by MOARdV** [comment]
Sure, they're possible.  I've thought of something like that before, but I had so many other things going on at the time, I forgot to write it down.  Now it's in the issue tracker, so it's less likely I'll forget it. :)

**Comment by DeputyLOL** [comment]
Yay! everyone happy!

**Comment by MOARdV** [comment]
The initial implementation will be out available in a dev build soon.
