### ISSUE TITLE
Controlling the order of vertical bars and ladder.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#328]
Is there a way of controlling where a ladder would be placed, in terms of in front of or behind other items?
I ask this as (hopefully) toggling certain vertical bars will be a feature and I need to be able to control which bars appear in front and which are behind.

I think it would also be more helpful for vertical bars to appear in front of the horizon ladder.

**Comment by MOARdV** [comment]
Right now, it looks like they're all placed at the same depth: just about everything (the ladder, the horizontal bar, and the vertical bars) are at a distance of 1.4.  For reference, the static overlay (if present) is at a depth of 1.0.  Prograde icons are at 1.35.  Statically changing the depth is feasible (setting it in the config file, and never changing it); dynamically changing it is probably not possible with the current implementation.

**Comment by DeputyLOL** [comment]
I just mean being able to set what appears above what. 
E.g. An altimeter might have a marker that moves up and down with it. The marker would basically be an altimeter but with a transparent background and small shape. The normal altimeter would have a solid background. I'm just asking if there is a reliable way to make sure the marker would appear in front of the altimeter because sometimes the opposite happens and results in me not seeing the marker.

I don't mean changing the order of bars using variables.
