### ISSUE TITLE
Add configurable horizontal bars to JSIHUD

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#329]
There's already configurable vertical bars, so it was only a matter of time. :)

Should be easy, mostly.

**Comment by DeputyLOL** [comment]
doesn't seem to work. It sort of worked once, but it went up and down. So it is still a vertbar for some reason.

**Comment by DeputyLOL** [comment]
still not working for me for some reason.

**Comment by DeputyLOL** [comment]
I got something. but it doesn't look pretty. I am assuming that the texture for the horizontal bar should also be horizontal. Either way, this is my config:
JSIHUD_HORIZONTAL_BAR
{
	name = LocMarker
	texture = AdvancedCockpit/MFD/BasicMFD/HUDPFD/ADI_LOC
	useLog10 = false
	variableName = ROLL
	position = 227,490,187,17
	scale = -10,10
	textureLimit = 0,187
	textureSize = 187
}

And texture:

![adi_loc](https://cloud.githubusercontent.com/assets/12616126/11556882/66112690-99a1-11e5-8c5f-7c3bcf76558b.png)

**Comment by DeputyLOL** [comment]
And video: https://youtu.be/NNzYw6Ie-xU
You can briefly see the marker when banking through 5*

**Comment by DeputyLOL** [comment]
Found the issue. Its still a vertical bar.
https://youtu.be/bunG42a_OQ0

**Comment by MOARdV** [comment]
> Found the issue. Its still a vertical bar.

That's what I get for a rushed copy/paste.  I'll pay more attention to it, today hopefully, and update it.

**Comment by DeputyLOL** [comment]
Tell me when, I'll continue testing

**Comment by MOARdV** [comment]
I had some time to look at the code - I think [this, on DropBox](https://www.dropbox.com/s/47ezo8iq219jz3s/RasterPropMonitor-dev.0.24.2.zip?dl=0) fixes it (I haven't had time to test).

**Comment by DeputyLOL** [comment]
ill test it for you now

**Comment by DeputyLOL** [comment]
from first looks, its seems to work!

**Comment by DeputyLOL** [comment]
yes, works completely!
