### ISSUE TITLE
Rotating scansat terrain map.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#334]
Not sure to put this here, but I wanted to ask. I kind of need a 'look ahead' terrain display. 
I know that ScanSat has maps that can do that. Is it possible to have a map like this (ignore dotted lines and arrows):
![terrain radar](https://cloud.githubusercontent.com/assets/12616126/9293050/c5165d0c-4412-11e5-83c6-199e3054ddfa.jpg)
The plane stays still at the bottom and the map displaying terrain data rotates around. The radar 'sweeps' from left to right redrawing the map as you go. 
Real aircraft use these and can switch between terrain and weather, but as there is no weather in KSP I can miss that one.
If this is the wrong place then I'm sorry and I'll put it somewhere else.

**Comment by MOARdV** [comment]
The SCANsat mod maintains the RPM plugin now, so they're probably your best bet.  That, or someone would need to make a standalone plugin that works with both.

**Comment by DeputyLOL** [comment]
ok thanks, ill ask scantsat
