### ISSUE TITLE
Cockpit broken on update v0.22.2

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#352]
Nuf said. No animations, no buttons, no screens, nothing. Only things that work are the vanilla gauges and throttle and the Nav Utilities Analogue HSI. I know that this on its own is not helpful so I put the log underneath. Hopefully you can understand what is wrong. I am probably gonna revert back to v0.21.0 as that is the last one that worked.

[LOG 21:05:44.776] ------------------- initializing flight mode... ------------------
[LOG 21:05:45.109] Target vessel index: 10  vessel count: 11
[LOG 21:05:45.115] [FLIGHT GLOBALS]: Switching To Vessel Ferry Mk2 FAR ---------------------- 
[LOG 21:05:45.121] setting new dominant body: Kerbin
FlightGlobals.mainBody: Kerbin
[LOG 21:05:45.128] Reference Frame: Rotating
[WRN 21:05:45.192] HighlightingSystem : Multiple Highlighter components on a single GameObject is not allowed! Highlighter has been disabled on a GameObject with name 'model'.
[WRN 21:05:45.236] [Part]: PartModule indexing mismatch at SXTmk3Cockpit52, index 5.
Node 'RasterPropMonitorComputer' found in loaded data, but 'GeometryPartModule' is defined in prefab.
Looking for RasterPropMonitorComputer in other indices...
[ERR 21:05:45.242] ...no RasterPropMonitorComputer module found on part definition. Skipping...

[WRN 21:05:45.245] PartModule is null.
[WRN 21:05:45.250] [Part]: PartModule indexing mismatch at SXTmk3Cockpit52, index 8.
Node 'JSINonTransparentPod' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for JSINonTransparentPod in other indices...
[ERR 21:05:45.255] ...no JSINonTransparentPod module found on part definition. Skipping...

[WRN 21:05:45.258] PartModule is null.
[ERR 21:05:45.311] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[ERR 21:05:45.314] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[WRN 21:05:45.428] [Part]: PartModule indexing mismatch at JSIPrimitiveExternalCamera, index 0.
Node 'JSIExternalCameraSelector' found in loaded data, but 'GeometryPartModule' is defined in prefab.
Looking for JSIExternalCameraSelector in other indices...
[ERR 21:05:45.434] ...no JSIExternalCameraSelector module found on part definition. Skipping...

[WRN 21:05:45.437] PartModule is null.
[WRN 21:05:45.478] [Part]: PartModule indexing mismatch at mk3CrewCabin, index 6.
Node 'JSINonTransparentPod' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for JSINonTransparentPod in other indices...
[ERR 21:05:45.483] ...no JSINonTransparentPod module found on part definition. Skipping...

[WRN 21:05:45.486] PartModule is null.
[WRN 21:05:45.529] [Part]: PartModule indexing mismatch at mk3CrewCabin, index 6.
Node 'JSINonTransparentPod' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for JSINonTransparentPod in other indices...
[ERR 21:05:45.534] ...no JSINonTransparentPod module found on part definition. Skipping...

[WRN 21:05:45.537] PartModule is null.
[ERR 21:05:45.683] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[ERR 21:05:45.687] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[ERR 21:05:46.571] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[ERR 21:05:46.574] Cannot parse Enum value: enumType is not an Enum type.
Parameter name: enumType

[WRN 21:05:47.301] [Part]: PartModule indexing mismatch at mk3CrewCabin, index 6.
Node 'JSINonTransparentPod' found in loaded data, but 'ModuleTripLogger' is defined in prefab.
Looking for JSINonTransparentPod in other indices...
[ERR 21:05:47.306] ...no JSINonTransparentPod module found on part definition. Skipping...

[WRN 21:05:47.309] PartModule is null.
[LOG 21:05:47.617] [Ferry Mk2 FAR]: landed - waiting for ground contact to resume physics...
[LOG 21:05:47.635] Camera Mode: AUTO
[LOG 21:05:47.770] InternalSeat: Cannot find portraitCamera of name 'Camera_Left003'
[LOG 21:05:47.775] InternalSeat: Cannot find portraitCamera of name 'Camera_Left003'
[LOG 21:05:47.781] InternalSeat: Cannot find portraitCamera of name 'Camera_Left003'
[LOG 21:05:47.788] stage manager resuming...
[LOG 21:05:48.952] all systems started
[LOG 21:05:49.052] MFIManager Start Post RemoveModuleOfType. Current modules coVesselModule : 
  ModularFI.ModularFlightIntegrator active=True order=0
  FerramAerospaceResearch.FARAeroComponents.FARVesselAero active=True order=0
  FerramAerospaceResearch.FARGUI.FARFlightGUI.FlightGUI active=True order=0

[LOG 21:05:49.108] Parsing double
[LOG 21:05:49.110] Parsing rect
[LOG 21:05:49.112] Parsing bool
[LOG 21:05:49.114] Parsing bool
[LOG 21:05:49.116] Parsing bool
[LOG 21:05:49.117] Parsing bool
[LOG 21:05:49.130] ScienceAlert, Waiting on R&D...
[EXC 21:05:49.137] TypeLoadException: Could not load type 'VesselView.VesselViewPlugin' from assembly 'VesselViewPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

[LOG 21:05:49.175] Parsing rect
[LOG 21:05:49.177] Parsing rect
[LOG 21:05:49.180] Parsing rect
[LOG 21:05:49.182] Parsing string
[LOG 21:05:49.184] Parsing string
[LOG 21:05:49.186] Parsing string
[ERR 21:05:49.278] WheelCollider requires an attached Rigidbody to function.

[LOG 21:05:49.280] FSwheel: reversemotorset: True
[LOG 21:05:49.324] FAR Raycast mask: 557059 557063
[LOG 21:05:49.353] FSwheel: missing suspensionParent wheelFix2
[ERR 21:05:49.355] WheelCollider requires an attached Rigidbody to function.

[ERR 21:05:49.356] WheelCollider requires an attached Rigidbody to function.

[LOG 21:05:49.358] FSwheel: reversemotorset: True
[LOG 21:05:49.447] FSwheel: missing suspensionParent wheelFix2
[ERR 21:05:49.449] WheelCollider requires an attached Rigidbody to function.

[ERR 21:05:49.450] WheelCollider requires an attached Rigidbody to function.

[LOG 21:05:49.452] FSwheel: reversemotorset: True
[ERR 21:05:49.819] MechJeb module MechJebModuleFlightRecorder threw an exception in OnFixedUpdate: System.IndexOutOfRangeException: Array index is out of range.
  at MuMech.MechJebModuleFlightRecorder.OnFixedUpdate () [0x00000] in <filename unknown>:0 
  at MuMech.MechJebCore.FixedUpdate () [0x00000] in <filename unknown>:0 

[LOG 21:05:49.829] [ModularFlightIntegrator] MFI Start
[LOG 21:05:49.835] [ModularFlightIntegrator] Start. Current modules coVesselModule : 
  ModularFI.ModularFlightIntegrator active=True order=0
  FerramAerospaceResearch.FARAeroComponents.FARVesselAero active=True order=0
  FerramAerospaceResearch.FARGUI.FARFlightGUI.FlightGUI active=True order=0

[LOG 21:05:50.049] DPAI: Reference Part Changed - tick 1
[ERR 21:05:50.453] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.455] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.457] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.459] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.461] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.463] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.465] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.466] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.468] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.470] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.472] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.474] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.476] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.478] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.480] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.482] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.484] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.486] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.488] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.490] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.492] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.494] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.496] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.498] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.500] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.502] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.503] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.505] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.507] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.509] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.511] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.513] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.515] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.517] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.519] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.521] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.523] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.525] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.527] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.529] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.531] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.533] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.535] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.537] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.539] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.541] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.543] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.545] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.547] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.548] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.551] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.553] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.554] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.556] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.558] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.560] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.562] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.564] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.566] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.568] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.570] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.572] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.575] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.577] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.579] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.581] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.583] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.585] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.587] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.589] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.591] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.593] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.595] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.597] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.599] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.601] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.603] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.605] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.607] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.610] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.612] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.614] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.616] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.618] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.620] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.622] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.624] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.626] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.629] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.631] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.632] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.634] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.636] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.639] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.641] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.643] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.644] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.646] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.648] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.650] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.652] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.654] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.656] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.658] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.660] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.662] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[ERR 21:05:50.664] Ignore collision failed. Both colliders need to be activated when calling this IgnoreCollision

[LOG 21:05:51.403] [ScenarioDestructibles]: Loading... 0 objects registered
[ERR 21:05:51.410] Cannot find a Module of typename 'SCANcontroller'

[ERR 21:05:51.412] ScenarioModule is null.

[ERR 21:05:51.414] Cannot find a Module of typename 'StnSciScenario'

[ERR 21:05:51.417] ScenarioModule is null.

[ERR 21:05:51.419] Cannot find a Module of typename 'KethaneData'

[ERR 21:05:51.422] ScenarioModule is null.

[LOG 21:05:51.426] Loading Depletion Nodes
[LOG 21:05:51.428] DepNodeCount:  0
[LOG 21:05:51.431] Loading Biome Nodes
[LOG 21:05:51.433] BiomeNodeCount:  1
[LOG 21:05:51.435] Loading Planet Nodes
[LOG 21:05:51.437] PlanetNodeCount:  0
[LOG 21:05:51.441] Loading FAR Data
[LOG 21:05:51.448] Parsing rect
[LOG 21:05:51.450] Parsing rect
[LOG 21:05:51.452] Parsing rect
[LOG 21:05:51.454] Parsing string
[LOG 21:05:51.456] Parsing string
[LOG 21:05:51.458] Parsing string
[LOG 21:05:51.460] FAR: loaded AG actionGroupSpoiler as Brakes
[LOG 21:05:51.463] FAR: loaded AG actionGroupIncreaseFlapDeflection as None
[LOG 21:05:51.465] FAR: loaded AG actionGroupDecreaseFlapDeflection as None
[LOG 21:05:51.479] FAR Vehicle Voxel Setup started
[LOG 21:05:51.481] FAR Vehicle Voxel Setup complete
[LOG 21:05:52.302] [PlanetariumCamera]: Focus: Ferry Mk2 FAR
[WRN 21:05:52.465] [CurrencyWidgetsApp]: No live widgets to Despawn!
[LOG 21:05:52.538] Updating vessel voxel for Ferry Mk2 FAR
[LOG 21:05:52.895] 2.53170336392094
1.07416391813861
0.318495059344451
0.641535829575634
0.693553509673092
0.242140246861675
-0.140558886198985
-0.390135194234047
-0.693379622163893
-1.03196180793652
-1.22794241565443
-1.17494149904257
-0.949825991826806
-0.694429289141134
-0.472021746531898
-0.29261506982815
-0.201469232955111
-0.24633487587102
-0.382075433126121
-0.485361023954487
-0.468956157044542
-0.342656751602629
-0.161100563069998
0.0609500883781168
0.367996471388325
0.790393142643605
1.24028455173511
1.49988795108342
1.36847632576628
0.859361432827441
0.243429154165332
-0.132900869348669
-0.10835957008084
0.191111486362916
0.511670180265041
0.698409026357867
0.699962288663439
0.412067478568785
-0.31397160292607
-1.48328487090223
-2.8753657794821
-4.1125621639754
-4.72248921105614
-4.28019234405344
-2.76463855236109
-0.797363568903842
0.71706514061386
1.32209186797975
1.29046358854718
1.16491498200751
1.19421840566466
1.28312431121473
1.29399697824915
1.21103673444169
1.06882148310491
0.864147751093023
0.556558582566802
0.112278628410749
-0.440386884705487
-0.97580654195827
-1.31007517965992
-1.30525025056964
-0.960058974682348
-0.422041004744668
0.0919960868026794
0.421781360743303
0.543134571988311
0.532756028230962
0.451870346802751
0.27335297013915
-0.0652202207741187
-0.561977034988794
-1.12740928438386
-1.59994947423593
-1.72782276235444
-1.24438824832351
-0.132723912908498
1.19458927587847
2.07024361089918
2.04245076624289
1.41259883009219
0.997133465864246
0.970435363211039

[LOG 21:05:53.633] Flight State Captured
[LOG 21:05:53.636] Saving Achievements Tree...
[LOG 21:05:53.638] Saving Achievements Tree...
[LOG 21:05:53.641] saved
[LOG 21:05:53.650] Saving FAR Data
[LOG 21:05:53.657] FAR: save AG actionGroupSpoiler as Brakes
[LOG 21:05:53.660] FAR: save AG actionGroupIncreaseFlapDeflection as None
[LOG 21:05:53.662] FAR: save AG actionGroupDecreaseFlapDeflection as None
[LOG 21:05:53.905] Game State Saved as persistent
[LOG 21:05:54.775] BDAdjustableLandingGear : Rebuilding mesh data.
[LOG 21:05:54.780] BDAdjustableLandingGear : Rebuilding mesh data.
[LOG 21:05:54.785] BDAdjustableLandingGear : Rebuilding mesh data.
[LOG 21:05:54.836] Updating vessel voxel for Ferry Mk2 FAR
[LOG 21:05:55.158] 2.53170336392094
1.07416391813861
0.318495059344451
0.641535829575634
0.693553509673092
0.242140246861675
-0.140558886198985
-0.390135194234047
-0.693379622163893
-1.03196180793652
-1.22794241565443
-1.17494149904257
-0.949825991826806
-0.694429289141134
-0.472021746531898
-0.29261506982815
-0.201469232955111
-0.24633487587102
-0.382075433126121
-0.485361023954487
-0.468956157044542
-0.342656751602629
-0.161100563069998
0.0609500883781168
0.367996471388325
0.790393142643605
1.24028455173511
1.49988795108342
1.36847632576628
0.859361432827441
0.243429154165332
-0.132900869348669
-0.10835957008084
0.191111486362916
0.511670180265041
0.698409026357867
0.699962288663439
0.412067478568785
-0.31397663056988
-1.48336204754855
-2.87593780749501
-4.11521159494469
-4.73085298473072
-4.2985934318492
-2.79181325253896
-0.819241953237613
0.722816043698397
1.36509794772486
1.35119284139643
1.20792106175264
1.19996930874921
1.26124592688096
1.26682227807128
1.19263564664594
1.06045770943034
0.861498320123741
0.555986554553886
0.112201451764421
-0.440391912349296
-0.97580654195827
-1.31007517965992
-1.30525025056964
-0.960058974682348
-0.422041004744668
0.0919960868026794
0.421781360743303
0.543134571988311
0.532756028230962
0.451870346802751
0.27335297013915
-0.0652202207741187
-0.561977034988794
-1.12740928438386
-1.59994947423593
-1.72782276235444
-1.24438824832351
-0.132723912908498
1.19458927587847
2.07024361089918
2.04245076624289
1.41259883009219
0.997133465864246
0.970435363211039

[LOG 21:05:56.429] [Ferry Mk2 FAR]: ground contact! - error: -0.006m

**Comment by MOARdV** [comment]
Based on the snippet you've provided, it looks like RPM isn't installed.  Can you put the full log somewhere (dropbox or onedrive or whatever)?

**Comment by DeputyLOL** [comment]
I can assure you that rpm is installed.
This occurred after I moved the old JSI folder out of game data and place the new one in.
If I put the old one back then it works perfectly.
I would put the log up, but I have no idea how..... :(

**Comment by MOARdV** [comment]
You should have (in that log, near the top) something that looks like this:

> [LOG 17:46:48.514] Load(Assembly): JSI/RasterPropMonitor/Plugins/RasterPropMonitor
> [LOG 17:46:48.515] AssemblyLoader: Loading assembly at D:\Games\Steam\steamapps\common\Kerbal Space Program\GameData\JSI\RasterPropMonitor\Plugins\RasterPropMonitor.dll
> [LOG 17:46:48.527] AssemblyLoader: KSPAssembly 'RasterPropMonitor' V0.17

Make sure that's there.  If it's not, or it says something else, let me know.

And I assume you've already verified that JSI/RasterPropMonitor/Plugins/RasterPropMonitor.dll exists in the new one?

**Comment by DeputyLOL** [comment]
ill have a look

**Comment by DeputyLOL** [comment]
Wait, I figured it out... Norton didn't like it so it deleted it automatically. Then didn't tell me. I think I may have got this sorted now. ITS ALWAYS NORTON!!!!

**Comment by MOARdV** [comment]
The joy of quiet anti-virus...  Glad it was something "simple". :)
