### ISSUE TITLE
Change Unit of some variables

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#353]
Is it possible to have some variable In a different unit?
Like having the air speed in knots. I think FAR already has this data.
And having the altitude and radar altitude in feet.

Just a little thing I wanted to get off my mind as real life airliners use feet and knots instead of meters and m/s

**Comment by MOARdV** [comment]
That should be easy to add.

**Comment by DeputyLOL** [comment]
cool, thanks

**Comment by MOARdV** [comment]
Okay.  I didn't exactly add the conversions, because they'd entail *lots* of new variables.  What I did instead is add a "MATH_" custom variable type, similar to the "MAPPED_" or "CUSTOM_" variables, and I added constants for converting meters to feet and m/s to knots.  I'll put the details on the Custom Variables page of the wiki, and I'll get a dev build released "soon".

**Comment by DeputyLOL** [comment]
Thanks, any news on the Nav Utilities variables. I can test them out and tell you what they mean if you want.

**Comment by MOARdV** [comment]
I haven't gotten to Nav Utilities yet.  They're on my v0.23.0 to-do list.  I'm just working a little more slowly right now.

**Comment by DeputyLOL** [comment]
ok thanks, I ran into some problems with the variables... when I tried to add MATH_ALTITUDE to my PFD (replacing ALTITUDE) it disappeared completely! I basically copied it from the wiki. I also added the airspeed in knots but that only appeared as NaN.
I looked at the log and found this:
[ERR 00:20:21.987] RPMVesselComputer: Processing error while processing MATH_AIRSPEED_KNOTS: Input string was not in the correct format

[LOG 00:20:21.990] VariableOrNumber: Warning: MATH_AIRSPEED_KNOTS can fail to produce a usable number.
[LOG 00:20:21.996] TextRenderer: Warning: Attempted to print a character "	" (u	) not present in the font.
[ERR 00:20:22.002] RPMVesselComputer: Processing error while processing MATH_AIRSPEED_KNOTS: Input string was not in the correct format

That last message is repeated throughout the log.... and always has an empty line after it.

**Comment by MOARdV** [comment]
I tested out the MATH_ALTITUDE_FEET variable, and it works for me.  The MATH_AIRSPEED_KNOTS error in the log sounds like a string format error.  What does the line for the PFD look like (the one that uses AIRSPEED_KNOTS)?

**Comment by DeputyLOL** [comment]
There are a bunch of other things in this line.
[@y-16]			[font4][@x1]{2,1:"[#ff0000ff]I[#ffffffff]";"";""}	[@y-14][font1]{1:000}[font4][@y-16][@x-2]{2,1:"[#ff0000ff]A[#ffffffff]";"";""}[@y-14]																[@x103][font1][#00FF00FF]{0:00000}	  $&$ MATH_ALTITUDE MATH_AIRSPEED_KNOTS CUSTOM_PFDSPEEDALERT

**Comment by DeputyLOL** [comment]
Is it because of the "000"?

**Comment by MOARdV** [comment]
The 000 should not matter.  I'll try it out here and see if I can reproduce the error.

**Comment by MOARdV** [comment]
I tried it out, and it works for me without error.  Did you double-check the variable names?  Are you using MATH_AIRSPEED_KNOTS anywhere else?  For that matter, how is AIRSPEED_KNOTS defined?

**Comment by DeputyLOL** [comment]
RPM_MATH_VARIABLE
{
   name = AIRSPEED_KNOTS
   operator = MULTIPLY

   sourceVariable = EASPEED
   sourceVariable = MetersPerSecondToKnots
}

**Comment by MOARdV** [comment]
I'm using that definition, and I don't have an error.  You do have the latest RPM dev v0.23.0 build from DropBox, correct?  Do you see the lines in the log that say "I know about MATH_AIRSPEED_KNOTS"?

**Comment by DeputyLOL** [comment]
Works now, although the altitude in feet is way bigger than I thought. It makes landing with the GPWS altitude call outs difficult because the altitude changes so quickly. I may go back to meters and just pretend its feet.
May I suggest feet per minute for vertical speed.
Also, I wanted to ask about a variable that tracks the change in radar alt. DELTA_RADARALT? So that I can have an alarm when you are climbing slowly while flying towards a rather steep and solid mountain.

**Comment by MOARdV** [comment]
Meters to feet is about 3.3, so 10km is about 33,000 feet, for instance.

I'll add a constant for m/s -> ft/min.

I'll see about adding the rate of change on the radar altitude.

**Comment by DeputyLOL** [comment]
thanks, Ive gone back to meters because feet are just too small for this game.

**Comment by MOARdV** [comment]
> Also, I wanted to ask about a variable that tracks the change in radar alt. DELTA_RADARALT? So that I can have an alarm when you are climbing slowly while flying towards a rather steep and solid mountain.

That variable exists already, as it turns out: it's TERRAINDELTA.  Returns positive values if the distance to the surface is increasing, and a negative value if it's decreasing.

**Comment by DeputyLOL** [comment]
is that if the terrain is getting heigher or lower or if you are getting closer to it?

**Comment by MOARdV** [comment]
It measures the distance between the craft and the ground - so it's negative if you're getting closer to the ground, and positive if you're moving away.

**Comment by DeputyLOL** [comment]
ok, thank you.

**Comment by DeputyLOL** [comment]
I think it is the rate of change of terrain height and not the change in distance to terrain, unless it's not counting the ocean.
I have had my plane maintain a height using the radar altimeter only to have the terrain alarm go off saying that the terrain coming towards me. Also, when flying up a hill at a constant rate, the terrain alarm activates even though the radar altitude is not changing.

**Comment by MOARdV** [comment]
Okay.  I will review the code - I thought I had it using the value for RADARALTOCEAN and tracking the difference, but maybe I misread what I did.

**Comment by MOARdV** [comment]
I double-checked the algorithm.  What it does is take the ALTITUDEBOTTOM variable (which itself is derived from RADARALTOCEAN).  Every second or so, it saves the current difference (ALTITUDEBOTTOM - previous ALTITUDEBOTTOM) and uses that value as terrainDelta (so a positive value if the aircraft is moving away from the terrain).  There is no smoothing applied to the variable, and it's not a rate value - it's the raw height difference.  It uses the ocean, not terrain height, when the aircraft is "feet wet".  I'll see if I can avoid crashing a plane long enough to fly around the space center a bit to look at how the variable reports (and maybe increase its update rate to higher than 1Hz).  If you haven't already accounted for this, you will want to have an alarm that has a dead zone near zero - if you are checking for any positive number, a 1mm difference will trigger the alarm, for instance.

**Comment by MOARdV** [comment]
Okay - TERRAINDELTA is too low frequency and too noisy for use as a radar altimeter VSI.  I'll add a variable that provides smoothing to the value (and a higher frequency update rate) for use as a radar VSI.

**Comment by MOARdV** [comment]
I'm adding RADARALTVERTSPEED.  I've checked it works as well as it can.  Radar altitude is a very noisy value, especially over rougher terrain, so I'm applying smoothing to make it more useful.  You will still see places where it swings wildly (clearing the land/sea transition, going over hills, and especially over mountains), so for an alarm I would use it as part of a custom variable so that it's ignored when you've above a "safe" radar altitude.

**Comment by DeputyLOL** [comment]
I do have a dead zone, how come the alarm triggers when I'm going up a hill that has an incline the same as mine?
(meaning I'm going up the hill at the same rate that the terrain is)

**Comment by MOARdV** [comment]
I'm not sure, without duplicating your flight parameters.  When I get the new dev build out, give it a try (with the new variable) and see if you're still seeing the problem.

**Comment by DeputyLOL** [comment]
ok
