### ISSUE TITLE
Integrate stock comms

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#354]
KSP 1.1 will introduce some sort of communications relay concept (something like the Antenna Diversity mod).  When it drops, RPM should expose whatever values it can (valid connection to KSC, whatever else).

**Comment by IntegerMan** [comment]
That'd be awesome. I already find myself wanting to know if a communication link is active when playing with Remote Tech or a page to view antenna retracted / extended status / the progress of outgoing messages.

**Comment by MOARdV** [comment]
This feature appears to be pushed to KSP 1.2, so I'm moving this to the corresponding RPM milestone.

**Comment by MOARdV** [comment]
This actually was implemented with pull request #625.
