### ISSUE TITLE
i still have this issue

### ISSUE THREAD

**Issue by thekerbalwow** [Mihara/RasterPropMonitor#355]
i still have this issue plane hud is black square

**Comment by MOARdV** [comment]
I have released a dev build on [DropBox](https://www.dropbox.com/s/wqhmekylfc310am/RasterPropMonitor-dev.0.23.0.zip?dl=0) that might fix the issue.  I need someone to take a look at it and tell me if it's the change fixes the problem.

**Comment by MOARdV** [comment]
I've had confirmation from BinaryLinguist that the changes in the dev build fix this problem.  You are welcome to try the dev build, or to wait for v0.23.0
