### ISSUE TITLE
Mech Jeb Space plane guidance

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#362]
I thought I posted this issue, but when I looked for it I couldn't find it so I was probably dreaming at the time.
Anyway, can we have access to mechjeb spaceplane guidance. (I know that at the moment it is very bad at flying the plane but I wanted a legitimate autopilot function). The main thing i'm interested in is the altitude and heading hold function. if there could be some way to "input" the heading and altitude into mechjeb then tell it to hold, I could have a very automated plane!

My idea for that stems from real life planes, can we have some kind of twister knob that increases or decrease a number display. When the number you want is entered you can press a button and send it to mechjeb.

![autopilot](https://cloud.githubusercontent.com/assets/12616126/9827110/ff30ea7e-58d6-11e5-8fb3-839b8f33c9eb.jpg)

Variables saying when the aircraft is at its selected altitude and when it leaves the selected altitude would also be very helpful.

**Comment by MOARdV** [comment]
Based on past attempts at input, I don't know if the twist-knob functionality will be practical.  I can give that a try to see how it plays.

As for spaceplane guidance - the last time I checked (which was quite a while ago), the spaceplane guidance module was not exposed in a way that I could link to it.  That may have changed, or the technique I'm using now may work differently, so I will have to check into that, as well.

**Comment by MOARdV** [comment]
It looks like at least the MechJeb control aspect (turn on / turn off landing guidance and hold altitude) is workable.  A variable reporting at altitude is okay, but I need an idea of how close to the target altitude is considered "at altitude" - it'll almost always be a little bit off from the exact value, so do you use a percentage of the target altitude (say, +/- 5%), or an absolute magnitude (+/- 500 meters)?

The data input feature will require more experimenting (it will most likely go into a separate issue, since I need to solve it in the general sense).

**Comment by DeputyLOL** [comment]
I think +\- 500 meters would be good. I don't know if the game supports it but j had an idea of a click and hold type knob. I recently found out about the odometer feature and I wanted to ask if it was possible to add these to the rpm screens. Kind of like vertical bars instead of have the text. You could also you the odometer as the display for heading and altitude if needed!

**Comment by DeputyLOL** [comment]
Also, I wouldn't work too hard on the 'leaving altitude' variable. Mechjeb space plane guidance flies badly and sends into a rollacoaster ride trying to stay on course.

**Comment by MOARdV** [comment]
Spaceplane guidance (hold altitude and autoland) were pretty easy to do.  I've added plugin variables to query glideslope, hold altitude, and hold heading.  I'll also add the query to determine if the craft is within +/-500 of the goal altitude. That's also possible math variables, now that I think about it, and it lets you customize the hold tolerance: make a math variable that takes the current spaceplane altitude and adds 500 (MATH_UPPERHOLDALT), a second one that subtracts 500 (MATH_LOWERHOLDALT), and compare ALTITUDE to those values.  I'll still add a basic query, since it'll be less computationally expensive.

**Comment by DeputyLOL** [comment]
Thanks for the help,
But I'm having problems with the maths variables again. I tried using ALTITUDEBOTTOM and put it into feet but it won't work. The log says that my new variable fails to produce a usable number and then is flooded with 
"Attempt to set pitch to infinite values from script ignored!"
I've also noticed that some FAR variables have also stopped working. (AoA, Sideslip and terminal velocity)
I now seem unable to create anymore math variables. But the ones I already had are still working. I would paste the log but I'm using my phone to see this and my PC has no internet.

**Comment by MOARdV** [comment]
I will take a look at FAR - I may have messed something up with it during all of the code changes I've made recently (and there's a newer version of FAR).  I wish I knew what was going on with the math variables - the ones I've tried, including the one you provided the other day, all are working for me.

**Comment by DeputyLOL** [comment]
The messages start spamming when the aircraft is moving and on the ground. When I try and put it on a display to see what it sees, it just has the variable name. And the vertical bar that is suppose to use it isn't there at all. Is it because is doesn't like 0 or negative numbers? I'm gonna check norton in the mean time. I'll keep you posted

**Comment by MOARdV** [comment]
If you see the variable name, it means the variable isn't being found.  Remember that if you're using the FAR methods directly, you need to prefix them with PLUGIN_ (as in PLUGIN_JSIFAR:GetAngleOfAttack) to treat them as a variable.  I just tested my FAR installation, and the variables are working for me.

**Comment by DeputyLOL** [comment]
I think these are variables from the ALCOR mod. But I noticed that the FD on his artificial horizon was static. I'm not having any trouble with my uses of FAR but it came up in the log. 
When I tried to put a math variable that i made it comes up as the variable name. Even though I am certain that it's there. For once, norton had nothing to do with this!

**Comment by DeputyLOL** [comment]
Problem solved... Somehow. Turns out KSP just needs to crash before it gets sorted. The math variables work but I still have a log flooded by "Attempt to set pitch to infinite values from script ignored!" When I'm on the ground and moving. I'm gonna look into that later. 

BTW, do you think there could be a way to use the odometer on a rpm screen. 

And out of curiosity, what's this Radar that you added?

**Comment by MOARdV** [comment]
I wonder if your problem is with Module Manager not realizing it needs to clear its cache.  Next time something like that happens, manually delete the ModuleManager.ConfigCache in your GameData directory.

As for the log - I don't set pitch anywhere in RPM, so I would suspect something else there.

I can probably update the odometer code to work with a regular screen (it's currently a very specialized version of an RPM screen).

The JSIRadar allows the vessel to automatically select a target.  You can configure the range and the scan width, and set some extra optional parameters to cause it to lose lock if the radar is shut off, or if the target moves outside the radar scan cone.  Details are here https://github.com/Mihara/RasterPropMonitor/wiki/Part-modules#jsiradar and I'll get a dev build for it out today.

**Comment by DeputyLOL** [comment]
ok, im having problems with my game again. My log is being spammed with 3 messages.
[Log]: Look rotation viewing vector is zero
[LOG 23:55:48.358] RPMVesselComputer: vessel.totalmass = 48.53754, piece-wise adding = 46.59859 (wet) 40.23705 (dry)
(That last one keeps changing with the engines on, I think its fuel load that keeps updating in the log)
I'll try your method.
I set up a button that is meant to turn the space plane alitiude hold on, but AFTER SIFTING THROUGH THE LOG I found this:
[ERR 00:10:47.638] Cannot find an InternalModule of typename 'MechJebRPMButtons'
[ERR 00:10:47.641] InternalProp: Failed finding module MechJebRPMButtons for method ButtonSpaceplaneHoldHeading
[ERR 00:10:47.644] JSIActionGroupSwitch: Failed to instantiate action handler MechJebRPMButtons
[LOG 00:10:47.648] JSIActionGroupSwitch: Plugin handlers did not start, reverting to dummy mode.

I know it means that it didn't like the button I set up but the wiki says I could use "MechJebRPMButtons"

**Comment by MOARdV** [comment]
That "vessel.totalmass" spam should not be in there - I suspect you've got an earlier dev build.  I removed it a few days ago.  That's probably why the control failed to set up - it's not in the dev build you have.

**Comment by DeputyLOL** [comment]
ok thanks for the help

**Comment by DeputyLOL** [comment]
I still haven't had any luck. The variable is coming back as -1 which means that it's not working. Did I miss something?

**Comment by DeputyLOL** [comment]
I still cant get the space plane guidance to work. This is my button:
		PLUGINACTION
		{
			name = MechJebRPMButtons
			actionMethod = ButtonSpaceplaneHoldHeading
			stateMethod = ButtonSpaceplaneHoldHeadingState
		}
It doesn't work in variables either as it comes up as -1.

**Comment by MOARdV** [comment]
I don't get it.  I tried both MechJebRPMButtons and JSIMechJeb, and both did the same thing (return -1).  I added some code to print out what was happening, and it started working.  I removed the code (so it's just like it was previously), and it is still working.

**Comment by DeputyLOL** [comment]
sounds weird... hope you can figure it out!

**Comment by DeputyLOL** [comment]
is it working?

**Comment by MOARdV** [comment]
It's working for me.  I will get another update out hopefully today.

**Comment by DeputyLOL** [comment]
Did you fix it in the latest dev build? I am still getting a reading of minus one.
Do I need a special version of mechjeb?
Or am I missing something else?
My button still reverts to dummy.

**Comment by MOARdV** [comment]
What version of MechJeb are you using?  Maybe that's the issue - I'm on a dev version 512 here, and I was using 508 previously.  I'm not sure when exactly the MechJeb changes went in, so maybe that's the problem?

**Comment by DeputyLOL** [comment]
I think I'm using the 5.1.2 version

**Comment by DeputyLOL** [comment]
Has JSI numerical input been put in the wiki.
I'm still having problems with mechjeb btw. I double checked that I was using 5.1.2 and redownloaded it. The button still doesn't work....

**Comment by DeputyLOL** [comment]
The nurmerical input works. But anything connected to mechjeb doesn't. I cant transfer anything and the my hold alt button still isn't working. The log says this:
[Error]: RPMVesselComputer: I failed to find the method for JSIMechJeb:ButtonSpaceplaneHoldHeadingState

Have I missed something?

**Comment by DeputyLOL** [comment]
Nothing connected to mechjeb works!
More of the log. 

[ERR 16:42:45.292] Cannot find an InternalModule of typename 'JSIMechJeb'
[ERR 16:42:45.295] InternalProp: Failed finding module JSIMechJeb for method SpaceplaneHoldAltitude
[ERR 16:42:45.298] JSIActionGroupSwitch: Failed to instantiate transfer handler JSIMechJeb
[LOG 16:42:45.302] JSIActionGroupSwitch: Transfer handlers did not start, reverting to dummy mode

[ERR 16:42:45.032] Cannot find an InternalModule of typename 'MechJebRPMButtons'
[ERR 16:42:45.035] InternalProp: Failed finding module MechJebRPMButtons for method ButtonSpaceplaneHoldHeading
[ERR 16:42:45.038] JSIActionGroupSwitch: Failed to instantiate action handler MechJebRPMButtons:ButtonSpaceplaneHoldHeading
[LOG 16:42:45.043] JSIActionGroupSwitch: Plugin handlers did not start, reverting to dummy mode.

**Comment by MOARdV** [comment]
I just double checked on my system, and it works for me.  I need you to provide me the complete log, not just excerpts, so I can try to figure out what is going on.  It would also help to have the config files for the props that are not working for you.

**Comment by DeputyLOL** [comment]
Log: https://raw.githubusercontent.com/DeputyLOL/KSP-Log/master/README.md

**Comment by DeputyLOL** [comment]
Button: Toggle Heading Hold
PROP
{
  name = switch_B_Button01_ALTHOLD
 
//---------------- Action -------------------------
	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = plugin
		switchSound = ASET/ASET_Props/Sounds/B_Button01_Click
    		PLUGINACTION
    		{
		        name = MechJebRPMButtons
		        actionMethod = ButtonSpaceplaneHoldHeading
		        stateMethod = ButtonSpaceplaneHoldHeadingState
		}
	}

**Comment by DeputyLOL** [comment]
Button: Send selected altitude to mechjeb (numerical value works)
PROP
{
  name = switch_B_Button01_ALTHOLD_ALT_SELECT
 
//---------------- Action -------------------------
	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		switchSound = ASET/ASET_Props/Sounds/B_Button01_Click
		TRANSFERACTION
		{
	    		name = JSIMechJeb
	    		setMethod = SpaceplaneHoldAltitude
	    		perPodPersistenceName = HOLDALT
		}
	}

**Comment by DeputyLOL** [comment]
A text file that is displayed on a screen 
(THE FIRST NUMBER WORKS, ONLY THE 2ND AND 3RD DONT):
------------FMC----(DEV)-----
{0:0} $&$	PLUGIN_JSIMechJeb:SpaceplaneHoldAltitude
{0:0} $&$	PLUGIN_JSIMechJeb:ButtonSpaceplaneHoldHeadingState
{0:0} $&$	PLUGIN_JSIMechJeb:ButtonSpaceplaneAutopilotState
{0:0} $&$	MATH_TARGETALT
{0:0} $&$	PERSISTENT_HOLDALT

**Comment by DeputyLOL** [comment]
hope this is enough.

**Comment by MOARdV** [comment]
Moving the bug discussion to Issue #385
