### ISSUE TITLE
Double check yaw/pitch math

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#367]
It looks like the yaw value's never > 90, which I would expect to see if the vector in question is behind the craft.

**Comment by ndevenish** [comment]
Hmm. I can't decide whether this is correct or not.

In theory the values are correct considered individually but together it depends on the intended usage - I know you said these aren't theoretically intended for navball usage, but I find it easiest to think in such terms - e.g. a unit sphere navball with vessel pointing towards prograde directly, prograde is shown at (pitch:0,yaw:0), RHcartesian(0,0,1). This algorithm gives retrograde as (pitch:180,yaw:180), so naively rotating by yaw then pitch will put the retrograde marker first at RHcartesian(0,0,-1) but then rotate 180 degrees over the top back to RHcartesian(0,0,1).

Funnily enough, I think the solution is just to use the old-style method for one of the variables - I'd do pitch, personally, or rely on the user to `ArcSin(Sin(theta))`, which throws away the phase information (and adding to the return value seems to give the right result in my version).

Also, having read the forum post (telling me to do it myself :open_mouth:) and not the subsequent correction, I did implement it myself. Here is my imlementation with the above fix:
```c#
private double GetRelativePitch(Vector3 normalizedVectorOfInterest)
{
    // vector projected onto a plane that divides the airplane into left and right halves. top and fwd lie on this plane
    Vector3 tmpVec = Vector3.ProjectOnPlane(normalizedVectorOfInterest, right).normalized;
    // Work out the components in the up, fwd directions
    float topComponent = Vector3.Dot(tmpVec, top);
    float fwdComponent = Vector3.Dot(tmpVec, forward);
    // Derive the full-phase angle for this
    float pitch = Mathf.Atan2(topComponent, fwdComponent);
    // Constrain this to just the relative pitch angle
    return Mathf.Rad2Deg * Mathf.Asin(Mathf.Sin(pitch));
}

private double GetRelativeYaw(Vector3 normalizedVectorOfInterest)
{
    //velocity vector projected onto the vehicle-horizontal plane. forward and right lie on this plane.
    Vector3 tmpVec = Vector3.ProjectOnPlane(normalizedVectorOfInterest, top).normalized;
    // Work out the components in the fwd, rightdirections
    float fwdComponent = Vector3.Dot(tmpVec, forward);
    float rightComponent = Vector3.Dot(tmpVec, right);
    // We want relative to up, so for purposes of atan2 up === x, right === y
    return Mathf.Rad2Deg * Mathf.Atan2(rightComponent, fwdComponent);
}
```

**Comment by MOARdV** [comment]
Yeah, I thought that maybe I got carried away converting both methods to return values in the range[-180, 180].  I agree that changing the pitch to a [-90, 90] range makes more sense.
