### ISSUE TITLE
Pilot Assist Intergration

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#368]
As mechjeb isn't really designed for flying planes with FAR, I looked for an alternative.
I found this:
http://forum.kerbalspaceprogram.com/threads/100073-1-0-x-Pilot-Assistant-Atmospheric-piloting-aids-1-9-3-%28May-18%29
Github: 
https://github.com/Crzyrndm/Pilot-Assistant

Its basically a mechjeb built for planes. (except it doesn't have the auto landing feature)
This works perfectly and has most the things a proper autopilot has! If this was made to work with RPM, then I could have a fully functional autopilot for my cockpit. The downside is that it seems to override a lot of stock controls and it doesn't use modulemanager (I think). 

Let me know what you think.

**Comment by DeputyLOL** [comment]
Do you think this is possible?
RPM has come a long way and now has the means to input numbers into mechjeb. If this was supported then it could mean having a very realistic autopilot that can be controlled in IVA.

**Comment by MOARdV** [comment]
Yes, this is possible.  I'll download the mod and start looking at integrating with it.

**Comment by DeputyLOL** [comment]
THANK YOU

**Comment by MOARdV** [comment]
Have you seen this? 

http://forum.kerbalspaceprogram.com/threads/135840-1-0-4-Kramax-Autopilot-Course-guidance-and-auto-land-for-spaceplanes-%28v0-2%29

It looks like it's based on pilot assistant, from what I read.  I haven't looked at it or pilot assistant yet, so I don't know if they overlap in function, or if they're two separate things.

**Comment by DeputyLOL** [comment]
yeah, im using this now. it takes a lot from pilot assist, I'm not sure if it requires PA to work but I certainly wouldn't complain if you implemented it. :)
I'm trying to phase out using mechjeb because it keeps crashing my plane when I try and autoland.

**Comment by DeputyLOL** [comment]
If you do end up integrating it, do you think there would be a way of displaying the flight plan? Having variables such as waypoint name, altitude, heading, etc... Or even be able to list all the waypoints on the current plan?

**Comment by MOARdV** [comment]
If I can get it working, I should be able to include waypoint and flight plan info - that seems to be the main feature of the autopilot functionality.

**Comment by DeputyLOL** [comment]
how about the input format? It uses ground speed in m/s. would it be possible to change that to airspeed or change the unit?
Or is that up to kramax?

**Comment by MOARdV** [comment]
I finally succeeded in building a flyable space plane, and I installed PA.  I'll have to modify the IVA to add some controls for testing, but it looks like I'll finally get this working in the next couple of weeks (as long as work doesn't interfere :D )

**Comment by Alexustas** [comment]
do you need some special prop to work on this?

**Comment by DeputyLOL** [comment]
awesome! 
are you just working on PA or will you consider the kramax autopilot too later?

**Comment by MOARdV** [comment]
@Alexustas : I think I can use the 4 digit and 8 digit MFDs you supplied for the number displays, and the numeric input dials you made DeputyLOL on your props request for the inputs, so I don't think I need special props for development.

@DeputyLOL : For now, PA.  I still need to go back through the mod and figure out what I can control.  Once I have it working (hold altitude, hold heading, hold speed for sure - what other options are needed?  hold pitch?  hold vertical speed?) - once it is working, I can start looking at the kramax autopilot.

**Comment by DeputyLOL** [comment]
ok good to know. Hold vertical speed would be needed and hold bank.
The problem I have is that when you switch modes or enable an section of PA. The numbers you enter are changed to your current situation. E.g. If you enter an altitude and then switch the 'Pitch' autopilot on, the altitude will change to your current altitude so you have to change it back again.
This is very dangerous when climbing at low altitudes as it means you can't set an altitude without  PA controlling your plane and immediately trying to descend to its set altitude.
Or if you select a vertical speed, switch to the altitude mode and then back again, the vertical speed will change to your current vspeed.

The last problem I have is that the autothrottle uses ground speed in m/s. This speed changes with height and so useless at trying to maintain a steady speed while decending or climbing. Would it be possible to have this in airspeed?

**Comment by MOARdV** [comment]
> The problem I have is that when you switch modes or enable an section of PA

Yeah, I saw that last night while flying.  I'm going to propose that be changed in the PA mod.  I also intend to have the RPM function be a "direct set" where you select the value and push the button, and that's applied.  However ....

PA will require changes to allow me to do that in the first place.  I'll open a request on that mod's issue tracker with the specifics I need.

> The last problem I have is that the autothrottle uses ground speed in m/s

Looking at the PA source code, it has enumerants defining different units, and different speeds (true, indicated, effective).  It looks like none of that is hooked up yet, though, so that may be a future feature.

**Comment by DeputyLOL** [comment]
ok, I saw the different speeds in the kramex codes too. Probably because the kramex autopilot is based heavily on the PA mod.

**Comment by MOARdV** [comment]
PA 1.12.1 included some functions RPM can use to interact with it, so I don't have the excuse to say "Waiting on third party" any longer. :)

**Comment by DeputyLOL** [comment]
sweet!

**Comment by DeputyLOL** [comment]
a few questions...
When PA is active, are the normal controls still disabled? (WASD controls PA inputs when active instead of controlling control surfaces)
Is it possible to set maximums and minimums from RPM?

**Comment by MOARdV** [comment]
> When PA is active, are the normal controls still disabled?

Probably yes.  I will try it out and see (I have vertical speed mode partially working).

> Is it possible to set maximums and minimums from RPM?

I can look into that.  I didn't ask for it, so it may not be available yet.

**Comment by MOARdV** [comment]
Here's how the interface is going to look:

There is a `SetVertPitch(bool)` that can turn on or off the pitch controller.  There is also a horizontal and velocity control that do the same thing.  These all behave the same as clicking on the top button in each section of the PA GUI - they toggle the controller on or off, but they do not change modes.

There is a `bool GetVertPitch()` that returns whether the pitch controller is on or off.  Likewise, there are horizontal and velocity 'Get' methods, too.

There is a `double GetVertMode()` that returns what mode the vertical pilot is in (0 for pitch, 1 for Vert Spd, etc).  There is also a `double GetVertSetting()` that returns the setting of the current mode (so, if GetVertMode indicates VSpeed, then GetVertSetting returns the current setting for VSpeed).  This is something that you'll want to pay attention to, since the setting depends on the mode (you can not query the vertical pitch setting if the pilot is in vert sped mode, for instance).

To change modes, you also have to set the value - eg. `SetVertAltitude(double)` will turn on the vertical controller, set it to 'altitude control', and set the target altitude all at once.  There are other methods as well for the other controller modes (`SetVertRadarAltitude`, `SetVertRate`, `SetVertPitch`).  Horizontal and speed controllers both have similar methods.

**Comment by DeputyLOL** [comment]
great... cant wait

**Comment by MOARdV** [comment]
Okay, the dev build is updated on [DropBox](https://www.dropbox.com/s/gaplio91e94fej1/RasterPropMonitor-dev.0.24.1.zip?dl=0), and I remembered to document it on [the wiki](https://github.com/Mihara/RasterPropMonitor/wiki/JSIPilotAssistant).

The mins/maxs are not controlled (I haven't looked into that yet), and I have not tested every single method since it requires setting up many controls to test all of them - I know the vertical pilot stuff works, since that's what I was using during development.  Horizontal and throttle control should work, but no guarantees yet (I'm still working on a space plane cockpit for testing this stuff, so I will eventually get it tested out).  I also forgot to check whether the keyboard overrides were working, but I am pretty sure they weren't (but, again, I may not have noticed).  If they are, I can put in a request to add a way to disable that.

All of this requires Pilot Assistant v1.12.1 from 2 days ago, since that's where the RPM methods were added.

**Comment by MOARdV** [comment]
> The mins/maxs are not controlled (I haven't looked into that yet),

... And now I've checked.  They're not exposed, and I'll need to ask for some more code changes in PA to allow them to be easily edited from RPM.

**Comment by DeputyLOL** [comment]
ok, thank you
ill have a look

**Comment by MOARdV** [comment]
I found a few bugs - I've now verified all of the vertical controls work right ('hold pitch', 'hold altitude', and 'hold vertical speed'), 'hold ground speed' works, and 'hold heading' work.  The remaining ones should, as well, but I haven't configured props to test them.  Updated on [DropBox](https://www.dropbox.com/s/gaplio91e94fej1/RasterPropMonitor-dev.0.24.1.zip?dl=0)

**Comment by DeputyLOL** [comment]
Ive set up an autopilot interface and I'm trying to get the hold altitude to work first. Theres a lot of coding to be done and its going to get complicated!
For the GetVertSetting, GetHorzSetting, GetThrottleSetting. Does it return what is in the box of the current mode?
And if it does, should this work?
RPM_SELECT_VARIABLE
{
    name = AUTOP_PA_ALTITUDE_MATH

    defaultValue = 100

    VARIABLE_DEFINITION
    {
        name = PLUGIN_JSIPilotAssistant:GetVertMode
        range = 1.5, 2.5

        value = PLUGIN_JSIPilotAssistant:GetVertSetting
    }
}

**Comment by DeputyLOL** [comment]
Basically, show 100 unless the hold altitude mode is selected, then show the altitude in the box.

**Comment by DeputyLOL** [comment]
hmmm, just checked and it seems all the variables are returning as -1....

**Comment by DeputyLOL** [comment]
nevermind, works now!

**Comment by DeputyLOL** [comment]
can you tell me whats wrong with this?

RPM_MATH_VARIABLE
{
   name = HOLDALT_PA
   operator = DIVIDE

   sourceVariable = PERSISTENT_HOLDALT
   sourceVariable = MetersToFeet
}

(HOLDALT is a numerical input)

I'm trying to change all my displays from meters to feet. This display is 'already in feet' so I need an output in meters to send to Pilot Assist.
However, it didn't work and when I did some investigating I found that the output of MATH_HOLDALT_PA was 'FORMAT ERROR' of something like that.

On a related note, is it possible for a single button to perform multiple transfers at once?

**Comment by MOARdV** [comment]
> can you tell me whats wrong with this?

I don't see anything wrong with it at first inspection.  Have you tried displaying PERSISTENT_HOLDALT and MetersToFeet as well?

> On a related note, is it possible for a single button to perform multiple transfers at once?

Not yet :)  I've thought it'd be useful to have a compound action button.  I'll write myself a reminder.

**Comment by DeputyLOL** [comment]
The persistent is working properly and I assumed that MetersToFeet would be a static number.
Would it possibly have something to do with the MATH variable being in this?
		TRANSFERACTION
		{
	    		name = JSIPilotAssistant
	    		setMethod = SetVertAltitude
	    		perPodPersistenceName = HOLDALT_PA
		}
		TRANSFERACTION
		{
	    		getVariable = MATH_HOLDALT_PA
	    		perPodPersistenceName = HOLDALT_PA
		}
		TRANSFERACTION
		{
	    		getVariable = PERSISTENT_HOLDALT
	    		perPodPersistenceName = HOLDALT_PFD
		}

**Comment by DeputyLOL** [comment]
All on one button....

**Comment by MOARdV** [comment]
Right now, only one TRANSFERACTION is supported in a single button.

**Comment by DeputyLOL** [comment]
what if the button config was written twice?

**Comment by DeputyLOL** [comment]
Like this?

	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		masterVariableName = CUSTOM_AUTOP_LVLCHG
		masterVariableRange = -0.5, 0.5
    		perPodPersistenceName = ALT_SELECTED
		switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		TRANSFERACTION
		{
	    		name = JSIPilotAssistant
	    		setMethod = SetVertAltitude
	    		perPodPersistenceName = HOLDALT_PA
		}
	}
	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		masterVariableName = CUSTOM_AUTOP_LVLCHG
		masterVariableRange = -0.5, 0.5
    		perPodPersistenceName = ALT_SELECTED
		//switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		TRANSFERACTION
		{
	    		getVariable = MATH_HOLDALT_PA
	    		perPodPersistenceName = HOLDALT_PA
		}
	}
	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		masterVariableName = CUSTOM_AUTOP_LVLCHG
		masterVariableRange = -0.5, 0.5
    		perPodPersistenceName = ALT_SELECTED
		//switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		TRANSFERACTION
		{
	    		getVariable = PERSISTENT_HOLDALT
	    		perPodPersistenceName = HOLDALT_PFD
		}
	}

**Comment by DeputyLOL** [comment]
Also, on the subject of pilot assist. Could there be a 'setMode' option? We can already get the modes the autopilots are in, but currently the only way to select a mode is to use the 'setaltitude' or something but that changes the setting and engages the autopilot immediately.

**Comment by DeputyLOL** [comment]
And metertofeet doesn't show up on a display for some reason

**Comment by MOARdV** [comment]
> Also, on the subject of pilot assist. Could there be a 'setMode' option?

I can add that, but it will have the same behavior as the mod does - if you change modes and enable, the current aircraft situation is used (so, if you setMode to 'hold altitude', the current altitude becomes the set point, overriding anything else that's been set).  If that's okay behavior, I'll add the option.

**Comment by DeputyLOL** [comment]
That's fine, my autopilot requires you to 'set' an altitude before it will enable it.

**Comment by MOARdV** [comment]
> That's fine, my autopilot requires you to 'set' an altitude before it will enable it.

What I'm trying to say is this:

1 - aircraft is flying.
2 - you set "hold altitude" set point (using a numeric input, or whatever that sets a PERSISTENT)
3 - you use a new "SetMode(hold altitude)" like you're asking about.
4 - aircraft will switch to "hold altitude" mode using whatever the current aircraft altitude is, not the value you have in your persistent.

That's the way Pilot Assistant works - if you enable a mode without setting the value at the same time, you'll get the current aircraft parameter for the set point.  There's no way to set an altitude, and enable the autopilot later, and have that altitude be the set point, unless you call the SetVertAltitude method.  Does my explanation make sense?  Or am I misunderstanding your response?

**Comment by DeputyLOL** [comment]
I totally understand.
The one question I have is, if I change mode, will it engage the autopilot or just change its mode?
If it doesn't then that's perfect!

I wanted a sort of 'LEVEL OFF' Method for my autopilot and the behaviour you just described pretty much fits that exactly.

In my plane if you want to set an altitude:
- Engage 'CMD' (allows autopilot control)
- Select 'ALT HOLD' (engage the altitude hold function, pressing this with CMD enabled switches on autopilot)
- Select the altitude you want then press 'LVLCHG' and the autopilot target will be updated.

The only problems I have with the autopilot is that its figity to disengage quickly. Real life autopilots can be disengaged just by moving the control column. I know that you asked PA about having an option to turn this off, but I was wondering if the control input variable only takes keyboard inputs or inputs on the aircraft.

Meaning if PA does have that option, is there a variable that only tracks the users input on the craft and not Pilot assistants?

**Comment by MOARdV** [comment]
> I wanted a sort of 'LEVEL OFF' Method for my autopilot and the behaviour you just described pretty much fits that exactly.

Switching between modes to a VSpeed 0 would trigger the behavior as a 'LEVEL OFF'.  Of course, once I figure out how to make compound switch behavior, that would be easy to do as a single button.

> Meaning if PA does have that option, is there a variable that only tracks the users input on the craft and not Pilot assistants?

PA has a variable called "Lock Inputs", which looks like it ignores keyboard inputs.  I still haven't actually checked its behavior (been busy fixing some little things, learning to fly a space plane, and testing a spaceplane cockpit), but I will try to check it out this morning.

**Comment by DeputyLOL** [comment]
does rpm have a control input variable?
I was wondering if we could use that to disengage certain parts of the autopilot.
E.g. When you try and pitch down, the vertical autopilot switches off.
But this wont work is RPMs control input variable reads PA inputs as well.

**Comment by DeputyLOL** [comment]
You can have a look at my first attempt. This autopilot features a altitude hold and a heading hold.
If can also see a few bugs I'm running into. (I gave up on trying to make my plane read altitude in feet because that math equation still produced FORMAT ERROR).
Also, in the video, the vertical speed is display on top of the altitude... and the video didn't record my mouse!

https://youtu.be/IBIqk6j2qyM

Basically:
CWS = Control Wheel Steering = SAS
CMD = Command = Autopilot can control the plane
ALT HOLD = Set the vertical autopilot to altitude mode (and switch it on if CMD is on)
HEADING = Set the horizontal autopilot to heading mode (and switch it on if CMD is on)
APP = Used to be space plane guidance, not used now.
LVL CHG = Transfer the displayed altitude into PA (bug in video, also enables the autopilot, I'm working on a fix)
VNAV = Vertical Navigation = GS on kramax autopilot (doesn't work now)
LNAV = Horizontal Navigation = NAV on kramax autopilot       "

More stuff later

You can also see in the video that the nav utilities mods screen is very dim

**Comment by MOARdV** [comment]
> does rpm have a control input variable?

No.  And I checked behavior of the control system - with PA engaged with a vertical hold, pitching the aircraft simply changes the set point, just like it normally does.  You can engage the 'input lock', but all that does is ignore the relevant keys (so the pitch keys do nothing).  Having RPM monitor flight commands in order to disable the autopilot is way outside the scope of RPM - that is something that needs to be a feature of Pilot Assistant (there is an issues list for that mod here on GitHub, so I'd suggest putting a request over there).

> You can also see in the video that the nav utilities mods screen is very dim

That seems to be unique to the NU mod. RPM doesn't do anything to those screens when another mod is responsible for drawing them, and I haven't heard about a problem with any of the other mods that draw screens.

I'll take a look at the math error issue - that shouldn't be a big thing to fix.

**Comment by MOARdV** [comment]
> I'll take a look at the math error issue - that shouldn't be a big thing to fix.

It works for me.  I set PERSISTENT_HOLDALT (I simply read the current altitude), and I got a value for MATH_HOLDALT_PA that looks right (on the runway, altitude is 70m, and dividing that by MetersToFeet gave me 21.something).  MetersToFeet didn't display, but it shouldn't now that I think about it.  What are you using for the format string on the MFD to display MATH_HOLDALT_PA?

**Comment by DeputyLOL** [comment]
ok thanks, ill try and work something out with it.

**Comment by DeputyLOL** [comment]
I'm having trouble getting it to work smoothly. I'm trying to use select variables to choose the modes but it doesn't work nicely. Currently my way is:
When Alt hold Button persistent on
Use select variable to select '2'
Button then transfers select to persistent
Then different module transfers persistent to plugin.

Also, when I press the button, the autopilot turns on. Not wanted behaviour :(

Would it be possible to have a SetVertMode0, SetVertMode1, SetVertMode2 ...
Same for others. 

I ask this because its difficult to get a select variable into plugin in one button press.

**Comment by DeputyLOL** [comment]
"What are you using for the format string on the MFD to display MATH_HOLDALT_PA?"
{0:0} $&$	MATH_HOLDALT_PA_METERS
I added the _METERS after because I thought it might be interfering with another variable. Turns out... it wasn't.

**Comment by MOARdV** [comment]
Try using {0} instead of {0:0} and see if that makes a difference.

**Comment by MOARdV** [comment]
> Would it be possible to have a SetVertMode0, SetVertMode1, SetVertMode2 ...

Explain to me exactly what the user flow is that you're trying to use (what buttons do what, when is the JSINumeric used to edit values, etc).  Maybe if I understand all the details of how you want it to work, I can figure out how to accomplish that.

**Comment by DeputyLOL** [comment]
hold on, I got the all IVAs disappear bug again...
Ill explain when ive got my ivas back.

**Comment by DeputyLOL** [comment]
found the problem, somehow, another completely different internal config appeared in the internal.cfg file. It was underneath the first one so I had trouble finding it.

**Comment by DeputyLOL** [comment]
Havnt fixed it. For some reason unity is saving the config without removing the previous one.

**Comment by DeputyLOL** [comment]
The autopilot interface should be quick and easy to use/learn. Meaning that having to push buttons in a certain order, or having to press certain button twice should be kept to a minimum.

My autopilot has 2 modes. Manual and Command.
When making selections or inputting variables, it changes the displays so that you can fly what you've entered. The only difference is that in command, the autopilot flies what you've entered. The CMD button is basically the master on/off switch. When its off, the autopilot will still work but it doesn't control the plane.

I use some of the variables from the PA plugin to show information about your flight plan based on the current mode selected. But it can only show the information when PA is also in the right mode. Changing modes should easy and not contain any unwanted 'features' such as turning on/off an autopilot regardless of CMD button without realising

If I use the vertical autopilot as an example. 
You press ALT HOLD while CMD is off, the plane just displays your target altitude for you to follow. If you then press the CMD button, the autopilot takes control and flies to that altitude. Press it again and the autopilot stops controlling the plane but keeps the displays on. 
If you then want to maintain a certain vertical speed, you press the V/S button and the displays stop showing target altitude and start showing target vertical speed. (PA then switches to vertical speed mode)

**Comment by DeputyLOL** [comment]
When in ALT HOLD mode, a new altitude can be selected by using a number dial and then pressing LVL CHG (which transfers the altitude to PA). Problem with that is that it also engages the autopilot.

**Comment by MOARdV** [comment]
> When in ALT HOLD mode, a new altitude can be selected by using a number dial and then pressing LVL CHG (which transfers the altitude to PA). Problem with that is that it also engages the autopilot.

Pilot Assistant does not allow me to set the set point without also engaging the AP.  It looks like I can change mode without engaging, but there is no way to set ALT HOLD in Pilot Assistant without also engaging ALT HOLD.  The options I can do are (using ALT HOLD as an example):

1) Change Mode, do not engage - this will turn off any vertical autopilots (hold VSPD, hold Pitch) and change the mode to hold ALT.

2) Change Mode, engage, do not set hold ALT - this will engage hold ALT and use the current altitude as the set point.  This is what JSIPilotAssistant.SetVertMode does currently.

3) Change Mode, engage, set hold ALT - this engages hold ALT and uses the supplied altitude.  This was in the original implementation of JSIPilotAssistant.

What I can not do, because Pilot Assistant is not designed to do it, is to set the hold ALT without also engaging hold ALT.  If I don't engage hold ALT, the set point is ignored.  If I engage the hold ALT without supplying the set point at the same time, the current altitude is used as the set point.  This is a limitation of Pilot Assistant.

**Comment by DeputyLOL** [comment]
Sorry, I wasnt clear. When I press LVL CHG, that engages the autopilot

**Comment by DeputyLOL** [comment]
Also, I am aware that the limits of PA mean I cant transfer things without engaging the autopilot so I though... why not work around it?
Using the trigger system.
Basically:
IF CMD = OFF & Pilot Assist = ON
THEN Set Pilot Assist to OFF.

Simple :D

**Comment by DeputyLOL** [comment]
And btw, I prefer your first idea!

**Comment by DeputyLOL** [comment]
ALSO, the math variables work now! And ive noticed that my log is now filled up with updating MATH variables from my PFD.

**Comment by MOARdV** [comment]
> And btw, I prefer your first idea!

so, this:

>1) Change Mode, do not engage - this will turn off any vertical autopilots (hold VSPD, hold Pitch) and change the mode to hold ALT.

I can change the current SetMode functions to behave like that, so selecting a new vert mode, for instance, turns off the vert pilot.

**Comment by DeputyLOL** [comment]
I think it would be better if it doesn't toggle the autopilot on or off. It just changes the mode.
If it was on, it stays on and if it was off, it stays off.

**Comment by MOARdV** [comment]
> I think it would be better if it doesn't toggle the autopilot on or off. It just changes the mode.
 If it was on, it stays on and if it was off, it stays off.

Okay.  I've updated the dev build on [DropBox](https://www.dropbox.com/s/gaplio91e94fej1/RasterPropMonitor-dev.0.24.1.zip?dl=0) with that change.

**Comment by DeputyLOL** [comment]
Can you run through how this works now please? Does it use SetVertMode2?
Does it work with triggers, transfers or plugin action handler?

**Comment by MOARdV** [comment]
The only update I did was to change SetVertMode/SetHorzMode/SetThrottleMode so it does not change the state of the pilot (so if you're holding vertical speed and change SetVertMode to hold altitude, the hold altitude pilot is already on, using current altitude).  The Set Mode functions all take parameters using the same values that are returned in Get Mode functions, so they'll work with transfers.

**Comment by DeputyLOL** [comment]
ok, thank you.

**Comment by DeputyLOL** [comment]
Will this work with the newest version?

**Comment by MOARdV** [comment]
I didn't see that there was a new version.  It should work as long as the functions RPM accesses haven't changed signatures.  And the EAS/IAS stuff is not supported yet in RPM.  I won't have time to look into it until later today, and I won't be able to work on the EAS/IAS support until later this week, most likely.

**Comment by DeputyLOL** [comment]
ok

**Comment by DeputyLOL** [comment]
Could you impletment the 'pause control' feature of PA?
Basically, pressing tab pauses all the autopilots.

**Comment by MOARdV** [comment]
> Could you impletment the 'pause control' feature of PA?

It looks like that requires changes in PA.  I can set the 'pause' variable, but input locks won't be switched and PA would be left in a bad state.

**Comment by DeputyLOL** [comment]
I would probably be better to wait for a PA update.

**Comment by MOARdV** [comment]
I think the majority of this is implemented.  Any additional changes should go into a new feature request / issue.
