### ISSUE TITLE
Cannot update changes to MATH_ variables without restarting KSP.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#375]
I don't know if its just me but when I modify or add a MATH_ variable, the changes wont work until the entire game is restarted. Reloading database doesn't work.

If you try and add a new variable, the game says that it cannot produce a useable number.
If you try and edit an existing variable, the variable in game doesn't change.

This is very annoying and time consuming (especially when trying to fine tune something)
Please get this fixed.

**Comment by MOARdV** [comment]
Fixed in the dev build I just released.

**Comment by DeputyLOL** [comment]
thank you
