### ISSUE TITLE
InvalidCastException: Cannot cast from source type to destination type.

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#383]
I have this endless spaming message:

 [EXC 15:46:07.719] InvalidCastException: Cannot cast from source type to destination type.
	JSI.JSIInternalBackgroundNoise.OnUpdate ()
	InternalProp.OnUpdate ()
	InternalModel.OnUpdate ()
	Part.InternalOnUpdate ()
	Part.Update ()

RPM 0.23

**Comment by MOARdV** [comment]
C# doesn't do a couple of things regarding casting that I thought it would.  Fixed in the brand-new dev build https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

**Comment by Alexustas** [comment]
Fixed! 
(0.23.1-dev)
