### ISSUE TITLE
no sound on JSINumericInput switcher

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#384]
I have re-maded 4-way switcher for Altitude warning setup using new JSINumericInput module , props work fine, but no sound while i'm clicking on it

MODULE
{
    name = JSINumericInput
    perPodPersistenceName = ALCORALTWARN
    defaultValue = 0
    stepSize = 1
    minValue = 0
    maxValue = 3
    reverse = false
    switchSound = ASET/ASET_Props/Sounds/click-027
    switchSoundVolume = 1
    loopInput = false

    USERINPUTSET
    {
        switchTransform = ColliderPlus
        increment = 1
    }
	USERINPUTSET
    {
        switchTransform = ColliderMinus
        increment = -1
    }
}

**Comment by MOARdV** [comment]
I will look at that - sound worked for me yesterday :(

**Comment by MOARdV** [comment]
Oh - I see the problem.  Sound goes in the USERINPUTSET (so you can have different sound for each collider / button).

**Comment by MOARdV** [comment]
I will fix the wiki - it is incorrect.

**Comment by Alexustas** [comment]
Thank you, it's works!
