### ISSUE TITLE
HUD Ladder keeps box shape when rolling leading to empty corners.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#386]
Hard to describe. Easy to show. My first solution was to have the overlay cover the corners but then the ladder was too small. Is there some way the ladder can 'fill' the corners in?

![2015-09-29_00003](https://cloud.githubusercontent.com/assets/12616126/10167612/2c67cede-66c1-11e5-8a5e-7adb1a911321.jpg)
![2015-09-29_00004](https://cloud.githubusercontent.com/assets/12616126/10167611/2c652440-66c1-11e5-8efd-e983fbae013b.jpg)

(you can see where the overlay ends because of the white lines)

Also, is there some way to have an arrow at the top that rotates with the ladder but isn't affected by pitch? (for bank indication)

**Comment by MOARdV** [comment]
I can probably add an option to add an overlay texture to the ladder that rolls with it that is not affected by pitch.  I will have to look at the ladder code a little more closely - it wasn't originally intended for in-cockpit displays, so it's never accounted for an opaque background.  I'll see if there's a way to let it work with a wider/taller texture region so it can fill the space even on a roll.

**Comment by DeputyLOL** [comment]
Thanks.

**Comment by MOARdV** [comment]
I think this will actually be easy - I will try to have a dev build out later today (my time) with the changes.

**Comment by MOARdV** [comment]
Rereading the documentation, it looks like the behavior you're asking for is how it is supposed to work, but I messed it up some time in the past.  You will need to make sure `horizonTextureSize` in your config is at least 1.42x larger than `horizonSize` (or just round it to 1.5x), and try it with the dev build on DropBox: https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

You may need to adjust the texture to have larger margins on the sides.

**Comment by DeputyLOL** [comment]
Ok, the ladder is now really zoomed in. I'll try and work round it, thanks for the fix!

**Comment by DeputyLOL** [comment]
hmmm..... nothing I'm doing seems to change the ladder. Its still really zoomed in.
I changed the texture and I edited the config. Nothing is changing :(

**Comment by MOARdV** [comment]
There are two parameters to adjust - `horizonSize`, which is how big the window for the HUD should be, and `horizonTextureSize`, which adjusts how big the horizon's texture should be underneath the window.  If you have `horizonSize` at, say, '320, 320', you'll want `horizonTextureSize` at '480, 480'.  Ideally in this example, the texture you're using for the horizon / ladder would be 512 pixels wide.  When you look at your ladder texture in an editor, you'll want the width of the ladder to be the same as it was previously, but you may need to make the texture wider so you can fill the sides with solid blue / brown-orange.  In other words, if your texture was 512 pixels wide, you might need to make it 768 pixels wide (without stretching the ladder - it stays in the center, the same size as before) so you can expand the sky/ground fill area.

**Comment by DeputyLOL** [comment]
I tried that. No matter what I change the ladder remains zoomed in.
I'll try again using the exact numbers you just gave there but I don't think it will work.

**Comment by MOARdV** [comment]
Can you put that texture somewhere?  I can try it here, too, to see if I can sort it out.

**Comment by DeputyLOL** [comment]
Here:
			horizonSize = 315,335
			horizonTextureSize = 480,480
The ladder doesn't change when I change either the config or the texture.

![adi_ladder](https://cloud.githubusercontent.com/assets/12616126/10178583/87f076d4-66f8-11e5-93d9-5b5fdd350fc1.png)

**Comment by DeputyLOL** [comment]
This is what it looks like in game:
![2015-09-29_00006](https://cloud.githubusercontent.com/assets/12616126/10178615/bd0a1686-66f8-11e5-94c7-2e40b8e7c635.jpg)

**Comment by MOARdV** [comment]
Okay, yeah, my math was off, and the ladder texture I had just happened to work out.  I'll get another fix out today.

**Comment by MOARdV** [comment]
Grab the dev build (same place as above) - however, change horizonTextureSize to 768, 768.  If the ladder in the middle is too small at that size, you can reduce that number.

**Comment by DeputyLOL** [comment]
thank you

**Comment by DeputyLOL** [comment]
Works now
