### ISSUE TITLE
Toggle all or individual screens on or off

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#391]
I know that all the screens go blank If the ship is out of power, but is there a way to turn them on or off by variable? I don't particularly mind if I can't turn them on or off individually but being able to turn them all off by one switch would be helpful.

I have a battery switch. The point of that switch is, to turn everything off in the cockpit when it is off. When it is on, it allows you to powerup other systems.

**Comment by MOARdV** [comment]
The ASET props use a variable animator to control the power off behavior.  You could make your own CUSTOM variable that does an OR with CUSTOM_ALCOR_POWEROFF and your own persistent variable (PERSISTENT_MONITOROFF), and use that as a replacement for the existing behavior.

**Comment by DeputyLOL** [comment]
I am using one of the ASET props as a monitor. I just changed the variable from CUSTOM_ALCOR_POWEROFF to CUSTOM_SYSTEM3
Its a switch that's meant to switch on the screens but not function if the battery is off or charge is depleted. When I tested it nothing happened.

**Comment by DeputyLOL** [comment]
MODULE 
	{
		name = JSIVariableAnimator
		refreshRate = 10
		
		VARIABLESET
		{
			animationName = MFD60x30PowerOffAnim
			variableName = CUSTOM_SYSTEM3
			scale = 1, 0
		}
		VARIABLESET
		{
			coloredObject = MFD60x30Screen
			passiveColor = 50,50,50,255
			activeColor = 255,255,255,255
			variableName = CUSTOM_SYSTEM3
			scale = 0,1
			threshold = 0.5,1.1
		}
	}

**Comment by MOARdV** [comment]
How is CUSTOM_SYSTEM3 defined?

**Comment by DeputyLOL** [comment]
RPM_CUSTOM_VARIABLE
{
  name = SYSTEM3
  operator = AND
  SOURCE_VARIABLE
  {
    name = PERSISTENT_SYSTEM3TOGGLE
    range = 0.5, 1.1
  }
  SOURCE_VARIABLE
  {
    name = CUSTOM_CHARGEFAIL
    range = -0.5, 0.1
  }
  SOURCE_VARIABLE
  {
    name = CUSTOM_POWERTOGGLE
    range = 0.5, 1.1
  }
}

**Comment by DeputyLOL** [comment]
its either 1 or 0

**Comment by MOARdV** [comment]
One thing I know is that the ALCOR custom variable is 0 when the display is on, and 1 when it's off.  I have not used the power off feature on those props, so you might check with alexustas for recommendations on how to implement that capability.

**Comment by DeputyLOL** [comment]
mine is the same...

**Comment by Alexustas** [comment]
CUSTOM_ALCOR_POWEROFF=1 if no power

**Comment by DeputyLOL** [comment]
how come all the screens are on when there is power then?

**Comment by Alexustas** [comment]
correction:

CUSTOM_ALCOR_POWEROFF=1 if no power _OR_ if High G-Force.


MFD screen itself become black if no power becouse "needsElectricCharge -- Boolean, defaults to true. "

this module turn off monitor's buttons backlight:
		VARIABLESET
		{
			animationName = MFD60x30PowerOffAnim
			variableName = CUSTOM_ALCOR_POWEROFF
			scale = 1, 0
		}
scale from 1 to 0 because animation was maded from OFF to ON and i need OFF then CUSTOM_ALCOR_POWEROFF=1


This module make screen dark (50,50,50,255) if you have power but experience hi G:

VARIABLESET
		{
			coloredObject = MFD60x30Screen
			passiveColor = 50,50,50,255
			activeColor = 255,255,255,255
			variableName = CUSTOM_ALCOR_POWEROFF
			scale = 1,0
			threshold = 0.1,1.1
		}

Oh, sorry for my terrible English...

I think you just must to invert "scale" to 0,1

**Comment by DeputyLOL** [comment]
I already have, that's why I'm really confused

**Comment by Alexustas** [comment]
in my setup screens become dark but not totally black, you need to change "passiveColor " to "0,0,0,255"

**Comment by DeputyLOL** [comment]
ok thanks

**Comment by Alexustas** [comment]
quick test
https://youtu.be/EngCh4WjnAY

**Comment by DeputyLOL** [comment]
:/ I don't know what's going on with mine.
I'm going to keep trying

**Comment by Alexustas** [comment]
variable "CUSTOM_SYSTEM3" working as it should?

**Comment by DeputyLOL** [comment]
yes. 1 when on. 0 when off. Even if they are the wrong way round the screens should be off at some point.
The screens are just staying on.
Does emptycolour affect it at all?

**Comment by DeputyLOL** [comment]
btw, do you take prop requests?

**Comment by Alexustas** [comment]
i have "emptyColor = 0,0,0,255"

**Comment by DeputyLOL** [comment]
I just tried that. didn't work

**Comment by DeputyLOL** [comment]
would the name of the prop affect it?

**Comment by Alexustas** [comment]
this setup turn on/off my screen by pressing "backLight" button:

          VARIABLESET
          {
                    coloredObject = MFD60x30Screen
                    passiveColor = 0,0,0,255
                    activeColor = 255,255,255,255
                    variableName = PERSISTENT_BackLight
                    scale = 0,1
                    threshold = 0.1,1.1
           }

**Comment by Alexustas** [comment]
no, i don't think the prop's name affect it

**Comment by DeputyLOL** [comment]
I'm going to double check my system3 variable is working. If it is, then I'm going to put in a persistent and see what it does.

**Comment by Alexustas** [comment]
request? - Yes of course :)

**Comment by Alexustas** [comment]
just to be sure, do you have latest ASET_Props version?

**Comment by DeputyLOL** [comment]
I love the rotary switch, is it possible to have one with 3 points instead of 2 or 4.

**Comment by DeputyLOL** [comment]
... ummm no.

**Comment by Alexustas** [comment]
ALCOR MFD 60x30
https://www.dropbox.com/s/ia6ke0i372d3clq/ALCORMFD60x30.zip?dl=0

**Comment by Alexustas** [comment]
3-point rotary switch
https://www.dropbox.com/s/w4f0osvc0w6860k/MultiSwitcher_3pos.zip?dl=0

i did'nt test it but it must to work :)

**Comment by DeputyLOL** [comment]
does this alright to you?
PROP
{
	name = PFDMFD60x30
	MODULE
	{
		name = RasterPropMonitor
		screenTransform = MFD60x30Screen 									// Name of transform for the screen surface.
		fontTransform = AdvancedCockpit/MFD/Fonts/mainfont    // Name of transform containing the font texture OR a full texture URL, either should work.
		textureLayerID = _Emissive            									// Name of texture layer to work with on the screen surface.
		screenWidth = 60                      									// Screen width in letters.
		screenHeight = 32                     									// Screen height in lines.
		screenPixelWidth = 640               									// Width of the generated screen texture in pixels.
		screenPixelHeight = 640               									// Height of the generated screen texture in pixels.
		fontLetterWidth = 16                  									// Width of a font character.
		fontLetterHeight = 32                 									// Height of a font character.
		cameraAspect = 0.9375
		globalButtons = button_UP,button_DOWN,button_ZoomIn,button_ZoomOut,button_HOME,button_RIGHT,button_LEFT,button_PREV,button_NEXT
		buttonClickSound = Squad/Sounds/sound_click_tick
		buttonClickVolume = 0.6
		emptyColor = 0,0,0,255
		
		fontDefinition = AdvancedCockpit/MFD/Fonts/fontDefinition.txt
		
		extraFont = AdvancedCockpit/MFD/Fonts/extraFont1
		extraFont = AdvancedCockpit/MFD/Fonts/InvertedMainFont
		extraFont = AdvancedCockpit/MFD/Fonts/InvertedExtraFont
		extraFont = AdvancedCockpit/MFD/Fonts/Symbols01
		extraFont = JSI/RasterPropMonitor/Library/Fonts/extraFont1
		extraFont = JSI/RasterPropMonitor/Library/Fonts/hudfont
		
		refreshDrawRate = 1
		refreshTextRate = 2
		refreshDataRate = 2

**Comment by Alexustas** [comment]
You have:

     screenPixelWidth = 640 // Width of the generated screen texture in pixels.
     screenPixelHeight = 640 // Height of the generated screen texture in pixels.

I have:

      		screenPixelWidth = 960
      		screenPixelHeight = 1024
becouse 

     60 symbols X 16 pixels per symbol = 960
    32 symbols X 32 pixels per symbol = 1024


but that should not matter to Your problem

**Comment by DeputyLOL** [comment]
yeah, I changed it because it messed up my displays. I'm testing your multi switch now.

**Comment by Alexustas** [comment]
and one more quick test
https://youtu.be/l-WO76BSWYg

**Comment by DeputyLOL** [comment]
your switch seems to work nicely, thanks so much

**Comment by Alexustas** [comment]
btw, seems like you build realistic 'glass' cockpit in Boeing style.
 May be you need to use more authentic monitor model?
![img_9815n](https://cloud.githubusercontent.com/assets/6713671/10217750/a06b70a4-6853-11e5-9853-69ba83c944af.jpg)

and a separate EFIS Control Panels for this monitors?
![efis1](https://cloud.githubusercontent.com/assets/6713671/10217800/f4298fa0-6853-11e5-951b-e4bb5311f753.jpg)

**Comment by DeputyLOL** [comment]
YES! YES! YES! PLEASE! YES!

**Comment by Alexustas** [comment]
I knew it :-)

**Comment by DeputyLOL** [comment]
I've been meaning to ask, is it possible to have a turn dial for inputting numbers into the autopilot.
Basically, you click and hold one side and it rotates in that direction will increasing the numerical input.
You click and hold the other side and it rotates the other direction and decreases the numerical input.

Maybe even a button in the middle that you can press to 'select' the number you've got.

**Comment by Alexustas** [comment]
please, post your request in my "Avionics props" thread. monitor model is quite simple but i need to know more details about EFIS Control Panel, which buttons and switcher you need and how they must to work

**Comment by Alexustas** [comment]
need MCP ?

**Comment by DeputyLOL** [comment]
yes please, I want to be able to swap between the Nav Utilities HSI and a rotation map.

**Comment by Alexustas** [comment]
Ok, I look forward to your detailed request in the forum topic

**Comment by DeputyLOL** [comment]
I cant post on forums with the internet I have.....

**Comment by Alexustas** [comment]
@DeputyLOL https://github.com/Alexustas/Props-requests/issues

**Comment by DeputyLOL** [comment]
thank you
