### ISSUE TITLE
FARPM_STALL_FRACTION

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#393]
FAR variable "FARPM_STALL_FRACTION" don't work in the new RPM version.

        Error]: RPMVesselComputer: Processing error while processing FARPM_STALL_FRACTION: Input string was not in the correct format

may be it is a FAR bug, not RPM...

FAR version 3.0.15.5.1, RPM - 0.23.1

CUSTOM's config:

        //	STALL
	
        RPM_CUSTOM_VARIABLE
	{
	  name = ASET_HUD_STALLWARNING
	  operator = AND
	  
	  SOURCE_VARIABLE
	  {
		name = FARPM_STALL_FRACTION
		range = 0.01, 1000
	  }
	  
	  SOURCE_VARIABLE
	  {
		name = ISLOADED_FERRAMAEROSPACERESEARCH
		range = 0.1, 1.1
	  }
	  
	  SOURCE_VARIABLE
	  {
		name = PERIOD_2HZ 
		range = 0.1, 1.1
	  }
	  
	  SOURCE_VARIABLE
	  {
		name = PERSISTENT_WARNINGS_ON
		range = 0.1, 1.1
	  }
	  
	}

**Comment by MOARdV** [comment]
I'll suspect me first.  I made a lot of changes related to plugin handling.

**Comment by MOARdV** [comment]
Yes, I broke it.  Fix is in the dev build on DropBox: https://www.dropbox.com/s/apttlrrfarqktvo/RasterPropMonitor-dev.0.23.1.zip?dl=0

**Comment by Alexustas** [comment]
Fixed!
Thank you!
