### ISSUE TITLE
Configurable state machine variables

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#396]
Currently variable only stay on as long as their thresholds are met.

What I'm asking about is basically a variable that stays on until something else tells it to stop being on.

I need it for an altitude alert. 
How its supposed to work:
1) You select an altitude and a marker appears on the altimeter.
2) When you get near a chime sounds to notify you. 
(Variable sets to 'ON' when you reach altitude)
3) If you stay within 200m of the selected altitude nothing will happen.
4) If you deviate 200 m from the selected altitude a warning will sound and a light will flash.
5) If you change the selected altitude and you are more than 200m from it, no alarm will sound. 
(Variable sets to 'OFF' when you change altitude)

How it currently works:
1) You select an altitude and a marker appears on the altimeter.
2) The alert sounds immediately as you aren't near you selected altitude.
2) When you get near a chime sounds to notify you and the alert turns off. 
3) Same
4) Same
5) If you change the selected altitude and you are more than 200m from it, alarm will sound. 

Any ideas?

**Comment by MOARdV** [comment]
What you're looking for is a state machine, where you create rules for the different states, and you have events when you transition into a state (or out of a state).  I am fairly certain I can work up something that can be configured in a config file.  It'll be a bit of work, so it's not going to be this week :)

**Comment by DeputyLOL** [comment]
ok thanks for letting me know

**Comment by MOARdV** [comment]
This is another feature I'm going to drop for the time being.  KSP 1.1 has a number of things that RPM needs to handle better, and there are still stock features that are not handled by RPM (and several incomplete RPM features still).
