### ISSUE TITLE
hardcoded ElectricCharge change to resourceName

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#397]
some mods change how stock power system works, and use resources other than ElectricCharge, causing RPM to not work with them, perhaps add a resourceName field to specify which to use?:)

searched through the source and only a couple of places have ElectricCharge hardcoded

**Comment by MOARdV** [comment]
There is ElectricCharge in a few places, and there's SYSR_ELECTRICCHARGE.  I'll see what I can do.

**Comment by MOARdV** [comment]
Most of these are easy to change.  The methods to toggle generators on and off are not really changeable, but I can add additional methods that can take a generic parameter now that I've got the JSIActionGroupSwitch transfer functionality implemented.
