### ISSUE TITLE
Toggle switchable label using a variable or persistent.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#401]
I'm going for a more complex autopilot system and I have limited space, so I need to be able to show multiple numbers on the same screen. 

The screen has a switch (separate prop) that toggles the 'mode' the screen is in.
The screen has a select button that will send the number displayed to its modes output.
The screen will have a + and - button which adds and subtracts from the current number displayed on the screen. (it doesn't adjust the other number, but it can if the screen is in the right mode)

Its kind of difficult to explain. If you do understand then please let me know what you think.

**Comment by MOARdV** [comment]
I think I understand your description, but I don't understand where the switchable label in the issue title is involved.  Do you want to change a label based on a variable?

**Comment by DeputyLOL** [comment]
The ASET digital display uses JSISwitchableVariableLabel for its multi purpose number display
(its a screen that can cycle through a number of different variables.

**Comment by MOARdV** [comment]
Okay.  I get it.  I'll see if I can work it in sometime soon.  I think it will not be too difficult.

**Comment by DeputyLOL** [comment]
thanks.
would it be difficult to implement a 'smooth' option for things like vertical bars, gauges and other things.

**Comment by Alexustas** [comment]
Take a look on my "DigitalIndicator_SASMode" prop. it displays current SAS mode. ie text vary depending on the state of the external variables

**Comment by DeputyLOL** [comment]
So it does, thank you.
But is the 'have one button be able to change two separate persistents' possible?

**Comment by DeputyLOL** [comment]
Also, is it possible to change the font on the digital displays?

**Comment by MOARdV** [comment]
> Also, is it possible to change the font on the digital displays?

Short answer, no.  It's using a KSP object that doesn't provide any font control (font, justification, etc).  That may change when KSP 1.1 drops and we have to deal with the side-effects of Unity 5.

**Comment by DeputyLOL** [comment]
awwww... ok.

**Comment by MOARdV** [comment]
> If you have a gauge or bar that has a range of 0 to 1 and is measuring a 0 to 1 variable. The gauge or bar will snap when the variable changes. Is there some way to config the speed at which the gauge or bar moves between 2 numbers, so that you can have it move across instead of just snapping to its new position

That was added in v0.23.2 - take a look at JSIVariableAnimator's `maxRateChange` parameter.

> But is the 'have one button be able to change two separate persistents' possible?

You might try putting to action group switches using the same collider on a single prop.  I don't know if that will work (meaning, I haven't tried it).

**Comment by MOARdV** [comment]
Is there anything I need to do here?  It looks like alexustas showed how to achieve what you were looking for with the initial post.  The gauge speed setting is in already, and the multi-action action group switch is a separate upcoming feature.

**Comment by DeputyLOL** [comment]
Nope, I think this can be closed!
The "putting two action groups switches using the same collider on a single prop" sort of works.
But the masterVariable config has no effect on it... I think.

**Comment by MOARdV** [comment]
> The "putting two action groups switches using the same collider on a single prop" sort of works.

I'll work that out with Issue #439
