### ISSUE TITLE
Expand on MATH_ MAX and MIN

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#407]
Is it possible to change a variable when a certain value is smaller or bigger than another value.

Kind of like how the MAX and MIN but instead of the highest of both the values, it gives either a 0 or 1.

Example:
(Altitude is 700/Persistent is 1000)
RPM_MATH_VARIABLE
{
   name = TARGETALT
   operator = MIN

   sourceVariable = ALTITUDE
   sourceVariable = PERSISTENT_TARGETALTITUDE
}
The output would be 700.
Could their be a way to return a number corresponding to the lowest number.
So instead of 700 the output would be 0 (as altitude is the first variable on the list)
If the Persistent is smaller, output would be 1.
If there was a 3rd number that was the smaller, output would be 2. 
And so on...

Same for MAX.

**Comment by MOARdV** [comment]
That should be fairly easy.

**Comment by MOARdV** [comment]
MAXINDEX and MININDEX are in v0.23.1 - there should be a release today some time.
