### ISSUE TITLE
Looping Sound for click and hold buttons.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#408]
For buttons that have a click and hold function, could there be two different sounds?

One for if the button is just clicked and one looping for when the button is clicked and held down.

Thanks

**Comment by MOARdV** [comment]
Another fairly easy implementation (unless I did something wrong).

**Comment by MOARdV** [comment]
Also in v0.23.1 (loopingSound and loopingSoundVolume in JSIActionGroupSwitch).

**Comment by DeputyLOL** [comment]
thank you
