### ISSUE TITLE
real fuels vs engine ignitor

### ISSUE THREAD

**Issue by anxcon** [Mihara/RasterPropMonitor#414]
RPM already interfaces with engine igniter which hasn't update in a year
RF has igniter functionality and other things, perhaps some variables needed :)

**Comment by MOARdV** [comment]
The Engine Ignitor interface is/was part of the Engine Ignitor plugin, not RPM.  RPM provided a page on the MFD for it, but that's as far as we've been involved on our side.  NathanKell PM'd me a while back about RF support, and I told him the same thing.  I'll be happy to support someone working on an RF page, but I don't know that I have time to develop it myself.  Likewise, if I know what variables in RF need exposed, and what functions can be called, I can add RF support that way (I have never used the mod, so I don't know what's needed).

**Comment by anxcon** [comment]
ah it goes on their end :D okie
