### ISSUE TITLE
JSIMechJeb Set/Get Launch Inclination

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#415]
Altitude is done, but inclination isn't.

**Comment by IntegerMan** [comment]
Fantastic. Will this be part of the mech Jeb UI or something different?

**Comment by MOARdV** [comment]
These are part of the plugin system - it's possible to make props that set / get numbers from plugins.  I would be possible to add it to the MJ menu in RasterPropMonitor, but it'd be tedious to adjust the inclination due to the limitations of the menu inputs.

**Comment by Alexustas** [comment]
you can use one of this dials

https://youtu.be/TJrDsPRSwzE

DL: https://www.dropbox.com/s/ufg4p5x9naq136w/NumInputDial_NoButton.zip?dl=0

**Comment by Alexustas** [comment]
or this

https://youtu.be/jdfLejKZ_Ao

Dial with "SELECT" button 
DL: https://www.dropbox.com/s/jfz0bhymt2d8bji/NumInputDial.zip?dl=0
