### ISSUE TITLE
View Selection Button

### ISSUE THREAD

**Issue by IntegerMan** [Mihara/RasterPropMonitor#416]
With a large number of views, you eventually run out of top / bottom buttons to use in allowing view selection. Additionally, people sometimes want to customize which views show up on which MFD button on an individual MFD basis. (E.G. for a flight based MFD I might want the Navball on bottom left, the plane's HUD on bottom MFD 2, orbit on bottom MFD 3, etc. whereas on another MFD I might want Navigation, Resources, Log, Vessel View, etc.)

To accommodate this customization and allow the inclusion of new MFD types, I suggest you follow the A-10 C's method of allowing view customization. In that model if you press and hold a MFD button, it brings up a view selection MFD where you can keep the currently selected view or select any other available view option, including no view. After selecting the new view, that view is then associated with that MFD button and its label changes. (E.G. If I press and hold on the Engine Igniter MFD a menu screen appears where I can select NAV 2 or some other new view type).

Take a look at how this is implemented in DCS World's A-10 C add-on for more specifics. This is a minor feature, but it'd make the MFDs feel more like an operating system while paving the way for a larger number of supported MFD views.

**Comment by MOARdV** [comment]
This will require a major overhaul of the MFD code to support - or, more realistically, a new MFD module.  I'll need to do some more planning before I can commit to it (particularly with respect to existing monitor handler capabilities), but it sounds to me like a good way to improve MFD flexibility.

**Comment by MOARdV** [comment]
Rolling this feature into #478.  The code to support this really warrants a new monitor class.
