### ISSUE TITLE
MFD Number Inputs

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#419]
First, I realise that this is going to take a lot of work and I know that you are busy. I just want to put this idea put there but if you don't have time, then I understand

Having the ability to punch in numbers using a keypad would be a major and useful feature for RPM.
This is the part where I start making lists because I cant explain it in full sentences. :)
(Input = Where you are typing the number in)      (Output = The number you have selected)
- You would have some type of module for the keypad, input and output. 
- The output would be a persistent.
- Multiple inputs can use the same keypad.
- The input can be displayed on a screen. (You can see what your number is as you are inputting it)
- The input can have a maximum and minimum value. (Between 500-2500)
- The input can be limited to a number of characters. (Max is 4 = 2000)
- The input should have an 'empty' character. ([....] -> [1...] -> [12..] -> [123.] -> [1234])
- You can select between different inputs on a screen (menu system, up/down buttons, switch...)
- The module would require at least 12 'buttons' (0,1,2,3,4,5,6,7,8,9,ENTER,BACK/DELETE)
- Enter Button 'Transfers' the input to an output persistent and clears the input
- Back or delete button clear the current input (for when you make a mistake)
- (Maybe use buttons on an MFD or separate buttons(?) as a keypad) not sure

That is as long as my memory lasted.
I am trying to build an FMC that you can use to input Auto Pilot functions and flight data that wouldn't be done on the main console.

![image](https://cloud.githubusercontent.com/assets/12616126/10822341/ae45cc5e-7e4e-11e5-868d-5de77cf02716.png)

Please let me know what you think, thank you.

**Comment by IntegerMan** [comment]
I'm curious about this screenshot. What's this from?

**Comment by DeputyLOL** [comment]
google images....

**Comment by MOARdV** [comment]
That's a function I've wanted for a while. It would definitely make some numeric inputs much, much easier.  It requires a prop that can support it (although alexustas already has a kOS terminal that could work with it, but a 12-key numeric input prop would be nice).  I'd say the 'Enter' key is optional - that functionality already exists in the JSIActionGroup 'transfer' mode.  I'd also add a 'clear' function that could reset the entire input buffer.

Actually, I may be able to use the ASET BtnB props for numeric input keys for something like this.  There are some infrastructure changes I will have to do to support it, to support strings as persistent variables.

**Comment by DeputyLOL** [comment]
great to hear. Thank you.

**Comment by IntegerMan** [comment]
Thanks for your help. I used reverse image search and determined it came
from Microsoft Flight Simulator, if you had any more interest in the
screenshot you came across.

**Comment by MOARdV** [comment]
This is partially functional with RPM (alexustas has demonstrated it), and it is fully functional in MOARdV's Avionics Systems.
