### ISSUE TITLE
New signed acceleration variable

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#420]
> I think I'm referring to EFFECTIVEACCEL. The problem I have with it is that it is always positive. Could we have a variable that is + when accelerating and - when decelerating?

Per DeputyLOL request.

One issue I see: acceleration is a vector in 3-space, and to get a signed value, it needs to be measured relative to an axis.  Presumably, if we want a signed value, that means we want the value relative to the forward vector, so we'd take a dot product of the forward unit vector and the acceleration vector to get a result.  However, that would mean the new acceleration variable would go to zero when the acceleration is exactly perpendicular to the nose of the vessel (such as horizontal flight when the vessel is accelerating straight down).

**Comment by DeputyLOL** [comment]
Would this be the acceleration of ground speed or EAspeed?

**Comment by MOARdV** [comment]
I can generate both, along with orbital speed (for completeness).

**Comment by MOARdV** [comment]
> I can generate both, along with orbital speed (for completeness).

Actually, I have to take that back.  I can provide ground acceleration (acceleration relative to surface prograde / forward), but not EAspeed.  Acceleration relative to EA speed would require me to compute that speed every update so I can track the difference since the previous update.  That's fairly costly to do for a variable that's fairly limited (it's only relevant in aerodynamic flight).  If the acceleration value were available elsewhere (like in FAR), I could provide access, but I don't want to be recomputing that value in RPM every update.

**Comment by DeputyLOL** [comment]
Wouldn't prograde acceleration be it then? Does it return negative when you are slowing down?

**Comment by MOARdV** [comment]
They're all signed.  Firing the rockets while retrograde will produce a negative ACCELPROGRADE.  Same with the other cases.

**Comment by DeputyLOL** [comment]
ok good, ill use that then.
thank you

**Comment by DeputyLOL** [comment]
Do you think you could make a meterpersecond to knotspersecond math function?

**Comment by MOARdV** [comment]
> Do you think you could make a meterpersecond to knotspersecond math function?
> EDIT: meterspersecondpersecond to knotspersecond! (m/s/s to kts/s)

Doesn't the current m/s to knots conversion do just this?  m/s^2 and kts/s have a common denominator, so I would think the current m/s to knots conversion would do the trick.

**Comment by DeputyLOL** [comment]
...   yes it would.
