### ISSUE TITLE
Props occasionally fail to appear

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#423]
I don't know if this is RPM or the prop its self but every now and then, the heading display doesn't appear on my MCP. I would have thought it was the prop but all the others still appear and they are almost the same.
![2015-11-03_00001](https://cloud.githubusercontent.com/assets/12616126/10924075/54ad2bba-827c-11e5-9c24-90250068844a.jpg)
When I look it up in the log, all I can find is this:

[LOG 21:44:31.247] [ModuleManager] Parent null for AdvancedCockpit/Instrumentation/EFIS_MCP_Display/Heading/MCP_HeadingDisp
...
[LOG 21:46:30.582] Cannot find InternalProp 'MCP_HeadingDisp'

The prop is where it is supposed to be but RPM doesn't recognise it for some reason.

**Comment by Alexustas** [comment]
Oh, it's my fault. sorry!
You need to fix the file name "MCP_HeadingDisp .cfg". You need to delete 'space' after "Disp"

**Comment by DeputyLOL** [comment]
ok, ill try that thanks.

**Comment by DeputyLOL** [comment]
i think its fixed, thank you
