### ISSUE TITLE
New Mk1 Cockpit IVA

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#428]
The new IVA model requires a new RPM IVA...

**Comment by DeputyLOL** [comment]
Whats the criteria? I can quickly put one together if you want

**Comment by MOARdV** [comment]
The only requirement I have is that is uses the props that come in the basic RPM package (the repurposed Squad IVA props + the MFDs alexustas made).  It can't have external dependencies, such as ASET props / avionics.  It'd be nice to have one or two MFDs, but from the 5 minutes I spent in that cockpit, it's really cramped, so there may not be room for more than one.

**Comment by DeputyLOL** [comment]
ok, I'm having problems with unity and my computer hard crashing.
I found the issue. When I try and open the mk1cockpit, task manager shows that unity starts using more and more memory until it get to 100% at which point my computer is a brick, the off button wouldn't even work.
After removing the power cable and battery then restarting the computer unity won't work with part tools at all now. So I'm reinstalling unity!

**Comment by DeputyLOL** [comment]
You may want to put this on hold, the new cockpit doesn't like unity. Then again it might just be my computer, but its been restarted and still doesn't work.
When I tried it on unity 5 (which I had been using all the time) It crashed my computer.
When I tried it on unity 4.22, it crashed unity. So there is a slight improvement.

Both versions still opened other cockpits successfully.

**Comment by DeputyLOL** [comment]
And just talking to Alexustas, he couldn't open it either...

**Comment by MOARdV** [comment]
Same problem for me.  It looks like we need to wait for Squad to release new PartTools, I am guessing.

**Comment by DeputyLOL** [comment]
yeah, suppose so.

**Comment by DeputyLOL** [comment]
Do you know of anything that could cause all IVAs in game to be inaccessible?
Meaning that there is no kerbal camera and pressing C doesn't switch to IVA mode.
I'm reinstalling ksp now.

**Comment by MOARdV** [comment]
I haven't heard of anything like that.  Look in KSP log file to see if it provides a clue.

**Comment by DeputyLOL** [comment]
This:
[LOG 13:26:15.396] Cannot find InternalPart 'landerCabinSmallInternalRPM'
[ERR 13:26:15.398] Cannot add an InternalPart: Cannot find internal of name 'landerCabinSmallInternalRPM'

A different version of this appears for all the command modules in the game, stock or not.
Even the ones without RPM such as the passenger cabins don't work.

**Comment by MOARdV** [comment]
It sounds like something is failing during load.  Are your Spaces directories still intact (GameData/Squad/Spaces)?

**Comment by DeputyLOL** [comment]
well. not now because I uninstalled ksp. I'm reinstalling it now.

**Comment by DeputyLOL** [comment]
also found this:
[EXC 13:20:28.598] NullReferenceException: Object reference not set to an instance of an object
	CameraManager.SetCameraIVA ()
	CameraManager.NextCameraMode ()
	CameraManager.Update ()
[EXC 13:20:28.906] NullReferenceException: Object reference not set to an instance of an object
	CameraManager.SetCameraIVA ()
	CameraManager.NextCameraMode ()
	CameraManager.Update ()
[EXC 13:20:29.087] NullReferenceException: Object reference not set to an instance of an object
	CameraManager.SetCameraIVA ()
	CameraManager.NextCameraMode ()
	CameraManager.Update ()
[EXC 13:20:29.357] NullReferenceException: Object reference not set to an instance of an object
	CameraManager.SetCameraIVA ()
	CameraManager.NextCameraMode ()
	CameraManager.Update ()

**Comment by DeputyLOL** [comment]
and this:
[WRN 13:18:36.799] [Part]: PartModule TransferDialogSpawner at mk3Cockpit.Advanced, index 12: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 13:18:36.804] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 13:18:36.807] PartModule is null.
[WRN 13:18:36.871] [Part]: PartModule TransferDialogSpawner at mk3CrewCabin, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 13:18:36.876] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 13:18:36.880] PartModule is null.
[WRN 13:18:36.930] [Part]: PartModule TransferDialogSpawner at mk3CrewCabin, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 13:18:36.935] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 13:18:36.938] PartModule is null.
[WRN 13:18:36.988] [Part]: PartModule TransferDialogSpawner at mk3CrewCabin, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 13:18:36.992] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 13:18:36.996] PartModule is null.
[WRN 13:18:38.128] [Part]: PartModule TransferDialogSpawner at mk3CrewCabin, index 8: index exceeds module count as defined in cfg.
Looking for TransferDialogSpawner in other indices...
[WRN 13:18:38.133] ...no TransferDialogSpawner module found on part definition. Skipping...
[WRN 13:18:38.136] PartModule is null.

**Comment by MOARdV** [comment]
Actually, I get the TransferDialogSpawner message as well, but I'm able to get to IVA.  There's got to be something during loading.  Look for Config(INTERNAL) to see what messages there are, and check what the messages there look like.

**Comment by DeputyLOL** [comment]
can you see anything wrong with this?
Cockpit config:
// --- general parameters ---
name = mk3Cockpit_Advanced
module = Part
author = k.yeon
[...]
// --- internal setup ---
CrewCapacity = 4

	INTERNAL
	{
		name = kossakintRPM
  		offset = 0 , 0.6 , -3
	}

**Comment by DeputyLOL** [comment]
Then this:
 @PART[mk3Cockpit_Advanced]:NEEDS[RasterPropMonitor]
 {
     @INTERNAL
     {
         @name = kossakintRPM
     }
     MODULE
     {
         name = RasterPropMonitorComputer
	 triggeredEvents = autobrakespoiler|autobrake|sasdisconnect|sason|sasoff|aldisconnect|alon|aloff|ahdisconnect|ahon|ahoff	 
     }
 }

**Comment by DeputyLOL** [comment]
INTERNAL
{
	name = kossakintRPM
	MODEL
	{
		model = AdvancedCockpit/Cockpit/Spaces/kossak/model
		texture = ksp_l_cupola_internal_diff , Squad/Spaces/cupolaInternal/ksp_l_cupola_internal_diff
		texture = ksp_l_cupola_internal_normal_NRM , Squad/Spaces/cupolaInternal/ksp_l_cupola_internal_normal
		texture = model000 , Squad/Parts/Command/cupola/ksp_l_cupola_diff
		texture = model001 , Squad/Spaces/crewCabinInternals/model001
		texture = model001NRM , Squad/Parts/Command/cupola/ksp_l_cupola_normal
		texture = model002 , Squad/Spaces/crewCabinInternals/model002
		texture = model005 , Squad/Spaces/crewCabinInternals/model005
	}

**Comment by MOARdV** [comment]
I don't see anything wrong with the configs by themselves.  I think the @INTERNAL part of the MM config is redundant if kossakINTRPM is already in the main part config, but that shouldn't be affecting anything.

**Comment by DeputyLOL** [comment]
I think I fixed it.
Apparently the game doesn't lie you leaving unfinished IVAs anywhere in the gamedata folder.
It removes the ability to IVA regardless of if the IVA is used in that ship, and even if its not used at all.

**Comment by DeputyLOL** [comment]
I found a the root cause! Do you know what this means?
[EXC 16:55:36.625] NullReferenceException: Object reference not set to an instance of an object
	PartLoader.ReplaceTextures (UnityEngine.GameObject model, System.Collections.Generic.List`1 textureNames, System.Collections.Generic.List`1 newTextures)
	PartLoader.CompileModel (.UrlConfig cfg, .ConfigNode partCfg, Single scaleFactor, .AvailablePart partInfo)
	PartLoader.LoadInternalSpace (.UrlConfig urlConf)
	PartLoader+.MoveNext ()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	:MoveNext()

**Comment by DeputyLOL** [comment]
When i reload the database, it gets this error and then stops.

**Comment by MOARdV** [comment]
> When i reload the database, it gets this error and then stops.

I think that error means a texture it is looking for is missing (either the name of the texture you are trying to replace, or the name of the texture you want to use for replacement).  You do have textures in the same directory as the model that have the same names as the textures you want to replace, right?

**Comment by DeputyLOL** [comment]
yes. I deleted the MODEL{ } section and my cockpit now works in IVA.... with out textures.

**Comment by MOARdV** [comment]
It looks like there's something going on with the texture replacement.  That feature can be tricky.

**Comment by MOARdV** [comment]
DeputyLOL has supplied a new IVA for the Mk1.  (Yay!)
