### ISSUE TITLE
IAS variable.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#429]
We currently use EAS (Equivalent Air-speed) for the airspeed variable.
This is rarely used in real life except for high performance aircraft.

If possible could we have IAS (Indicated Air-speed)? For the less high performance aircraft...
I'm not sure what the equation is but FAR uses it.

I also want to add that FAR EAS in knots and RPM EAS in knots are different (something different about the conversion equation maybe as it gets worse the higher the speed is.

**Comment by MOARdV** [comment]
I will have to find a way to determine IAS.  As for EAS, I can update RPM to use the FAR EAS when available - the RPM EAS computation predates several aerodynamics changes in KSP, so I am not surprised that it's skewed a bit from what FAR computes.

**Comment by DeputyLOL** [comment]
Fair enough. FAR has IAS, so you might be able to take it from that when its available.

(also, I'm on limited wifi so I cant access steam. Has there been an update for KSP?)

**Comment by MOARdV** [comment]
KSP 1.0.5 released yesterday afternoon CST.

**Comment by MOARdV** [comment]
IAS is easy to compute, and I updated EAS using FAR's equations, since they're under the same license as RPM, so both will be updated today.

**Comment by DeputyLOL** [comment]
Thank you...
did the update release anything game changing?

**Comment by DeputyLOL** [comment]
I just checked the KSP forum and it says new engines for space planes!

**Comment by DeputyLOL** [comment]
and according to scott manley, they have thrust reversers...

**Comment by DeputyLOL** [comment]
works great.
Don't forget to add it to the wiki.
