### ISSUE TITLE
More Trim Control?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#434]
Would it be possible to have way of controlling trim through switches or dials in IVA?

Or at least have a way to reset the trim (ALT+X) with a button, or disable the ability to adjust trim while in IVA?

If not easily possible then that's ok.
Sorry for so many requests and issues...

**Comment by MOARdV** [comment]
With the trim reset - do you want three reset options (one for each axis), or a "reset all", or both?  I think I can also add numeric input support, so you can, say, set "pitch trim = +25%", or something like that.

**Comment by DeputyLOL** [comment]
Both would be smashing good sir!
Numeric input support would also be a nice bonus.

**Comment by MOARdV** [comment]
Okay, this will be a little more involved than I initially expected (although I should have realized it would be).  The early experiment almost worked - I could neutralize the trim, but it snapped back almost immediately.

I think, I have to subscribe an object to the OnFlyByWire callback chain to control flight control state (the trim position, specifically).  That will require a little more thought to decide how best to interact between the methods that are called through RPM and the controller object.  On the other hand, if I can get that to work, RPM would also have the ability to control the craft more directly...

**Comment by DeputyLOL** [comment]
imagine that. using a keyboard... in actual KSP to fly your rocket!
Wow that would be difficult to fly....

**Comment by MOARdV** [comment]
Okay, the callback wasn't needed.  I only needed to find the right object to set the control state, instead of reading it.

**Comment by MOARdV** [comment]
I've got a dev build with trim control on [DropBox](https://www.dropbox.com/s/gaplio91e94fej1/RasterPropMonitor-dev.0.24.1.zip?dl=0).

**Comment by DeputyLOL** [comment]
Thank you
