### ISSUE TITLE
Some model and texture files from Squad used by you are gone in 1.0.5

### ISSUE THREAD

**Issue by RealKolago** [Mihara/RasterPropMonitor#435]
PartCompiler: Cannot clone model 'Squad/Spaces/MK1_Inline_Int/MK1_Inline_Int' as model does not exist
PartCompiler: Cannot clone model 'Squad/Spaces/mk1CockpitInternal/model' as model does not exist
PartCompiler: Cannot replace texture 'model003' as cannot find texture 'Squad/Spaces/mk1CockpitInternal/model003' to replace with
PartCompiler: Cannot replace texture 'model009' as cannot find texture 'Squad/Spaces/mk1CockpitInternal/model009' to replace with

**Comment by MOARdV** [comment]
I see the spaces errors, but I don't see anywhere where the RPM configs are cloning textures (the model003 and model009 errors) - can you provide some more context around those errors?

**Comment by MOARdV** [comment]
Closing issue, since the only RPM-relevant part of this bug was the Mk1 cockpits.
