### ISSUE TITLE
Hide Kerbanaut model in IVA

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#437]
Is it possible to add ability to hide the entire model of Kerbanaut whose eyes we are looking?
Now only the his head is hidden

**Comment by MOARdV** [comment]
It looks like even the head is not hidden with KSP 1.1 prerelease - I can see big googly eyes if I turn the camera far enough to the side.

**Comment by MOARdV** [comment]
I also need to keep this in mind with Issue #480 - I don't want to hide the Kerbanaut if we're in external / transparent pod mode.

**Comment by MOARdV** [comment]
I am implementing the "hide kerbal's head" feature that KSP broke.

@Alexustas : Do you really want to hide the entire model, not just the head?

**Comment by Alexustas** [comment]
I think the best solution may be configurable parameter (in the Internal cfg). kind of `none`, `head `and `all`

for my interior is quite enough to hide only the head. but the idea of what I need to hide entire model I had while working on the cockpit for DeputyLOL. I realized that the giant kerbal's hands closed most of the useful surface of the panels in the middle of cockpit

**Comment by DeputyLOL** [comment]
If I could add to this, I too think we should be able to hide the kerbals bodies or at least their hands.
I can't really use the middle of my cockpit as alexustas said.

**Comment by MOARdV** [comment]
Hiding the hands gets really messy - the only info I have is the head transform.  TO hide hands, I'd have to go up to the body, and then find the arms or hands.  I've got it working now with `head`, `all`, or `none`.
