### ISSUE TITLE
Compound Actions in JSIActionGroupSwitch and RPMC.FixedUpdate

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#439]
Taking the ActionGroupSwitch to its extreme (aka foolhardily introducing limited scripting...): an action mode that allows multiple 'action group' events to be triggered by a single switch (multiple transfers, multiple event toggles, whatever).  I'll have to think through exactly how that will work - it may be something like JSIVariableAnimator where it inspects the config node for multiple sub nodes, only we allow multiple names.

**Comment by MOARdV** [comment]
Change of plans - instead of adding a new switch module, add a new action to the existing switch module.  This action will call a compound action event that contains a sequential list of actions and an enabling variable/range.  This same action event can be listed in RPMC in the craft config file, where it will be loaded and parsed each FixedUpdate - this allows automatic actions per FixedUpdate, provided the enabling variable allows it.  The basic idea comes from DeputyLOL in issue #452 .

**Comment by DeputyLOL** [comment]
If you do implement this, could we have the ability for 'continuous transfers'.
I want to use the variables from navutilites with pilot assistant. 
NavUtilites + (miracle) + Pilot Assistant = Autolanding(crashing) plane!
Let me know.

**Comment by MOARdV** [comment]
I can do an Autolanding(crashing) plane without NavUtilities and Pilot Assistant, and I don't need a mod to do it.  If I ever figure out how to record a gameplay session, I'll show you. :)

I have something in mind that will be able to do what you want.  It will be very flexible and powerful, and hopefully not too laggy.  But it is going to take a while to get it accessible.

**Comment by DeputyLOL** [comment]
If you have windows 10, it allows you to record game sessions.

**Comment by DeputyLOL** [comment]
And, Holy shit I'm really looking forward to this autocrashing plane thing.

**Comment by MOARdV** [comment]
> If you have windows 10, it allows you to record game sessions.

I do, but that takes away my excuse for not recording how badly I fly spaceplanes. :)

**Comment by DeputyLOL** [comment]
to be honest, I'm crap at flying as well. Why do you think I'm trying to make an autopilot. :D 

If you errr... *cough* wanted someone tooooooooo........ errr..... test it, I suppose errrr...... I might be able to.

**Comment by MOARdV** [comment]
I'll PM you on the KSP Forums about testing.

**Comment by DeputyLOL** [comment]
cool

**Comment by DeputyLOL** [comment]
If its not too much to ask, do you think we could still get the compound actions for RPM?
I understand your busy or working on other things so if it is then i'll try and make do.

Alexustas made the nav radios and beacons and so we could use his glide slope to make an autolanding system using pilot assistant. Having a mostly functional autopilot system is the next thing on my list and its gonna be real difficult to do only using buttons.

I've just got back into modding and i'm determined to finish the 737 cockpit.

**Comment by MOARdV** [comment]
I won't be implementing this, since MOARdV's Avionics Systems already provides this capability, and I don't want the extra maintenance overhead of supporting RPM's implementation of it, too.
