### ISSUE TITLE
per-prop (per-monitor) current page number variable

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#445]
local (per prop) variable that returns the current page number of a particular MFD.  I would like to use this variable to control the additional animated overlays, such as circular scale, markers, etc. All these overlays, of course, are part of the monitor. The order of the page numbers can be the same as the pages appear in the configuration file, but it does not matter. the main thing - that this order was repeatable. 

this request is the alternative to my long-standing [request](https://github.com/Mihara/RasterPropMonitor/issues/210)

**Comment by MOARdV** [comment]
Per-prop variables are challenging.  This variable is only accessible on this prop, correct?

**Comment by Alexustas** [comment]
Yes

**Comment by MOARdV** [comment]
Closing this feature and adding it to #478 .

**Comment by MOARdV** [comment]
Actually, this information is available and well hidden.

PERSISTENT_activePage### will tell you the active page of the monitor in prop ### (for instance, on your Mk1-2 IVA, it is activePage106, activePage107, ..., activePage113.  (Look in persistent.sfs and search for "RPM_PERSISTENT" - you will see the list of persistent variables per part).

Not helpful if you move props around in the IVA so the prop ID changes.  But the page numbers and the propID is consistent from save to save.

**Comment by Alexustas** [comment]
very interesting information, thank you. 
but it's not quite what I need. because I need to do separate props  (or rather configs) for different MFDs in the same IVA.

**Comment by MOARdV** [comment]
A different prop can still query, for example, PERSISTENT_activePage106, to see what page is active on MFD #106.
