### ISSUE TITLE
Looping Sound Issue.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#446]
Sounds stop playing if you leave and re-enter IVA, even if they are set to loop. 
Unless the prop that they are sounding from has a flashing delay.

Nuf' said

**Comment by DeputyLOL** [comment]
On the issue of sound, I had a little request. Currently, if you have a sound that is set to loop and must play once, the sound will start and never stop which is understandable. Could we make it so that if a sound has both of these configs, the sound will repeat but not cut-off when the variable is not longer met.
The example in my cockpit is a terrain voice alarm.
Even better would be a way of 'grouping' sounds, so only one sound in a particular group can be playing anytime.

Just a thought

**Comment by MOARdV** [comment]
> Could we make it so that if a sound has both of these configs, the sound will repeat but not cut-off when the variable is not longer met.

I'm not sure what you're asking me to change - right now, once a looping alarm starts with 'must play once' set, it looks like it doesn't cut off.  How is that different than what you're requesting?

> Even better would be a way of 'grouping' sounds, so only one sound in a particular group can be playing anytime.

Each animator tracks its audio on its own.  Grouping audio would require a new audio alarm class.  JSIVariableAnimator would require too much special-casing to take on that task in addition to its existing tasks.

**Comment by DeputyLOL** [comment]
Ignore the second request.
For the first one I mean that the alarm will keep repeating while the alarm is on. When the alarm is off, it will finish playing the sound file and then stop. I can only really explain with an example.

Currently with loop on and must play once off
Terrain alarm: ON------------------------->OFF----------------->ON----------->
           Sound: TERRAIN TERRAIN TER-                         TERRAIN etc...

Currently with loop on and must play once on
Terrain alarm: ON------------------------->OFF----------------->ON----------->
           Sound: TERRAIN TERRAIN TERRAIN TERRAIN TERRAIN etc...

My request with loop on and must play once on
Terrain alarm: ON------------------------->OFF----------------->ON----------->
           Sound: TERRAIN TERRAIN TERRAIN                 TERRAIN etc...

**Comment by MOARdV** [comment]
What you're asking for is something that will allow the audio loop to play to the end?  I don't know if I have a way to do that, since the 'looping' property is part of FXAudio effect, while the playing / not playing is controlled separately.  I may be able to toggle 'looping', but I'm not sure.

**Comment by DeputyLOL** [comment]
ok

**Comment by DeputyLOL** [comment]
if its too much work then don't worry about it.
