### ISSUE TITLE
TIMETOATMOSPHERESECS

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#447]
Time remaining until the craft crosses the atmosphere top (going either direction).  Return 0 if invalid.  I've wanted this for reentry planning, particularly in craft using newer Alexustas props where I didn't install a digital altimeter.

**Comment by MOARdV** [comment]
Also add a TIMETOSOISECS, same idea, just counting down to the SOI change (although I thought there already was one?).

**Comment by Alexustas** [comment]
> just counting down to the SOI change 

Yes, "ENCOUNTERTIME" variable

**Comment by MOARdV** [comment]
I knew it was in there somewhere.  Too many variables to remember :)
