### ISSUE TITLE
Pilot Assist (MAX/MIN limits)

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#449]
As per your comment, new pilot assist requests go in separate fields.

A way of adjusting PAs limits on the go. I'm still working on my autopilot and while it can hold an altitude, I think it would be a big help if I could specify how fast it should climb or descend. (adjusting the MAX/MIN of the altitude control in the altitude mode).

I have no idea how the logistics of this would work and can imagine that it would probably be complicated.

**Comment by MOARdV** [comment]
Min/Max settings are buried pretty deeply in Pilot Assistant.  It'll require changes to that mod to expose them.  I agree it sounds like it would be complex to adjust - is it something you'd actually want to change in flight?  I would think it'd be easier to set it and forget prior to departure.

**Comment by DeputyLOL** [comment]
When adjusting altitude, you would want to set the vertical speed.
If you set the plane to climb to a low altitude at a vertical high speed, the plane would be ok.
But if you set the plane to climb to a high altitude at a vertical high speed, the plane would lose speed, stall and drop. The only fix would be to have the plane climb slowly to its target.
But then if the plane was set to always climb at a slow speed, it would take a long time to reach the target altitude.

As for descending, the plane has a certain vertical speed, where it will descend without gaining speed. But then we have the speed brakes that allow us to descend faster without speeding up.

Being able to adjust these would be a great help.
If the vert speed is set to 0, then I would use the defaults.

**Comment by DeputyLOL** [comment]
Also, I have a dial that can adjust bank limits for when the plane is following a heading. So being able to adjust that would also be helpful.

**Comment by Alexustas** [comment]
:airplane:  Kerbal Flight Simulator X  :airplane:  ))

**Comment by DeputyLOL** [comment]
Yeah!
:airplane: X-SpacePlane 10 :airplane:

**Comment by DeputyLOL** [comment]
PA no longer accepts speed inputs. Probably due to the update. You can turn the throttle pilot on and off but you cant set a target speed.

**Comment by MOARdV** [comment]
> PA no longer accepts speed inputs. Probably due to the update. You can turn the throttle pilot on and off but you cant set a target speed.

Arg.  Okay.

**Comment by DeputyLOL** [comment]
Do you think there could be an option to specify the type of speed and unit using rpm?

**Comment by Crzyrndm** [comment]
https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L748-L758

For future reference, if someone could ping me so that I know some changes are required on my end, that'd be a great help

**Comment by DeputyLOL** [comment]
thank you. I'll do that in future.

**Comment by MOARdV** [comment]
@DeputyLOL - what features are currently missing?  MAX/MIN limits, selecting speed type.  I want to gather all of them in one thread so I don't have to look around to find what's missing.

**Comment by DeputyLOL** [comment]
Yeah the max and min limits, selected speed type and unit would be nice. I'll include post from PA that lists the things ready to implement.

**Comment by DeputyLOL** [comment]
Crzyrndm commented on Dec 29 2015 
Some updates from the previous 24 hours that may be helpful for RPM (pending release)
•Pushed the pause toggle to a method (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L717)
•Changing the speed reference (TAS/IAS/EAS) is handled by the method ChangeSpeedRef (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L688)
•Changing the speed unit (m/s, km/h, etc.) can be handled through the method ChangeSpeedUnit (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L711)
•Target updating now applied to GUI even if the modules are inactive (Still need to pass the value through again on activation if it's to be used)
•Fixed the speed control update not respecting the selected units

**Comment by MOARdV** [comment]
This will be slow going, since I don't want to hook everything up at once and cross my fingers - here's the first step:

Speed reference is in this dev build, I think: [DropBox](https://www.dropbox.com/s/wpsmlyglgmdta2l/RasterPropMonitor-dev.0.25.2.zip?dl=0)

`JSIPilotAssistant:GetSpeedRef` should return the current speed ref, `JSIPilotAssistant:ChangeSpeedRef` will set it.  0 = True, 1 = Indicated, 2 = Equivalent, 3 = Mach.

You will want to check in the log to see if there are lines like "RasterPropMonitor: Exception tripped:" - those indicate that something went wrong trying to connect to JSIPilotAssistant.  The current speed reference isn't in a public variable, so I'm not 100% sure I can read it.

**Comment by DeputyLOL** [comment]
ill give it a test

**Comment by DeputyLOL** [comment]
The 'GetSpeedRef' works fine but I'm having trouble getting the ChangeSpeedRef to work. It might be due to how I'm trying to use it.
Ill keep trying until I'm sure it doesn't work.

**Comment by DeputyLOL** [comment]
Ok, it works. I get this in the log:
[ERR 16:45:44.372] RasterPropMonitor: Pilot Assistant speedRef is visible (this is not an error)

But, the ChangeSpeedRef is very picky about what it will accept. I don't think it will accept anything except for some PERSISTENT variables in the transfer.

**Comment by DeputyLOL** [comment]
Ok, it all works. The issue with ChangeSpeedRef was due to the transfer action.

**Comment by MOARdV** [comment]
Okay, I've added GetPauseState and SetPauseState - same [DropBox](https://www.dropbox.com/s/wpsmlyglgmdta2l/RasterPropMonitor-dev.0.25.2.zip?dl=0) link.

**Comment by DeputyLOL** [comment]
sorry for the delay. Testing it now.

**Comment by DeputyLOL** [comment]
Would the setPauseState be a trigger or transfer variable?

**Comment by DeputyLOL** [comment]
OK, nevermind it was a plugin action. Both work perfectly.

**Comment by MOARdV** [comment]
Okay.  New ones for today on [GitHub](https://www.dropbox.com/s/wpsmlyglgmdta2l/RasterPropMonitor-dev.0.25.2.zip?dl=0): GetSpeedUnits and ChangeSpeedUnits.  Speed units are 0 = m/s, 1=km/h, 2=mph, 3=knots, 4=mach

**Comment by DeputyLOL** [comment]
Get/Set speed units works perfectly. Thank you.

**Comment by MOARdV** [comment]
It looks like separate max / min limits are not readily accessible for me, and there are hoops I need to jump through even to set max.  I think even if min and max were accessible, the complexity required to interact with them is high enough that I don't want to tackle it, since it's not a mod I use.  Any problems that crop up because of mistakes I make are going to be a challenge to resolve (I don't have an installation with Pilot Assistant, and, more importantly, I don't have an IVA with all of the props needed to test the interface and the props I would need to test additional components).

I think the other changes from December are already handled with the code as it is.

**Comment by DeputyLOL** [comment]
Yeah your right. I think this is going to be enough. Thank you for implementing it. :D
