### ISSUE TITLE
Log full of MATH_ equations.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#450]
Don't know if this was left over from the dev build but my log fills up with math equations when ever I'm in IVA.

[LOG 09:11:42.497] MathVariable: [0] = 0.8
[LOG 09:11:42.500] MathVariable: [1] = 0.4
[LOG 09:11:42.502] MathVariable: --- = 0.3
[LOG 09:11:42.505] MathVariable: [0] = 0.4
[LOG 09:11:42.508] MathVariable: [1] = 0.0
[LOG 09:11:42.510] MathVariable: --- = 0.4
[LOG 09:11:42.571] MathVariable: [0] = 72.4
[LOG 09:11:42.574] MathVariable: [1] = 500.0
[LOG 09:11:42.576] MathVariable: --- = -427.6
[LOG 09:11:42.579] MathVariable: [0] = 0.8
[LOG 09:11:42.582] MathVariable: [1] = 0.4
[LOG 09:11:42.585] MathVariable: --- = 0.4
[LOG 09:11:42.587] MathVariable: [0] = 0.4
[LOG 09:11:42.591] MathVariable: [1] = 0.0
[LOG 09:11:42.593] MathVariable: --- = 0.4
[LOG 09:11:42.656] MathVariable: [0] = 72.4
[LOG 09:11:42.659] MathVariable: [1] = 500.0
[LOG 09:11:42.662] MathVariable: --- = -427.6
[LOG 09:11:42.665] MathVariable: [0] = 0.8
[LOG 09:11:42.668] MathVariable: [1] = 0.4
[LOG 09:11:42.670] MathVariable: --- = 0.4
[LOG 09:11:42.673] MathVariable: [0] = 0.4
[LOG 09:11:42.676] MathVariable: [1] = 0.0
[LOG 09:11:42.679] MathVariable: --- = 0.4
[LOG 09:11:42.792] MathVariable: [0] = 72.4
[LOG 09:11:42.795] MathVariable: [1] = 500.0
[LOG 09:11:42.798] MathVariable: --- = -427.6
[LOG 09:11:42.800] MathVariable: [0] = 0.8
[LOG 09:11:42.803] MathVariable: [1] = 0.4
[LOG 09:11:42.805] MathVariable: --- = 0.4
[LOG 09:11:42.808] MathVariable: [0] = 0.4
[LOG 09:11:42.811] MathVariable: [1] = 0.0
[LOG 09:11:42.813] MathVariable: --- = 0.4
[LOG 09:11:42.924] MathVariable: [0] = 72.4
[LOG 09:11:42.926] MathVariable: [1] = 500.0
[LOG 09:11:42.929] MathVariable: --- = -427.6
[LOG 09:11:42.932] MathVariable: [0] = 0.8
[LOG 09:11:42.934] MathVariable: [1] = 0.4
[LOG 09:11:42.937] MathVariable: --- = 0.3
[LOG 09:11:42.939] MathVariable: [0] = 0.4
[LOG 09:11:42.942] MathVariable: [1] = 0.0
[LOG 09:11:42.944] MathVariable: --- = 0.4
[LOG 09:11:43.054] MathVariable: [0] = 72.4
[LOG 09:11:43.056] MathVariable: [1] = 500.0
[LOG 09:11:43.059] MathVariable: --- = -427.6
[LOG 09:11:43.062] MathVariable: [0] = 0.8
[LOG 09:11:43.064] MathVariable: [1] = 0.4
[LOG 09:11:43.067] MathVariable: --- = 0.4
[LOG 09:11:43.069] MathVariable: [0] = 0.4
[LOG 09:11:43.072] MathVariable: [1] = 0.0
[LOG 09:11:43.074] MathVariable: --- = 0.4

etc!

**Comment by MOARdV** [comment]
Woops.  It looks like I overlooked some debug code when I was working on it.  It's removed from the dev build I just put on [DropBox](https://www.dropbox.com/s/47ezo8iq219jz3s/RasterPropMonitor-dev.0.24.2.zip?dl=0)

**Comment by MOARdV** [comment]
BY the way, this dev build also has configurable horizontal bars (issue #329).  They're untested as of right now (I hadn't gotten to testing them) - they work the same as the configurable vertical bars, but use a node name of `JSIHUD_HORIZONTAL_BAR`.

**Comment by DeputyLOL** [comment]
Cool, ill have a look at them and let you know.

**Comment by DeputyLOL** [comment]
I've been thinking, seeing as the NAV Utilities mod is not being updated anymore. 
Do you think it would be possible to create waypoints in RPM? I wanted to ask you here to see if there was a possibility before creating a new issue

**Comment by MOARdV** [comment]
> Do you think it would be possible to create waypoints in RPM?

Like in Issue #302? :)

**Comment by DeputyLOL** [comment]
first attempt at horizontal bars..(drum roll)...... nothing happened!

**Comment by DeputyLOL** [comment]
and yes like in #302

**Comment by MOARdV** [comment]
> first attempt at horizontal bars..(drum roll)...... nothing happened!

Yeah, I was able to start a test at about the same time, and the same thing happened.  I'll have to figure out what I messed up when I get some time later today.

**Comment by MOARdV** [comment]
DropBox updated - I saw one glaringly obvious 'oops'.  Still untested (btw, I forgot to mention that horizontal bars need to be listed under `horizontalBar` in the JSIHUD config).  Although lets continue this particular discussion in #329

**Comment by DeputyLOL** [comment]
We can close this now.
Can I just say that what ever you did in this update has massively improved the performance of my cockpit. Thanks!

**Comment by MOARdV** [comment]
I'll take care of closing it - I keep the issues open to help remind me to update all the things that need updated.

As for performance - I'd love to know which change helped.  I mean, other than not spamming your log with debug messages (which causes lag).  There were a couple of other little things I changed, but I haven't had enough time to really see what effect they had.

**Comment by DeputyLOL** [comment]
I couldn't say which thing exactly. The noticeable difference came when I updated to v0.24.2. 
My cockpit has a lot of sound files, a fair amount of big textures and small textures, about a ton of variables and a lot of unused props, models and other stuff. What ever you worked on improving I'd say had a big impact. Add the fact that my computer is fairly old, unstable and basic, and that I usually run KSP with about 6 other programs while modding, to see my cockpit actually run smoothly for the first time ever is a great feeling.
