### ISSUE TITLE
Pilot Assistant updated, RPM doesn't work with new version

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#453]
Per DeputyLOL

> PA no longer accepts speed inputs. Probably due to the update. You can turn the throttle pilot on and off but you cant set a target speed.

**Comment by MOARdV** [comment]
Finally got around to looking at this - I am not having a problem setting target speed.  I took off, set a cruising altitude and heading, and I was able to set speed as well, and all controls worked.

**Comment by DeputyLOL** [comment]
most recent version of pilot assist?

maybe it was just me, ill have a closer look?

**Comment by DeputyLOL** [comment]
what's wrong with this?

	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		//masterVariableName = CUSTOM_AUTOT_DISCONNECT
		//masterVariableRange = -0.5, 0.5
		//switchGroupIdentifier = 3
		perPodPersistenceName = AUTOT_SPEEDMODE_BUTTON
		switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleSpeed
		    perPodPersistenceName = MCP_SpeedDial
		    //stateVariable = CUSTOM_AUTOP_ALTHOLD_BUTTON_BLOCK
		}
	}

**Comment by DeputyLOL** [comment]
WELP, IM AN IDIOT AS USUAL!
I got the persistent name wrong and immediately assumed that it was RPMs fault. It should have been MCP_SpeedInput not MCP_SpeedDial. 

Sorry about that.
You can close this now.

Hows the transfer action upgrades going?

**Comment by DeputyLOL** [comment]
Maybe not, I just corrected it and its still not working.

**Comment by MOARdV** [comment]
All of your important values match mine.  You've made sure that PERSISTENT_AUTOT_SPEEDMODE_BUTTON is true, correct?

**Comment by DeputyLOL** [comment]
ill have a look

**Comment by DeputyLOL** [comment]
works now after update
