### ISSUE TITLE
Delay Variable

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#454]
Would it be possible to have some sort of internal timer that can trigger a variable?
I cant really explain how it would work but I have an idea of how the config could look like. It would probably be more understandable this way.

My idea for a config would be like this.

RPM_DELAY_VARIABLE
{
   name = BLAH (name of delay variable: DELAY_BLAH. 1 if the timer reaches 0)
   timername = BLAHBLAH (shows the timers value: TIMER_BLAHBLAH.)
   delay = (number of seconds)
   stopOnReset = true/false (if true the timer will stop when reset, if false the timer will continue counting down when reset if it wasn't already stopped)
   loopTimer = true/false (if true, timer will immediately reset on reaching 0, if false the timer will stay at 0 until reset.
   startVariable= CUSTOM_SOMETHING (Timer will start counting down when this is active)
   startRange = #, # 
   stopVariable= CUSTOM_SOMETHINGELSE (Timer will stop counting down when this is active)
   stopRange = #, # 
   resetVariable= CUSTOM_ANOTHERSOMETHINGELSE (Timer will reset when this is active)
   resetRange = #, # 
}

Let me know what you think.

**Comment by MOARdV** [comment]
I'll have to think about it. :)

**Comment by DeputyLOL** [comment]
ive been thinking about is more. you would only need 'timername' as you could use CUSTOM_ variables to detect when the timer is at 0 or not. You could also use the CUSTOM_ on other numbers in the timer, not just 0.

**Comment by MOARdV** [comment]
A delayed timer event gets really twitchy due to entering / exiting IVA - typically, all of the state is suspended when exiting IVA, so the timer may expire while in the external view, but the action won't trigger.

Right now, I think I'm going to say "won't implement" on this issue.  If I get more free time for new features, I can revisit this.
