### ISSUE TITLE
Buttons work with controller inputs?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#455]
Would it be possible to assign a button to a keyboard button or to a joystick button? I'm going to get a joystick to fly, but would like to know if I could assign the buttons on it to interact with buttons in my cockpit? 
I know that it might not be possible due to the limitations of the game and that the buttons that can be controlled by keyboard have an in game function (brakes, SAS, gear....)

Let me know what you think.

**Comment by MOARdV** [comment]
The buttons in IVA all work on colliders.  Having to add a dispatch system to handle physical buttons (keyboard or joystick) is more work than I'm willing to take on (particularly since I don't have a joystick).

**Comment by DeputyLOL** [comment]
Fair enough
