### ISSUE TITLE
Bar graph threshold question

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#458]
I'm starting to use bar graphs as engine displays until the round gauges are implemented.
I notice that you can change the colours of the graph when it is full and empty and the colour will change as the graph fills. I was wondering if we could use the threshold config to specify a point where the graph changes colour.
So instead of slowly fading from white to red, the graph is white until it is within the threshold.
Currently trying to use threshold with a vertical graph results in the graph not filling at all.

Just letting you know about it as I thought it might have been a bug (or if not, a potential feature).
If it isn't easy then don't bother because I'm only using these until this is finished: #374

**Comment by MOARdV** [comment]
Adding as part of issue #478
