### ISSUE TITLE
HOTTEST* variables

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#460]
VIDEO: https://youtu.be/_0Ey8X4DSEI

It seems that the HOTTESTENGINEMAXTEMP variable uses stock value and does not take into account the modifications made by other mods, such as DRE.
A variable HOTTESTPARTMAXTEMP variable take into account these modifications.

And also, for HOTTESTENGINETEMP uses the 'ALL SKIN' value and variable HOTTESTPARTTEMP - 'Internal Temp' value

**Comment by MOARdV** [comment]
It looks like I have a copy-paste bug in the engine temperature - it looks only at skin temperature, but not internal.  That is an easy fix.  Both hottest engine and hottest part are supposed to report the part that is closest to its maximum temperature, either (max skin temperature - current skin temp) or (max internal temp - current internal temp).
