### ISSUE TITLE
JSIInternalBackgroundNoise doesnt stop when out of IVA

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#463]
Not really anything else to explain about this bug.

BTW, I released some previews of my cockpit and mentioned your mod.
You can check it out if you want. :D 
http://forum.kerbalspaceprogram.com/index.php?/topic/129964-advanced-cockpit-b737-style-iva-cockpit-with-functional-systems/

**Comment by MOARdV** [comment]
Hm.  According to the code, the sound should stop.  I will see if I can reproduce it here.

**Comment by DeputyLOL** [comment]
Now JSI Internal sound doesn't play at all...

**Comment by MOARdV** [comment]
There haven't been any changes to the JSI code - is there another mod that might be interfering?

**Comment by DeputyLOL** [comment]
I don't think so, I'll try and find out. What type of mod do you think could be interfering?
I'm

**Comment by DeputyLOL** [comment]
Actually thinking about there are other things that I've noticed about the internal modules. They tend to work until the database is reloaded and then they disappear. I noticed this when the seat FOV kept disappear from the cockpit internal config. I'm guessing it's related.

**Comment by DeputyLOL** [comment]
I think I figured it out. All the internal modules have to put directly into the internal config for them to work. It cant be assigned to it in a different config file.
So this.....
@PART[mk3Cockpit_Advanced]:NEEDS[RasterPropMonitor]
{
	@INTERNAL
	{
		@name = DLAdvCockpitInternal
	}
	MODULE
	{
		name = RasterPropMonitorComputer
		triggeredEvents = genon|genoff|engon|engoff|autobrakespoiler|autobrake|sasdisconnect|sason|sasoff|vpon|vpoff|hpon|hpoff|aton|atoff	 
	}
	MODULE
	{
		name = JSIInternalBackgroundNoise       <---
		soundURL = (Sound)
		soundVolume = 1
	}
}
..... doesn't work. Unless I'm missing something else?

It works fine when put directly into the space's internal config.
This is annoying as all the internal modules get deleted every time you make changes to the internal in unity.

**Comment by MOARdV** [comment]
> I think I figured it out. All the internal modules have to put directly into the internal config for them to work. It cant be assigned to it in a different config file.

JSIInternalBackgroundNoise is an internal module - it has to be in the internal space's config.  The MM config you show adds the JSIInternalBackgroundNoise to the part.  You would need to do one of two things: either a module manager config to add the background noise module to your existing internal config, or add it module to the internal config directly as a step after you save updates in Unity.  If you keep a text file with the snippet you need to add after saving, it's a simple copy-paste step.  There's not much I can do about that - it's the way KSP is.

**Comment by DeputyLOL** [comment]
Fair enough. I will probably do the second one. You can close this now if you want. 
Thank you for the answer.
