### ISSUE TITLE
More complex math variables

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#465]
Do you think we could have roots and squares added to the math variables?
I'm trying to make a localizer and glide slope without relying on NAV Utilites and I have to use lat and lon coordinates.
Problem is that I need to know the distance between the runway and the ship which I can't get without being able to square root.

**Comment by DeputyLOL** [comment]
Do you think that we could also have a MID operator. Its would work like MAX and MIN but it would basically clamp a variable between 2 numbers. It would mean that it can only take 3 source variables though.

**Comment by MOARdV** [comment]
A clamp operator can be accomplished with a MIN and a MAX.  I don't want to go too far down the path of adding special math variables - it becomes very cumbersome.  At some point, it'll be better adding a scripting language instead.  Which may not be a horrible idea, but it's not something I have time for.

**Comment by DeputyLOL** [comment]
I know that clamping can be done with max and min variables. It's just a little messy. You don't have to do it if it's not worth it.
Is the root possible?

**Comment by DeputyLOL** [comment]
Ive been thinking about the roots and did a bit of research. If I am correct in assuming that KSP uses C# then I might have come up with something. I created a pull request that may add the ablility to use powers and therefore be able to use roots! please let me know what you think and if it could be implemented.

**Comment by DeputyLOL** [comment]
I think this is now closable. Thanks again.

**Comment by DeputyLOL** [comment]
Could we have maths variables with only one number?

**Comment by DeputyLOL** [comment]
Do you think we could have a 'round to' math variable?
So the input is rounded to the nearest 1, 2, 5, 10, 20.. etc?

**Comment by MOARdV** [comment]
Due to the extensive work I expect for v0.25.0 / KSP 1.1, new features are being booted to a later update.

**Comment by DeputyLOL** [comment]
Ok

**Comment by MOARdV** [comment]
What features are still open here - there was a request for a MID operator (essentially, CLAMP) - that's not going to be viable with the current design.  You've already added POWER and ATAN2.  I don't think the ROUND function is viable, since the only built-in options are selecting the number of places after the decimal, like round(123.4567,2) = 123.46.  To round to an arbitrary step, like 5 or 10, requires writing the algorithm by hand.

**Comment by DeputyLOL** [comment]
ok, I guess you can close this then. Thank you for implementing them.
