### ISSUE TITLE
known incompatibalities

### ISSUE THREAD

**Issue by LexingtonDelta** [Mihara/RasterPropMonitor#473]
does anyone know which mods this doesnt work with? i have like 12 installed and one of them( not sure which) is causing all buttons to be unclickable, the RPM displays and buttons are in the right place, but cant interact with any of them

**Comment by MOARdV** [comment]
Unfortunately, there are far too many mods out there for me to maintain a list of incompatibilities.  You will have to remove the mods one at a time until the RPM buttons start working (or remove all of the mods, and add them back in one at a time).

**Comment by LexingtonDelta** [comment]
Dam I was homing do to the fact u can see but nit interact it could near it lol. Great mod btw



Sent from Outlook Mobile






On Mon, Mar 28, 2016 at 5:14 AM -0700, "MOARdV" <notifications@github.com> wrote:





Unfortunately, there are far too many mods out there for me to maintain a list of incompatibilities.  You will have to remove the mods one at a time until the RPM buttons start working (or remove all of the mods, and add them back in one at a time).

---

**Comment by LexingtonDelta** [comment]
so, apperintly the work around was do downgrade to 21.2 RPM

**Comment by MOARdV** [comment]
Without additional information on what mods and versions you're using, and an output log, there's nothing else I can recommend.
