### ISSUE TITLE
Account for stock cutaway mode

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#480]
The KSP 1.1 cutaway mode allows the player to see into the craft from the outside (replacing JSITransparentPod with the right planning).  I should see what it takes to detect that condition (external camera + cutaway mode active) so I can make sure RPM updates from that viewpoint, instead of hibernating.

**Comment by JPLRepo** [comment]
`
public bool StockOverlayCamIsOn   
{   
         get   
            {   
                Camera StockOverlayCamera = JUtil.GetCameraByName("InternalSpaceOverlay Host");   
                if (StockOverlayCamera != null) return true;   
                else return false;   
            }   
        }   
 `   
Will tell you if the new Stock Overlay Camera is On or Off.
Jutil.IsInIva() will tell you if you are in IVA mode or not.

**Comment by MOARdV** [comment]
@JPLRepo  - thanks for the code snippet.
