### ISSUE TITLE
Add JSILabel text class

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#486]
Once the callback system from Issue #343 is implemented, add a three-value color system to JSIVariableLabel:

```
variableName = (defined variable)
positiveColor = R,G,B,A
negativeColor = R,G,B,A
zeroColor = R,G,B,A
```

This addresses the use of variables simply to color text on those labels, which results in a lot of variable queries and string re-processing.  Changing it to use the callback system to select colors will make it more responsive, and it will eliminate all of the round trips and string parsing overhead.

**Comment by Alexustas** [comment]
whether it is possible in the new version of Unity and KSP customize the label text, such as font or shader?

**Comment by MOARdV** [comment]
> whether it is possible in the new version of Unity and KSP customize the label text, such as font or shader?

With existing JSIVariableLabel, not yet.  It may be possible (have to test), since there are parts visible - I see a font object, a text alignment object, and a MeshRenderer (which has a material, which has a shader).  I will have to experiment.

**Comment by MOARdV** [comment]
It looks like color is changeable, although I suspect it works as "multiply Color by the color in [#RRGGBBAA]", since when I hacked the colors to XKCDColors.BabyBlue, the backlit text was blue until I turned it off.  That should still work just fine.

**Comment by Alexustas** [comment]
I very much hope that we will be able to replace a shader that is used for the VariableLabel text, if necessary. because any non-black color labels glows in the dark, which is not always acceptable

**Comment by MOARdV** [comment]
> I very much hope that we will be able to replace a shader that is used for the VariableLabel text, if necessary. because any non-black color labels glows in the dark, which is not always acceptable

Yes, disabling the emissive channel would be good, or at least being able to set emissive and diffuse separately.  I don't know what shader they use, so I don't know if there's a way for me to do that without providing a replacement shader - I will see if I can find out.

**Comment by MOARdV** [comment]
The color selection code makes a big difference in the RPM prop workload.  I added some profiling code to track which variables are called, and how often they are called, with that info written to a sorted list in the log when exiting Flight.  Before I started making changes `CUSTOM_ALCOR_BACKLIGHT_ON` was being called on average more than 14 times per FixedUpdate.  Once I changed prop backlights animations to use the JSICallbackAnimator, that number dropped to 9.  By also adding this code, I got that number down to 2.6.  The only variable that looks like it's being called too much now is `CUSTOM_FDAIGMCP_ON-01` (9.1 calls per FixedUpdate).  Beyond that, nothing's called more than 3.7 times on average.

**Comment by MOARdV** [comment]
Changing fonts will most likely have to be done using an AssetBundle - I don't see another way to find which fonts are enabled in KSP, but it looks like I can add additional text fonts through the asset bundle mechanism.  If I read the documentation correctly, we can reference fonts that are found on the computer without embedding them, or, if there are fonts that are open license (free to distribute, and that we can include in the project), they can be embedded in the asset bundle.

**Comment by MOARdV** [comment]
Pushing font / formatting questions onto v0.25.1

**Comment by MOARdV** [comment]
Alignment doesn't work, or I don't know the trick to change it.  I tried setting the alignment based on changing the variable directly, and using the SetAlignment method, and neither affected the output.  Neither did calling UpdateMesh afterwards.  I may need to look at a replacement text object to allow more control over text.

**Comment by MOARdV** [comment]
Good news - I can change the text anchor and alignment, so for instance labels for switches can have their transform moved to the center of the switch, and they can center the text on that transform, so we don't have to manually adjust its position.

Bad news - trying to load another system font is not working.  I am still trying to understand this.  Also, the color tags [#rrggbbaa] do not work.  But the color stuff I did in the first comment of this thread *does* work, so I will make sure that you can specify a constant color as part of the config for the new part.  It will be a new module (JSILabel?).  It looks like the TextMesh supports "richText", which is described as "Enable HTML-style tags for Text Formatting Markup", but I don't know what that does.  I have not tried replacing shaders.

Still a lot of work, but maybe some progress.

**Comment by MOARdV** [comment]
More progress:

![fonts](http://imageshack.com/a/img922/9358/DFNHhL.jpg)

JSILabel can load any font available on the computer (if the font is unknown, it will use Arial).  The config can specify alignment (above is "Center").  The config can specify anchor (where the text will draw from) - for example, if the 'WarningText_2Lines' transform in the retro warning lamp is moved to the very middle of the prop, anchor `MiddleCenter` will make all of the text centered on the middle of the prop.

I tried to get richText to work, since it supports **bold**, _italics_, size, and color, but it is not working for me yet.  So, for now, text color has to be configured with the 'zeroColor' config option.

**Comment by Alexustas** [comment]
is a new label font have an outline and shadow like stock?

**Comment by MOARdV** [comment]
> is a new label font have an outline and shadow like a stock ksp font?

I do not know - I did not see any, but I have not drawn large text yet.  Do you want it to have outline and shadow?

Oh - I think I will be able to change shaders, also, once I find a good shader for "not illuminated".

**Comment by Alexustas** [comment]
> Do you want it to have outline and shadow?

No! No! And NO! ))

> Oh - I think I will be able to change shaders, also, once I find a good shader for "not illuminated".


that's what I really want

**Comment by MOARdV** [comment]
I do not see outline and shadow even when I expand the text to large sizes.  Or maybe it's just the font I used. :)

**Comment by MOARdV** [comment]
Okay, early sample on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  Use [JSILabel](https://github.com/Mihara/RasterPropMonitor/wiki/JSILabel) instead of JSIVariableLabel.

**Comment by MOARdV** [comment]
Text color markup works, but it requires closing tags (I left them out previously)

```
<color=red>Red Text</color>
```

Per [Unity Rich Text](http://docs.unity3d.com/Manual/StyledText.html).  Bold and italics tags also work (`<b>Bold</b>` and `<i>italics</i>`).  I assume size works, but I did not test it.

**Comment by Alexustas** [comment]
some nice free fonts:

LCD indicators/displays

http://www.1001fonts.com/repetition-scrolling-font.html?text=198.36%20m&size=66&fg=ffffff&bg=000000
http://www.1001fonts.com/hydrogentype-font.html?text=GEAR%20LIGHT%20BRAKES%20573&size=66&fg=ffffff&bg=000000
http://www.1001fonts.com/ticketing-font.html?text=Periapsis%20124.98%20(km)&size=66&fg=ffffff&bg=000000
http://www.1001fonts.com/01-digit-font.html?text=GEAR%20LIGHT%20BRAKE%2009.23%25&size=66&fg=ffffff&bg=000000
http://www.dafont.com/register.font?text=%2F+%2B+-159.2+km%2Fs+MG%28+%25%29&back=theme
http://www.dafont.com/receiptional-receipt.font?text=%2F%2B-9.2+m%2Fs&back=theme

http://www.fontspace.com/style-7/digital-7?text=-124.36&foreground=0cff05&background=000000
http://www.fontspace.com/philing/7led-italic?text=-0.35&background=1bfa00
http://www.fontspace.com/allen-r-walden/crystal?text=-3.50&foreground=cee5f3&background=162346

Panels, instruments lanels

http://www.1001fonts.com/inconsolata-font.html?text=GEAR%20LIGHT%20BRAKES%20ON%20OFF%20START&size=66&fg=ffffff&bg=000000
http://www.1001fonts.com/liberation-mono-font.html?text=GUID%20CTRL%20ATTITUDE&size=66&fg=ffffff&bg=000000

**Comment by MOARdV** [comment]
If you have any fonts you like better, let me know. Or I can pick them.

I am going to add a `transformOffset` option to JSILabel so your existing props can be used without having to re-export them with a new transform location.

**Comment by Alexustas** [comment]
Do I understand correctly, the user will have to manually install the needed font?

**Comment by Alexustas** [comment]
> I am going to add a transformOffset option 

excellent!

**Comment by MOARdV** [comment]
tranformOffset now works.  [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  It moves the named transform, so if anything else is attached to the transform, it will move also.  I plan on changing it so that the transform is not moved, but that does not work yet.

For Retro Warning Lamps, I find the following parameters work for two-line messages:
```
fontName = Arial Bold
fontSize = 0.0045
alignment = Center
anchor = UpperCenter
transformOffset = 0.02, 0
zeroColor = 0,0,0,255
```

(Use zeroColor by itself to set the color of the text.  Can also use html-style <color=#000000>SomeText</color>, as well as <b>BoldText</b> and <i>Italic</i>)

> Do I understand correctly, the user will have to manually install the needed font?

If the fonts have a license that allows me to include them in RasterPropMonitor, they will not need to manually install.  I will see what the rules are for those fonts.

System fonts (Arial, Times New Roman, Courier New), work automatically if the user's computer has those fonts.  If you set RasterPropMonitor's config to `debugLogging=true`, right now the dev version will list all fonts installed on your computer.

**Comment by Alexustas** [comment]
> right now the dev version will list all fonts installed on your computer.

because of my work I have installed quite a lot of fonts ))

**Comment by Alexustas** [comment]
now I am most excited about the opportunity to text labels is not always shining, as it is now

**Comment by MOARdV** [comment]
> now I am most excited about the opportunity to text labels is not always shining, as it is now

That will be next. :)  I am making a couple of config changes so font size is not always a tiny number, so I do not recommend using this except for maybe a little bit of testing, so you do not have to change too many configs.

**Comment by MOARdV** [comment]
Something I have discovered: the font in JSIVariableLabel uses lower resolution textures for rendering characters, which explains why it is blurry and harder to read for me.  Text with JSILabel using the same Arial font is easier to read at the same size.

**Comment by Alexustas** [comment]
>  is easier to read at the same size.

but I have a completely opposite situation

![screenshot125](https://cloud.githubusercontent.com/assets/6713671/15228084/1ec776f6-18ac-11e6-98f8-d338320a7190.png)

**Comment by Alexustas** [comment]
"FUEL CELL" - JSILabel
"ON" and "OFF" - JSIVariableLabel


```
	MODULE
	{
		name = JSILabel
		
		transformName = TextTopObj
		alignment = Left
		anchor = UpperLeft
		fontName = InconsolataCyr
		fontSize = 0.012
		zeroColor = 255,255,255,255
		refreshRate = 10
		labelText = FUEL CELL
	}
  	
	
 	MODULE
	{
		name = JSIVariableLabel
		transformName = TextPlateTopObj
		fontSize = 0.008
		variableName = CUSTOM_ALCOR_POWEROFF
		positiveColor = 50,50,50,255    // 333333
		negativeColor = 255,0,0,255     // ff0000
		zeroColor = 214,211,194,255     // D6D3C2
		labelText = "       ON
	}	
	MODULE
	{
		name = JSIVariableLabel
		transformName = TextPlateBottomObj
		fontSize = 0.010
		variableName = CUSTOM_ALCOR_POWEROFF
		positiveColor = 50,50,50,255    // 333333
		negativeColor = 255,0,0,255     // ff0000
		zeroColor = 214,211,194,255     // D6D3C2
		labelText = "     OFF
	}

```
output.log
```
RPMVesselComputer: ... InconsolataCyr
```

what am I doing wrong?

**Comment by MOARdV** [comment]
> what am I doing wrong?

Nothing - you don't have the latest update.  Let me post the update (you will have to change font sizes with the update)

**Comment by MOARdV** [comment]
Okay - dev build is updated [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  You will need to change the font size (try multiplying the current size x 625 to start - `0.012` becomes `7.5`).

**Comment by Alexustas** [comment]
Nothing - you don't have the latest update.

Ah, ok ))

**Comment by Alexustas** [comment]
much better, but still a little blurry

![screenshot129](https://cloud.githubusercontent.com/assets/6713671/15229385/9ef65e22-18b2-11e6-97a6-1be3d77c8b22.png)
![screenshot130](https://cloud.githubusercontent.com/assets/6713671/15229393/abec3ca0-18b2-11e6-8722-08c07cac5ed3.png)

**Comment by MOARdV** [comment]
Okay.  Let me try raising the resolution again.

**Comment by MOARdV** [comment]
Updated again.  See if this is better?

**Comment by Alexustas** [comment]
LCD symbols are quite a bit blurry, but I think this is good enough

![screenshot134](https://cloud.githubusercontent.com/assets/6713671/15229950/28c97ba0-18b5-11e6-9d4c-ca2fb8290269.png)
![screenshot133](https://cloud.githubusercontent.com/assets/6713671/15229954/2c4a22e8-18b5-11e6-96c5-2079ae6d57c8.png)

**Comment by MOARdV** [comment]
Maybe you need to zoom less close, or have bad eyes like me. :)

I can adjust it one more step better - with 64 bit, I think it is not a problem.  If I understand the configuration right, each letter has up to 32x32 pixels right now.  I can make it 64 square.

**Comment by Alexustas** [comment]
> EDIT: Or I can add a "quality" setting, so you can change it with the config file.

good idea! 
and make the default 32x32

**Comment by MOARdV** [comment]
Okay. New JSILabel parameter `fontQuality` is an integer, defaults to 32.

Updated DLL only on [DropBox](https://www.dropbox.com/s/mt21fx0wxqxo75f/RasterPropMonitor-dll-dev.0.26.1.zip?dl=0), instead of downloading all the rest of RPM that did not change.

**Comment by Alexustas** [comment]
oh yeah, I definitely like this new  JSILabel  module! 

https://youtu.be/uz8_tur3c94

my config:

```
	MODULE
	{
		name = JSILabel
		
		transformName = DigitIndicatorNameObj //DigitIndicatorAmountObj
		alignment = Right
		anchor = UpperRight
		transformOffset = 0.09,0
		fontName = Digital-7 Mono Italic
		fontSize = 13.75
		variableName = VERTSPEEDROUNDED
		positiveColor = 0,255,0,255 
		zeroColor = 255,255,0,255
		negativeColor = 255,0,0,255
		refreshRate = 10
		labelText = <=0:0.0;-0.0;"---"=>$&$VERTSPEEDROUNDED 
	}
  
	MODULE
	{
		name = JSILabel
		transformName = DigitIndicatorAmountObj
		alignment = Right
		anchor = UpperRight
		fontSize = 5
		refreshRate = 10
		labelText = <b>V/S:</b>$$$<color=silver><i>m/s</i></color>
		oneshot = true
	}

**Comment by MOARdV** [comment]
Okay.  These fonts look okay for including:
> http://www.1001fonts.com/repetition-scrolling-font.html?text=198.36%20m&size=66&fg=ffffff&bg=000000

> http://www.fontspace.com/allen-r-walden/crystal?text=-3.50&foreground=cee5f3&background=162346

> http://www.levien.com/type/myfonts/

The last one is Inconsolata from the author's page, which has some others (that are not helpful for digital displays).

I will look at adding them today.

**Comment by Alexustas** [comment]
font "Digital-7" is more preferablem, IMHO. it has monospaced version and both normal and an italic versions

**Comment by Alexustas** [comment]
I suggested font "Inconsolata" because it monospaced and it is well suited for labels on the instrument panel

**Comment by MOARdV** [comment]
One problem I find: I have to set fontSize in Unity.  If I set it to 32, then it will be too low for some things.  What size are you using for the high-quality fonts?

**Comment by Alexustas** [comment]
I have  tested only one prop so far . it's on the video above.
 and I was quite happy with the default value

**Comment by MOARdV** [comment]
Okay.  Updated on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) - need the updated rasterpropmonitor.ksp with the embedded fonts.  The names that RPM recognizes are `digital-7`, `digital-7 (mono)`, `digital-7 (italic)`, `digital-7 (mono italic)`, `InconsolataGo-Regular`, `InconsolataGo-Bold`, and `repet___` (for repetition scrolling - Unity uses the file name for the font name).  I have only looked at digital-7 so far.

**Comment by Alexustas** [comment]
It seems I  have a problem
I uninstalled Digital-7 fonts and install the new version of the RPM x.13301
I run the KSP, create a new craft and press "Launch!". everything is working fine. 

![2016-05-15 04-18-01-137](https://cloud.githubusercontent.com/assets/6713671/15270951/3052ac34-1a54-11e6-923a-8e56351b862c.jpg)

Then, I go out in the KSC and going back on the launch pad. text disappears
![2016-05-15 04-18-37-718](https://cloud.githubusercontent.com/assets/6713671/15270955/4196adba-1a54-11e6-83d5-ea84758d3b33.jpg)

 and debug message appears:

```
JSILabel: Start failed in prop 135 (Resource_Display) with exception System.NullReferenceException: 

  at (wrapper managed-to-native) UnityEngine.Font:get_material ()

  at JSI.JSILabel.Start () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)

JSILabel: Start failed in prop 141 (DigitalIndicator_JSI_Label_Test) with exception System.NullReferenceException: 

  at (wrapper managed-to-native) UnityEngine.Font:get_material ()

  at JSI.JSILabel.Start () [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 64)
```
then I restart the game, switch to craft. text returns!

**Comment by Alexustas** [comment]
and issue №2

I created in Unity gameobject exactly in the lower right corner of the LCD screen.  
![2016-05-15 04-25-30-786](https://cloud.githubusercontent.com/assets/6713671/15271001/89fbb586-1a55-11e6-9884-461ba1f8e374.jpg)

setting up a configuration as follows:

```
MODULE
	{
		name = JSILabel
		
		transformName = ScreenTextObj //DigitIndicatorAmountObj
		alignment = Left
		anchor = LowerRight
//		transformOffset = 0.09,0
		fontName = digital-7 (mono italic)
		fontSize = 12.03
		zeroColor = 255,255,0,255
		refreshRate = 10
		labelText = 12345678
		
		//labelText = <=0:######00=>$&$ MATH_RESOURCE_DISPLAY_ELECTRICCHARGE_10 
	}	
```
but the text printing lower than it should

![2016-05-15 04-18-01-137](https://cloud.githubusercontent.com/assets/6713671/15271003/988197ec-1a55-11e6-98ff-cfd172ef6371.jpg)

**Comment by Alexustas** [comment]
and now I have noticed that the label also is offset forward in the Z axis

**Comment by MOARdV** [comment]
I have an idea on the exceptions.  I will post an update maybe later tonight, or else in the morning.

I think that Digital-7 has no "descender" below the base line of the text, so I would expect it to be positioned exactly on the lower-right corner (no lower case letters like y, so the bottom of the digits are the bottom of the font).  I think maybe that font is better used with a `MiddleRight` anchor.

I will see if I can find out why the text has a z-offset.

**Comment by MOARdV** [comment]
Okay - [DLL only update](https://www.dropbox.com/s/mt21fx0wxqxo75f/RasterPropMonitor-dll-dev.0.26.1.zip?dl=0) for the exception and missing text.

**Comment by Alexustas** [comment]
> Okay - DLL only update for the exception and missing text.

Yes, all works fine now

**Comment by Alexustas** [comment]
I did a couple of experiments and found out there is no offset in Z axis, but the text is forced to render over the geometry

**Comment by Alexustas** [comment]
is it possible to use multiple JSILabel modules on one transforms? I tried to do it, but displays only one module

**Comment by MOARdV** [comment]
> is it possible to use multiple JSILabel modules on one transforms? I tried to do it, but displays only one module

I think it should work.  Except: RIght now, transformOffset moves that transform (it is bad, I know).  When I fix it so it creates a new child game object for transformOffset, it should be okay.  I think.

**Comment by MOARdV** [comment]
New update on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) - JSILabel uses a shader that checks the depth buffer (the stock shader does not), so it should not appear over other parts.  The label also creates a child transform for the text, so using transformOffset does not move the transform in the prop.

**Comment by MOARdV** [comment]
Another update on ]DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) - there is now a config option `emissive`, defaults to `true`.  Right now, it does not do anything, since I do not have the non-emissive shader working, so `emissive = false` looks the same as `emissive = true`.  When I *do* get non-emissive shaders working, everything else is ready.

**Comment by Alexustas** [comment]
and we definitely need the ability to switch between the emissive and non-emissive shaders using variable.
 or be able to control the emissive color using variable

**Comment by Alexustas** [comment]
> so it should not appear over other parts.

yes, now everything is OK

**Comment by MOARdV** [comment]
> and we definitely need the ability to switch between the emissive and non-emissive shaders using variable.

What if `emissive = toggle` tells JSILabel to switch color AND switch shaders?  So if JSILabel is using `positiveColor`, it will also use the emissive shader; if it is using `zeroColor` or `negativeColor`, it uses the diffuse shader.  If `emissive = false`, it always uses the diffuse shader.  If `emissive = true`, it always uses the emissive shader.  And, if we really need it, `emissive = reverse` uses diffuse for `positiveColor` and emissive for the other two.

**Comment by Alexustas** [comment]
sounds great!

> And, if we really need it, emissive = reverse

I thInk, yes. We ... or at least, I need it ))

**Comment by MOARdV** [comment]
If I can figure out how to get diffuse shaders to work in Unity.  Even when I use a KSP shader, it is wrong.  The normal is pointing the wrong way.  Grrr.

*If* I can get the diffuse shader to work, I think I can combine diffuse + emissive into one shader with a single variable to switch between them.  But I have to get diffuse shading to work, first.

**Comment by Alexustas** [comment]
Do you plan to add something like "Switchable Variable" option, as it is implemented in the module "JSISwitchableVariableLabel"

**Comment by MOARdV** [comment]
> Do you plan to add something like "Switchable Variable" option, as it is implemented in the module "JSISwitchableVariableLabel"

Ummm.  I do now? ))

For `emissive` parameter, I will use these names since it is not only true/false: `never` (never emissive, always diffuse), `always` (always emissive, never diffuse), `active` (emissive when using `positiveColor`, diffuse otherwise), `passive` (diffuse when using `positiveColor`, emissive otherwise).

**Comment by Alexustas** [comment]
So, I started the conversion of all the "DigitalIndicator" props. 

**new module is simply superb!**

![screenshot136](https://cloud.githubusercontent.com/assets/6713671/15426445/90440092-1eb0-11e6-8427-51ad0d2a8ce7.png)

**Comment by MOARdV** [comment]
> So, I started the conversion of all the "DigitalIndicator" props.

That looks great!  Much better than Arial.

Still no luck with the diffuse shader  I can get it where it is dim, but still glowing, or I can get it to work like the light source is in the wrong place, or like it doesn't know about some of the lights.  I am going to ask this morning on the forum to see what step I am missing.

**Comment by MOARdV** [comment]
Still working on diffuse.  I am now writing my own TextMesh class to replace Unity so that the mesh has proper normals.  I now have it partially working - I don't think it is receiving shadows, but it does seem to be responding to environmental lighting.  But I still have to write the richText support for bold, italic, and color.  And I need to make alignment and anchor features work again.

**Comment by MOARdV** [comment]
Another update on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

What works:
* Ambient / Diffuse lighting (sunlight + lights in the pod).

What does not work:
* Shadows - text is not receiving shadows, and I do not know why.  Still investigating.
* HTML markup (`<i>`, `<b>`, and `<color>`).
* Switchable variables.  I have been working on lighting, so I did not do this yet.

@Alexustas : Two questions: do you need the HTML markup?  It will take me some more time to make it work correctly.  Also, do you have a preference for `emissive` default?  I was going to make it `always`, but maybe it does not need to be.

**Comment by Alexustas** [comment]
> Two questions: do you need the HTML markup? 

**Yes, PLEASE** , and the `<size>` too, please, please, please :)

>  do you have a preference for emissive default?

For digital indicators - `always`, for switches - `active`... But I have a much much more switchers than indicators, so I think for me is more appropriate default `active`

**Comment by MOARdV** [comment]
> Yes, PLEASE , and the <size> too, please, please, please :)

Okay.  I will work on it.  It might take a while.  Color maybe easy, the others, we will see.

> For digital indicators - always, for switches - active... But I have a much much more switchers than indicators, so I think for me is more appropriate default active

Okay.  How about this: if it has `variableName` (so it can change), it will default to `active`.  If no `variableName`, it will be `always`.

**Comment by MOARdV** [comment]
One more change: the HTML tags will use `[` and `]`, like regular pages do, so that it's the same for both.

**Comment by MOARdV** [comment]
Okay, using RPM page tags made this much, much easier.

[DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) right now, only [b] [i] and [#rrggbb] or [#rrggbbaa] is supported.  If you use the color tags, it overrides any colors you use for positiveColor, zeroColor, negativeColor.  Emissive behavior is the same (so color overrides will light up the same).  I have to figure out what the [size] tag means so I can make it work.

**Comment by Alexustas** [comment]
Oh yeah!

![screenshot138](https://cloud.githubusercontent.com/assets/6713671/15517795/8dd48886-221b-11e6-8307-9a578bba7623.png)
![screenshot139](https://cloud.githubusercontent.com/assets/6713671/15517798/8ffcb4d0-221b-11e6-916b-2c4e693013f8.png)
![screenshot140](https://cloud.githubusercontent.com/assets/6713671/15517819/aa1c0c58-221b-11e6-875d-b928f0afa991.png)
![screenshot141](https://cloud.githubusercontent.com/assets/6713671/15517833/bae6b330-221b-11e6-8940-b34ed2bb3dda.png)

**Comment by MOARdV** [comment]
> Oh yeah!

It looks much better, I think. :)  Later today I'll have the variable label feature ready.

**Comment by Alexustas** [comment]
https://youtu.be/dQpYis9GvoQ

**Comment by Alexustas** [comment]
![screenshot143](https://cloud.githubusercontent.com/assets/6713671/15550237/58e05666-22d2-11e6-95df-894e7bd8ac12.png)
![screenshot142](https://cloud.githubusercontent.com/assets/6713671/15550238/593e6c74-22d2-11e6-84a4-8b3d2d0a63db.png)

**Comment by MOARdV** [comment]
Those look good.

**Comment by MOARdV** [comment]
I think, other than fixing the shader so it will receive shadows, this feature is now implemented.

**Comment by Alexustas** [comment]
if I using `labelText = <=0:0;"";"OFF"=>` and vairable become negative module stops working at all

**Comment by MOARdV** [comment]
> if I using labelText = <=0:0;"";"OFF"=> and vairable become negative module stops working at all

It should not (obviously).  I will look at it maybe later today, if I ever figure out the mess docking and undocking.

**Comment by MOARdV** [comment]
Okay.  Fixed in DLL-only [DropBox update](https://www.dropbox.com/s/colgs7nml0cujwn/RasterPropMonitor-dev.0.26.1-dll.zip?dl=0).  This also has updates to docking and undocking callbacks.  It works for me with ALCOR and Mk1-2, except the interior lights persistent is not correct (it shuts itself off).  I have an idea on that, but it is not fixed yet.

**Comment by Alexustas** [comment]
I tried to use a `fontQuality = 128` (1st screenshot) and  `fontQuality = 32`(2nd screenshot), and I do not see much difference. I'm talking about the number "250" and a lot of eights beneath
![screenshot154](https://cloud.githubusercontent.com/assets/6713671/15656815/b4b44490-26cc-11e6-8504-2bda4a8a530d.png)

![screenshot155](https://cloud.githubusercontent.com/assets/6713671/15656816/b8da6a7c-26cc-11e6-999a-e7601e9077a1.png)


Also,  I tried to use `color = 255,255,255,30`, but the text remained opaque, although should be barely noticeable transparent. Is it possible that emissiv shader ignores alpha channel and semi-transparent text can only be obtained with a diffuse shader?

**Comment by MOARdV** [comment]
I will look at the fontQuality.  Maybe I broke it.  Oh!  I remember - the included fonts do not use fontQuality, because I think Unity stores the font texture in the AssetBundle.  For system fonts, Unity loads the font and creates the texture when it loads.  Let me see if I can find a way to make the texture work correctly.

For transparency - it should work, but I did not test it, so I probably missed something controlling alpha.  I know alpha is used, since that is how the text is visible.  If alpha channel is ignored, all we will see is rectangles.  Let me see what is happening.

**Comment by MOARdV** [comment]
Transparency was a bug.  I looked at the alpha from the texture, but I ignored alpha from the color.  That is fixed.

fontQuality will take more work.  It looks like I have to set the font quality for included fonts in Unity, and I can not change it once we are in KSP.  I can increase the quality for Digital-7 in the AssetBundle, but I don't know if I can make it change at run time.

**Comment by Alexustas** [comment]
> I can increase the quality for Digital-7 in the AssetBundle,
Ok. I think it would be an acceptable solution

> but I don't know if I can make it change at run time.
Ok. not really matter

**Comment by MOARdV** [comment]
Okay, correct shader and larger fontQuality is now on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  All fonts are now 64 instead of 32.  If that is still not enough, I can raise that higher.

**Comment by Alexustas** [comment]
and another very strange thing.

![screenshot157](https://cloud.githubusercontent.com/assets/6713671/15659786/c4c32d94-26f2-11e6-85b8-3d1598477f35.png)
![screenshot159](https://cloud.githubusercontent.com/assets/6713671/15659788/c9720c16-26f2-11e6-8b0f-cf1dbed23062.png)

I switched through the tracking station to the docked test craft and that's what I saw, almost all the labels maded with  Inconsolata font are broken in the "MK1-2" pod, but at the same time everything worked perfectly in the docked ALCOR

![screenshot161](https://cloud.githubusercontent.com/assets/6713671/15659802/fb0b78ac-26f2-11e6-85a9-1b495131d906.png)
![screenshot160](https://cloud.githubusercontent.com/assets/6713671/15659805/024b5fce-26f3-11e6-90fd-d3354dd89c58.png)

All fixed after switching to KSC and back

![screenshot162](https://cloud.githubusercontent.com/assets/6713671/15659815/4156bf56-26f3-11e6-8476-790c1f356f5f.png)
![screenshot163](https://cloud.githubusercontent.com/assets/6713671/15659817/4308cd4e-26f3-11e6-82af-a7a1360fd0a2.png)

**Comment by MOARdV** [comment]
> and another very strange thing.

Ohhh.  I suspect I know what it is.  The texture atlas the font uses changed, and I am not updating it correctly.

**Comment by MOARdV** [comment]
Okay, latest strange bug is fixed.  I will update the DLL later - I want to look at the docking / undocking bug some more, first.

**Comment by Alexustas** [comment]
before you publish next update.
I have a problem (today) with updating my custom variable (CUSTOM_ and SELECT_) settings during "reload database" via MM menu. Any changes I make in config have effect only after restart of the game. 
RPM 0.26.1.27092 and MM 2.6.24/25

**Comment by MOARdV** [comment]
I will see if I can find a way to detect "reload database" and reload values.

**Comment by Alexustas** [comment]
I have never had such problems in the past ... very strange.
 always changes I made in the variables setup were applied after base roloading. till today

**Comment by MOARdV** [comment]
Something I changed, I am sure. (((

**Comment by Alexustas** [comment]
in the old "JSISwitchableVariableLabel" module had sound settings option. Can you, please, add this option in a "JSILabel" module for the "Variable Text" Mode

**Comment by MOARdV** [comment]
> The old "JSISwitchableVariableLabel" module had sound settings option. Can You, please, add this option in a "JSILabel" module for the "Variable Text" Mode

Same sound per click, or different sounds possible?

**Comment by Alexustas** [comment]
one sound will be enough, I suppose

**Comment by MOARdV** [comment]
Wait - already has sound.

`switchTransform`, `switchSound`, `switchSoundVolume` in the JSILabel config.  Is it not working?

**Comment by Alexustas** [comment]
I have not found mention of it in the wiki, and decided that this module does not have this function

**Comment by Alexustas** [comment]
I just checked and it works. sorry

**Comment by MOARdV** [comment]
> I just checked and it works. sorry

It's okay.  I forgot I added it until I checked the code, and then I worried I broke it by accident.

**Comment by Alexustas** [comment]
Yesterday I started to remake "TabloIndicator" props using the same principle that I used when creating "RetroWarningLight": customizable background color and text, implemented using the "JSILabel" module. 

![screenshot184](https://cloud.githubusercontent.com/assets/6713671/15964503/a5a3c9dc-2f3a-11e6-8410-27b19ef8ff12.png)

and everything goes just fine, except for the case when the indicator should be flashing.

Now I have this strange kind of flashing indicator - blinking background but the text is lit constantly.))
this is not very critical of course, but there is a possibility to add a flashing option (switching from the emissive to non-emissive) to the module "JSILabel" and is there any chance that the flashing text and flashing backgrounds (with same flash rates) will be synchronized??

**Comment by MOARdV** [comment]
Synchronized will be tricky.  I will see what I can do, but it will require changing configs again for flashing components, since it means changing who controls the flash.

**Comment by Alexustas** [comment]
BTW, I have a "B" plan)
I can add one more transforms into a indicator model and make two versions of the text: 

1. Emissive (always) for  "on" state, attached to a transform №1. 
2. Non-emissive text attached to transofrm №2 for "off". 

and then, in the **same** "callback" module, which animates the background, I will add one more "variableset" with "translate" mode for moving one of the transform behind background

**Comment by MOARdV** [comment]
I think my code change will be less complex. :)  And fewer polys, since you don't have to have two copies of the text.

**Comment by Alexustas** [comment]
> require changing configs again for flashing components

it may be something like

```
MODULE
{
    name = JSILabel	
    ...
    emissive = flash
    flashRate = 0.3
    ...
}
```

**Comment by MOARdV** [comment]
> it may be something like

Yes.

**Comment by MOARdV** [comment]
Okay.  Update on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

JSILabel change same as you have.

When flash is on, it changes between `positiveColor` emissive on and `negativeColor` emissive off. `zeroColor` is not used by flash.

**Comment by Alexustas** [comment]
thank you very much! I will test this feature shortly

**Comment by Alexustas** [comment]
it works as expected. 
### great job!
