### ISSUE TITLE
Variables + Multiple IVAs

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#492]
I know you busy and I know this is probably an issue that isn't fixed easily.
Basically, my cockpit shuts down (monitors/autopilot/everything)  when ever you enter a different IVA (eg. Passenger cabin) which somewhat limits it to being used for cargo planes. It also means that there my never be no smoking and fasten seat belt signs. *dramatic pause.
If it's not easily fixed then don't worry about it. I was just mentioning it just in case. :D

**Comment by MOARdV** [comment]
I guess I need a little more info on what you mean by "shuts down".  You're not in the cockpit any more, so you can't see it working until you return.  Is it still not working when you go back in?  Is this with RPM v0.24.2 / KSP 1.0.5, or are you playing with the pre-release stuff?

**Comment by DeputyLOL** [comment]
I noticed this problem quite a while ago, my work around was not to use passenger cabins.
My mod has changed somewhat since then and so has RPM so the effects are different.
I just tested it now (KSP 1.1, dev version of RPM) and got some interesting results;
What I noticed was that some switches changed positions on their own when I went to the other IVA.
Also, SAS turns itself off when I renter the cockpit, probably due to some custom variable not being what it should and making the autopilot turn off.
What I cant test is the actual autopilot system, because PA isn't compatible with 1.1 yet.

**Comment by MOARdV** [comment]
I expect persistent variables will behave better in 1.1, since I made some fairly large changes to RPM.  Persistent variables are now truly stored per vessel, so they should remember their settings when you go to a different IVA on the craft and return.  It also means the "No Smoking" and "Fasten Seat Belt" signs should work. :D

**Comment by DeputyLOL** [comment]
Brilliant, Just in case, I recorded the bug in progress: https://youtu.be/I5r9gMpXUUE
Would the no smoking signs work if the switch is in the cockpit and the lights are in the passenger cabin?

**Comment by MOARdV** [comment]
> Would the no smoking signs work if the switch is in the cockpit and the lights are in the passenger cabin?

They *should* work with the v0.25.0 dev build (0.25.0.12349).  I haven't tested the behavior, since I don't have any multi-IVA craft.

**Comment by DeputyLOL** [comment]
WOOOOO!!!!!!!!! https://youtu.be/9LkKLSmXVjk
It works a treat! Can even set the seatbelt sign to automatically turn on when below 1000 feet.
I LOVE RPM!!!!!!!

**Comment by MOARdV** [comment]
NICE!  Do you still see the cockpit shutting down, or is it remembering everything (some animations will still play when you enter an IVA - there's not much I can do about them having to reset)

**Comment by DeputyLOL** [comment]
Everything stays as it is when I leave and return, perfect! I think this is closable now, Thank you.
