### ISSUE TITLE
FAR is compatible.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#500]
Just letting you know, the KSP 1.1 version called "Jones" (where does he get these names from?!?!) is compatible with RPM 0.25 from what I can tell.

**Comment by MOARdV** [comment]
Thanks for letting me know.

**Comment by DeputyLOL** [comment]
I think you might want to change the FAR compatibility to the newest version of FAR. "Jones" has a bug that prevents module manager from reloading the database.
Newest version has fixed that and is still compatible.
