### ISSUE TITLE
Pilot Assist is compatible.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#502]
Nuf said.

On the subject of pilot assist, did you ever implement these methods?

Crzyrndm  commented on Dec 29 2015 
Some updates from the previous 24 hours that may be helpful for RPM (pending release)
•Pushed the pause toggle to a method (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L717)
•Changing the speed reference (TAS/IAS/EAS) is handled by the method ChangeSpeedRef (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L688)
•Changing the speed unit (m/s, km/h, etc.) can be handled through the method ChangeSpeedUnit (https://github.com/Crzyrndm/Pilot-Assistant/blob/master/PilotAssistant/FlightModules/PilotAssistant.cs#L711)
•Target updating now applied to GUI even if the modules are inactive (Still need to pass the value through again on activation if it's to be used)
•Fixed the speed control update not respecting the selected units.

**Comment by MOARdV** [comment]
I didn't implement those methods - I lost some data over the winter, including the PilotAssist test environment I had, and I don't have a way to test changes for it without recreating a lot of props and an IVA to put them in.  I suppose I can implement them blindly and let you see if they work :) .

**Comment by DeputyLOL** [comment]
ok, you want me to test them?

**Comment by MOARdV** [comment]
I'll have to implement them first.  If you're willing to try them out, that'd make things easier (as long as I do it right the first time :) )

**Comment by DeputyLOL** [comment]
i'd be happy to test them for you.
Its abit of a pain having to set the speed to IAS knots manually everytime you start the flight.

**Comment by DeputyLOL** [comment]
let me know when theres a build I can test.

**Comment by MOARdV** [comment]
It'll take a while - I need to get some bug fixes out, and then I need to download the source code for PilotAssist and figure out what entry points I need.
