### ISSUE TITLE
Ability to change near camera plane in JSIExternalCameraSelector

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#505]
Request by InsaneDruid on the forum.  I need to try it out to make sure it plays well with the existing implementation, but I think this is a safe change.

**Comment by MOARdV** [comment]
Easy change - Camera 00 and FX Camera have a near plane of 0.4m / far plane of 300.0m.  If I use a 8192:1 far/near ratio, I get the near plane down to 37cm, which works with the provided sample part.

**Comment by InsaneDruid** [comment]
first test done, works great (so far)!
