### ISSUE TITLE
Separate RPM and JSIAdvTransparentPods release process?

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#511]
Maybe this will settle down once we're past the initial surge of "new KSP version" tweaks, but I think RPM and JSIAdvTransparentPods need separate releases, even if they're sharing the same GitHub repo.  I don't think GitHub can manage doing separate project releases on the same repository, so maybe I need to look at a separate release process somewhere else (spacedock?).  Or create a completely new repo for JSIAdvTransparentPods.  The two plugins have completely separate code bases, so there's no techinical reason not to split them.

Any feedback?

**Comment by JPLRepo** [comment]
Let me know and I will create a new project and separate it completely.

**Comment by JPLRepo** [comment]
New Project over here:
https://github.com/JPLRepo/JSIAdvTransparentPods
