### ISSUE TITLE
KSP 1.1.1 breaks RasterPropMonitor

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#516]
Sigh.  Vessel.GetActiveResources (and its per-resource sibling Vessel.GetActiveResource) now throw exceptions, so RPM can't provide stage resource info without a significant rewrite.  Since it's a breaking change, I guess the revision goes to v0.26.0.

**Comment by MOARdV** [comment]
Turns out it's a stock bug (it affects a stock install - the stage view of the resource display is completely broken).  I may be able to hack a workaround, but I'll sit on it a day or two to see if Squad fixes the problem

**Comment by DeputyLOL** [comment]
Just a heads up, ALTITUDE and RADARALTOCEAN only read 0 since I updated to 1.1.1. I don't know if this was fixed in the new version of RPM.

**Comment by MOARdV** [comment]
@DeputyLOL - that's a side-effect of the bug in KSP 1.1.1.  Their code is causing an exception before my code updates.  You'll have to use the hotfix with KSP 1.1.1 for now.

**Comment by MOARdV** [comment]
I've got a [workaround](https://www.dropbox.com/s/5dlddbl5mtixqto/RasterPropMonitor-dev.0.26.0.zip?dl=0) that seems to handle conventional rocket configurations (LF+O engines) that should also account for electric and monoprop flow.  It's mostly untested, but it shouldn't crash.

**Comment by Alexustas** [comment]
quick testing RPM 0.26.a

![screenshot55](https://cloud.githubusercontent.com/assets/6713671/14934819/0ab272d2-0edf-11e6-8d3c-6cf984909fd1.png)

![screenshot57](https://cloud.githubusercontent.com/assets/6713671/14934823/119ea066-0edf-11e6-8944-1e578939b751.png)
![screenshot56](https://cloud.githubusercontent.com/assets/6713671/14934824/153f2d8a-0edf-11e6-8f45-7f70473093bf.png)

**Comment by MOARdV** [comment]
Now that KSP 1.1.2 is out, my work around isn't needed, although it's already implemented.  I guess RPM is ready for next time, if there is one.
