### ISSUE TITLE
REQUEST: POD>MAX<SKINTEMPERATURE

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#518]
We have a PODSKINTEMPERATURE variable but not have its MAX value. Can you please add this variable asap?

And (if it is not hard) 'Static Ambient Temperature' and 'Body Temp under craft'

**Comment by MOARdV** [comment]
PODMAXSKIN is easy.  I must have overlooked it when they added all the millions of new temperature readings. :)

Static Ambient Temperature = temperature outside the craft?  There's already EXTERNALTEMPERATURE, although I see Vessel also has "atmospheric temperature", but I haven't looked at that yet?  Body Temp under craft = surface temperature?

**Comment by Alexustas** [comment]
> Static Ambient Temperature = temperature outside the craft?

most of the time - yes, it's the same. but during re-entry this variable rises up to 6000 K or more, while the actual ambient temperature ~ 10 K 

> Body Temp under craft = surface temperature?

Yes, it seems so

**Comment by Alexustas** [comment]
![screenshot52](https://cloud.githubusercontent.com/assets/6713671/14916628/96f19adc-0e3c-11e6-9259-2567e113890d.png)

**Comment by MOARdV** [comment]
Okay.  Let me run a reentry flight test and see if I can find which variable has the ambient temp.  The rest are ready, so I'll get a dev build out this morning before I start work.

**Comment by MOARdV** [comment]
Here it is on [DropBox](https://www.dropbox.com/s/5dlddbl5mtixqto/RasterPropMonitor-dev.0.26.0.zip?dl=0)

* PODMAXSKINTEMPERATURE and PODMAXSKINTEMPERATUREKELVIN - self-explanatory
* AMBIENTTEMPERATURE and AMBIENTTEMPERATUREKELVIN - temperature outside the pod with no heating effect.
* ORBITBODYSURFACETEMP and TARGETBODYSURFACETEMP - "atmosphereTemperatureSeaLevel" from the current body.  I don't know yet what that does on a body with no atmosphere.

**Comment by Alexustas** [comment]
o! so quickly!

## Many thanks!

I will test it right now

**Comment by Alexustas** [comment]
> (in Kelvin - I can provide Celsius if needed)

yes, please

**Comment by MOARdV** [comment]
> yes, please

Okay.  Just updated. :)

ORBITBODYSURFACETEMP is in Celsius.  ORBITBODYSURFACETEMPKELVIN is in Kelvin.  Same for TargetBody.  Also, this code has a "maybe it works" stage resource workaround.  It worked for my test rocket, so maybe it works for someone else, too. :)
