### ISSUE TITLE
Shaders do not load when using -force-glcore

### ISSUE THREAD

**Issue by davv1** [Mihara/RasterPropMonitor#521]
As title says. Later I'll add SShots.

No textures are present in IVA, on RPM screens.

**Comment by MOARdV** [comment]
KSP 1.1.1 is unsupported due to a breaking bug in stock KSP.  Does the problem reproduce in 1.1.2 with RPM v0.26.0?  Does it only trigger with -force-glcore?  Please also provide logs so I can see what's going on.

**Comment by davv1** [comment]
Sorry for long respond.

![scr1](https://cloud.githubusercontent.com/assets/13569795/15065067/c4b19a98-135b-11e6-8b8e-5e6be15452b0.png)
![scr2](https://cloud.githubusercontent.com/assets/13569795/15065069/c64ae3fa-135b-11e6-86e1-1defc38f0da0.png)
And log: http://www12.zippyshare.com/v/GVXLElxC/file.html (uncompressed ksp.log)

**Comment by davv1** [comment]
It's 1.1.2 with RPM 26.0.

**Comment by davv1** [comment]
There's also modlist: http://www37.zippyshare.com/v/5c3xjphm/file.html

**Comment by davv1** [comment]
IMO -force-glcore is same as -force-opengl but it's used for Unity5 and uses newest GL software.

**Comment by MOARdV** [comment]
Okay, I can reproduce it locally.  I don't know what's going on - it looks like Unity is failing to find an OpenGL compatible shader in that mode, which does not make sense, since Linux and Mac both work, and they use OGL.

**Comment by davv1** [comment]
How things are going?

**Comment by MOARdV** [comment]
I do not see anything wrong with the shaders, and I have not been able to find a solution.  For now, RPM is not compatible with -force-glcore.

**Comment by talpadk** [comment]
Too bad that KSP 1.1.2 is so broken under Linux without -force-gl*
(even had to remove the ATI/AMD gfx card reverting to the Intel onboard to remove some graphics glitches in KSP stock)

**Comment by RichardDastardly** [comment]
Have been investigating this issue for B9-PW, we have the same problem ( well, the wings are going black under glcore32 ). Having looked around *further*, it might well be a problem with Unity because there's been a whole bunch of complaints about WebGL/iOS shaders not functioning in recent versions. I'm not sure what the earliest 5.x PartTools will run on but it might be worth trying to compile shaders under different versions.
