### ISSUE TITLE
Variables: Fuel Flow rate for engines

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#522]
It's more of a "cool detail" than functionally useful in KSP, but it's easy to compute.  It's another way of representing `THROTTLE` with specific units.

Add variables that report the max fuel consumption and current fuel consumption in grams/second (computing specific fuel consumption, and applying that to max and current thrust settings) for engines.

I can compute it for RCS as well, but the current fuel consumption may be twitchy enough that it's not helpful if someone is tapping RCS thrusters repeatedly.

**Comment by MOARdV** [comment]
I'll skip RCS - it's not quite as straightforward, and I don't want to spend a huge amount of time on a marginal piece of data.

**Comment by DeputyLOL** [comment]
Do you think you could combine this with JSIEngineMonitor when that has been completed?

**Comment by MOARdV** [comment]
> Do you think you could combine this with JSIEngineMonitor when that has been completed?

Per-engine fuel flow will be easy.
