### ISSUE TITLE
REQ: "RECOVER VESSEL" action handler

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#525]
this can be done?

**Comment by MOARdV** [comment]
What would it do?

**Comment by Alexustas** [comment]
is a button which initiates a rescue operation

the same as it is here
![screenshot114](https://cloud.githubusercontent.com/assets/6713671/15181158/6f4096c2-17a7-11e6-8a56-2d074bd30169.png)

but Prop

**Comment by MOARdV** [comment]
Okay.  I will see if I can do that.  I know I can add "Is Recoverable" query.

**Comment by MOARdV** [comment]
So I don't lose my notes: Vessel.isRecoverable looks like it will be the "can I recover" query.  Still looking for the "Recover this vessel" command.

**Comment by MOARdV** [comment]
This was easy, once I learned a little bit about Unity.  It will be in the next test drop for the undocking bug (tomorrow, my time).
