### ISSUE TITLE
JSI Config Error.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#527]
Every time I load my craft, i get an INITIALISATION ERROR on my screen. Here is the part of the log.

[ERR 19:47:22.620] JSIActionGroupSwitch: INITIALIZATION ERROR, CHECK CONFIGURATION.
[EXC 19:47:22.627] IndexOutOfRangeException: Array index is out of range.
	JSI.JSIActionGroupSwitch.Start ()

The thing is that everything still works and I can't find the troublesome prop. There is no mention of a bad prop in the log and I haven't added any more props recently.

**Comment by MOARdV** [comment]
I just updated the dev build on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) so the prop ID and name are listed in the exception.  Hopefully, that helps narrow it down so we can figure out why it is complaining.

**Comment by DeputyLOL** [comment]
Thank you.

**Comment by DeputyLOL** [comment]
Ok, I found the problem prop. It was the autopilot speed dial.
[LOG 09:16:47.477] JSIActionGroupSwitch: Warning, neither color nor animation are defined in prop MCP_SpeedDial #51 (this may be okay).
[LOG 09:16:47.483] JSIActionGroupSwitch: Configuration complete in prop 51 (MCP_SpeedDial).
[ERR 09:16:47.493] JSIActionGroupSwitch: Exception configuring prop 51 (MCP_SpeedDial): System.IndexOutOfRangeException: Array index is out of range.
  at JSI.JSIActionGroupSwitch.Start () [0x00000] in <filename unknown>:0 
[ERR 09:16:47.499] JSIActionGroupSwitch: INITIALIZATION ERROR, CHECK CONFIGURATION.
[LOG 09:16:47.506] JSIVariableAnimator: Configuration complete in prop 51 (MCP_SpeedDial), supporting 2 variable indicators.

Yay! Now what is confusing me is that I haven't touched the config for this in a long time and it has been working fine up until now. I did more testing and discovered the exact problem but not how to fix it.

This is part of the config for the dial.

 	MODULE
	{
		name = JSIActionGroupSwitch
		switchTransform = DialColliderPlus
		actionName = transfer
		masterVariableName = CUSTOM_AUTOT_SPEED
		masterVariableRange = 0.5, 1.5
		momentarySwitch = true
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleSpeed
		    perPodPersistenceName = MCP_SpeedInput
		}
	}

	MODULE
	{
		name = JSIActionGroupSwitch
		switchTransform = DialColliderMinus
		actionName = transfer
		masterVariableName = CUSTOM_AUTOT_SPEED
		masterVariableRange = 0.5, 1.5
		momentarySwitch = true
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleSpeed
		    perPodPersistenceName = MCP_SpeedInput
		}
	}

The purpose of this is to automatically transfer the speed to Pilot Assistant when I change the dial. The thing that is confusing me is that the top one works, so when I increase the speed it is automatically sent to Pilot Assistant when I release my mouse. But..... the bottom one doesn't work and as far as I can tell there is no reason why it shouldn't work. The only thing that is different is the collider name and I've triple checked it. Any ideas?

**Comment by MOARdV** [comment]
I do not see anything in the config or in the code that will explain it.  The only places I see plain arrays are for interior lights and for animations, and you are not using either of them in that config.  I will stick that config in one of my props and see if it will reproduce for me.  Do you have anything else on that collider (like JSINumericInput)?

**Comment by DeputyLOL** [comment]
Yeah. Here is the full config:

// MCP Speed

PROP
{
  name = MCP_SpeedDial
  
// switcher status
  
MODULE
{
    name = JSINumericInput
    perPodPersistenceName = MCP_SpeedInput
    defaultValue = 210
    stepSize = 1
    minValue = 0
    maxValue = 500
    reverse = false

    //loopInput = true

    USERINPUTSET
    {
		switchTransform = DialColliderPlus
		incrementCurve
		{
			key = 0 1
			key = 1 20
			key = 3 100
		}
		
		switchSound = AdvancedCockpit/Sounds/NID02
		switchSoundVolume = 0.5
    }
	USERINPUTSET
    {
		switchTransform = DialColliderMinus
		incrementCurve
		{
			key = 0 -1
			key = 1 -20
			key = 3 -100
		}
		switchSound = AdvancedCockpit/Sounds/NID02
		switchSoundVolume = 0.5
    }
}
 
 	MODULE
	{
		name = JSIActionGroupSwitch
		switchTransform = DialColliderPlus
		actionName = transfer
		masterVariableName = CUSTOM_AUTOT_SPEED
		masterVariableRange = 0.5, 1.5
		momentarySwitch = true
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleSpeed
		    perPodPersistenceName = MCP_SpeedInput
		}
	}

	MODULE
	{
		name = JSIActionGroupSwitch
		switchTransform = DialColliderMinus
		actionName = transfer
		masterVariableName = CUSTOM_AUTOT_SPEED
		masterVariableRange = 0.5, 1.5
		momentarySwitch = true
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleSpeed
		    perPodPersistenceName = MCP_SpeedInput
		}
	}

// knob rotation animation
	
	MODULE
	{
		name = JSIVariableAnimator
		refreshRate = 2
		
		VARIABLESET	
		{		
			controlledTransform  = KnobGrp
			localRotationStart = 0,0,0 
			localRotationEnd  = 0,0,100000000
			variableName = PERSISTENT_MCP_SpeedInput
			scale = 0,25000000
			longPath = yes
			//maxRateChange = 1.0
		}
		VARIABLESET	
		{	
			animationName = NID_nb_PictSwitchAnim
			variableName = 0 // 0 - clear top, 1 - Arrow, 2 - Course icon, 3 - Dash mark, 4 - Heading icon, 5 - Point mark, 6 - wide arrow
			scale = 0,7
		}

	}

**Comment by DeputyLOL** [comment]
wait.... missing bracket.... sorry....
I don't recall changing the config for this prop so my thoughts are;
1. The bracket disappeared on its own.
2. The bracket was never there and the prop worked perfectly up until now.
3. I deleted the bracket and then completely forgot about it.....

**Comment by DeputyLOL** [comment]
Thinking about it though, recently something snapped and a bunch of mods are misbehaving.
Namely TweakScale and FAR. They worked perfectly before and suddenly now there is a problem with them. I updated FAR and TweakScale and now my plane is super glued to the runway, it wont move at all. If i use hyper edit to teleport it into the air, the plane becomes a particle accelerator and rips itself apart.

I know that there have always been issues with these mods but they were working fine up until now. Maybe whatever caused them to snap caused RPM to change as well... who knows.
As of writing this, the analogue HSI from Navutilities is beige with no textures. Again, something that has never happened before....

**Comment by MOARdV** [comment]
Yeah, that sounds like something in the installation has gone bad.  I know TweakScale has caused issues before with other mods.  I have never used it, so I don't have any experience with it.

**Comment by DeputyLOL** [comment]
What about the bug with the prop. As I recall it started before I updated those mods. Things had been working fine and then suddenly they weren't.

Even with the bracket added, the prop still complains and now the NavUtilites prop has no texture.
I did not touch that prop.

**Comment by MOARdV** [comment]
I don't know what's going on with those.  The props haven't changed and Raster Prop Monitor doesn't exist in Unity, so it has to be something inherent to the models.  I can look at the stock prop configs to see if there's some clue in them, but that's about the extent of what I can do.

**Comment by DeputyLOL** [comment]
I found out what was causing all the errors. The ASET prop dev build. I have no idea why but having that in my game data folder was just causing more and more things to break. I deleted the ASET folder and now there are no more errors.

My thought is that there were some props with the same name in the ASET folder? What do you think?

**Comment by MOARdV** [comment]
If you included any of the props alexustas developed for your B737 in another folder, you might want to check on that.  I've been able to remove most of the props I added for FlightSystemsRedux, since they're in the dev builds.  Also make sure you delete the ASET directory, don't unzip the dev build over an existing installation.  That can cause problems (although, again, if you've got props of your own in those directories, you'll want to make sure you back them up, just in case).

I haven't seen any problems with config errors, myself.  I was using MODEL {} nodes for the props I added, so all I had to do with the dev builds is change where the MODEL node was configured.

**Comment by DeputyLOL** [comment]
Since everything works now, I think you can close this. Thanks for the help.

**Comment by Alexustas** [comment]
I ask here, in order not to create a new topic

@MOARdV 
Does the the number of colliders (in internal) impact on performance? I mean colliders in props

**Comment by MOARdV** [comment]
@Alexustas  - I think it does.  I do not know how much impact, though.  Or if the impact only happens if there is a module attached to the collider (like JSIActionGroupSwitch).

I have not seen big performance problems with the new RPM + Unity 5 + changes to props to use JSICallbackAnimator.  With KSP 1.0.5, sometimes I would see the MET clock on the UI flash yellow because of lag, but I have not seen that with KSP 1.1 and updated mods.
