### ISSUE TITLE
Add option to EVA from Crew window

### ISSUE THREAD

**Issue by Gotbread** [Mihara/RasterPropMonitor#530]
Currently, to go on EVA you have to enable the GUI and click in the EVA button, which removes some of the immersion. Since the Crew page does not use buttons, maybe add the option to scroll through the crew with up and down arrows and send a selected kerbal on EVA.

**Comment by MOARdV** [comment]
The crew page can't take inputs, because it is a passive display.  Making it active would be a major undertaking.  However, the "target" menu could support triggering EVA.
