### ISSUE TITLE
REQ: color global presets and per-part color overrides

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#532]
I would be difficult to describe my thoughts in English, but I'll try.
What do you think about adding the ability to use not only a direct description of the color (eg 255,200,150,255) in the prop config but something like a meta-variable (or presets). 

how it should be work.

First I create a global configuration file with default presets for colors, such as:

```
RPM_GLOBALCOLORSETUP
{
   COLORDEFINITION
   {
      name = ASET_BackLightColor
      color= 210,220.250,255
   }

   COLORDEFINITION
   {
      name = ASET_ActiveButtonColor
      color= 80,150,160, 255
   }

   COLORDEFINITION
   {
      name = ASET_TextLabelColor
      color= 180,190,170,255
   }

etc . . .
}
```

then I write in my config:

```
...

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Left
		anchor = UpperLeft
		fontName = InconsolataGo
		fontSize = 4
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
	>>>  positiveColor = COLOR_ASET_BackLightColor
		zeroColor = 255,255,0,255
		negativeColor = 255,0,0,255
		labelText = LIGHTS
	}

...
```
Further, in the configuration of Part (eg MK1-cockpit) in the module **RasterPropMonitorComputer {}** I add a block:
```
RPM_COLOROVERRIDE
{
   COLORDEFINITION
   {
      name = ASET_BackLightColor
      color= 110,140,250, 255
   }
}
```   

so my instruments in aircraft cockpit will glow green. 

For the LanderCan internaI I will make a different settings, and voilà!  The same instruments are illuminated with warm white light

**Comment by MOARdV** [comment]
You don't like having to copy and paste the same numbers over and over and over again, and then make new props for different color lights? And then have to edit hundreds of configs if you want to change the color?  :)

This will be a big change so it will work for JSILabel, JSIVariableAnimator, JSIVariableLabel, JSISwitchableVariableLabel, JSIActionGroupSwitch, and JSICallbackAnimator (did I forget anyone?).  But, if I am going to make it work, it should work everywhere.

**Comment by Alexustas** [comment]
the main goal - the opportunity to get different look of props in different interiors, without creating more and more copies of the same props

**Comment by MOARdV** [comment]
I have the new named color code working, and JSILabel can use it.  On [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  May be bugs - I did a very simple test.

Configs like you described.  Can have more than one `RPM_GLOBALCOLORSETUP` in global config files, and `RPM_COLOROVERRIDE` in the RasterPropMonitorComputer module.  If the same color name is seen more than once in the same place, the last one that is parsed is kept.

I will add documentation and support more RPM modules later today (need to get back to work :) ).

**Comment by MOARdV** [comment]
EDIT: The other prop color animators are updated. JSIVariableAnimator, JSIVariableLabel, JSISwitchableVariableLabel, JSIActionGroupSwitch, JSICallbackAnimator, and JSILabel all can use named COLOR_.

**Comment by Alexustas** [comment]
wow! your speed is simply amazing!

**Comment by MOARdV** [comment]
> wow! your speed is simply amazing!

This was easy.  Or I made some mistakes.  Or maybe both of those. :)

**Comment by Alexustas** [comment]
Only thing that worries me, how it will work with the docked spacecraft

**Comment by Alexustas** [comment]
hmmm... it's not work for me. (RPM 0.26.1.25028)


that's how it was before the last update

![screenshot143](https://cloud.githubusercontent.com/assets/6713671/15556999/8458a27e-22f2-11e6-968e-b1cb8a3ff174.png)


So, what I did:

1. I created a file AsetDefaultColors.cfg
```
RPM_GLOBALCOLORSETUP
{
   COLORDEFINITION
   {
      name = ASET_BACKLIGHTCOLOR
      color = 255,0,0,255
   }
}
```
clear red color

2. I edited config of "SAS" switcher
```
...
// labels


// NAME

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = LowerCenter
		lineSpacing  = 0.3
		transformOffset = 0.026,-0.012
		fontName = Arial
		fontSize = 6.5
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
		positiveColor = 150,170,195,255
		zeroColor = 255,255,255,255
		negativeColor = 255,0,0,255
		labelText = ┌────┐$$$└────┘
	}
	
// NAME

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = LowerCenter
		lineSpacing  = 0.3
		transformOffset = 0.026,-0.007
		fontName = Arial
		fontSize = 6.5
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
		positiveColor = COLOR_ASET_BACKLIGHTCOLOR
		zeroColor = 255,255,255,255
		negativeColor = 255,0,0,255
		labelText = [b]SAS[/b]
	}
	
// ON / OFF

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = UpperCenter
		lineSpacing  = 1.5
		transformOffset = 0.026,-0.010
		fontName = Arial
		fontSize = 4.6
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
		positiveColor = 255,255,255,255
		zeroColor = 255,255,255,255
		negativeColor = 255,0,0,255
		labelText = [b]ON$$$ $$$ $$$ $$$ $$$ $$$ $$$ $$$OFF[/b]
	}
	
// LEDS "ON "

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = LowerCenter
		lineSpacing  = 0.6
		transformOffset = 0.026,-0.017
		fontName = Arial
		fontSize = 3.5
		fontQuality = 64
		variableName = CUSTOM_ALCOR_SAS_ON
		emissive = active 
		positiveColor = 0,255,0,255
		zeroColor = 50,50,50,255
		negativeColor = 255,0,0,255
		labelText = ▒             ▒ 
	}
```
and that's what happened

![screenshot149](https://cloud.githubusercontent.com/assets/6713671/15557353/497f278e-22f4-11e6-81de-397dc944707d.png)

"SAS" label should be the same color as the "RCS" (for "RCS" i'm using direct color coding `positiveColor = 255,0,0,255`)

and also I see that broke all the text formatting

**Comment by Alexustas** [comment]
EDIT. 
color corrected after game restart. I probably missed something. sorry

![screenshot150](https://cloud.githubusercontent.com/assets/6713671/15557710/a757a8de-22f6-11e6-9a1b-bf0104979d27.png)


 But text formatting is still broken

**Comment by Alexustas** [comment]
> color corrected after game restart. I probably missed something

I think I understand. "RPM_GLOBALCOLORSETUP" changes are not applied when you reload database via MM

**Comment by MOARdV** [comment]
> I think I understand. "RPM_GLOBALCOLORSETUP" changes are not applied when you reload database via MM

Yes, I don't know how to make everything work with MM reload, sorry.  I will see if I can find a way to support that.  I will also investigate text formatting.  That is not expected.

**Comment by Alexustas** [comment]
> I don't know how to make everything work with MM reload, sorry. 

it's not such a big issue

about formatting

before

![screenshot153](https://cloud.githubusercontent.com/assets/6713671/15558142/b5223774-22f9-11e6-882c-131e21775673.png)

after apdate

![screenshot151](https://cloud.githubusercontent.com/assets/6713671/15558147/bf0d3bb2-22f9-11e6-85d2-f1e41d1bcccc.png)

**Comment by Alexustas** [comment]
config:

```
// labels

// NAME

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = LowerCenter
		lineSpacing  = 0.3
		transformOffset = 0.026,-0.011
		fontName = Arial
		fontSize = 6.5
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
		positiveColor =COLOR_ASET_BACKLIGHTCOLOR
		zeroColor = 255,255,255,255
		negativeColor = 255,0,0,255
		labelText = LIGHTS
	}
	
// ON / OFF

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = UpperCenter
		lineSpacing  = 1.5
		transformOffset = 0.026,-0.010
		fontName = Arial
		fontSize = 4.6
		fontQuality = 64
		variableName = CUSTOM_ALCOR_BACKLIGHT_ON
		emissive = active 
		positiveColor = 255,255,255,255
		zeroColor = 255,255,255,255
		negativeColor = 255,0,0,255
		labelText = [b]ON$$$ $$$ $$$ $$$ $$$ $$$ $$$ $$$OFF[/b]
	}
// LEDS "ON "

MODULE
	{
		name = JSILabel		
		transformName = TextTopObj
		alignment = Center
		anchor = LowerCenter
		lineSpacing  = 0.6
		transformOffset = 0.026,-0.017
		fontName = Arial
		fontSize = 3.5
		variableName = CUSTOM_ALCOR_LIGHTS_ON
		emissive = active 
		positiveColor = 0,255,0,255
		zeroColor = 50,50,50,255
		negativeColor = 255,0,0,255
		labelText = ▒             ▒ 
	}

**Comment by MOARdV** [comment]
It is this:
```
 lineSpacing  = 0.6
```
That means "Use 0.6 x normal line spacing".  Remove that and see how it looks.

**Comment by Alexustas** [comment]
and [output.log](https://www.dropbox.com/s/xfnd8gcj5texsxf/output_log.txt?dl=0)

**Comment by MOARdV** [comment]
`lineSpacing` is multiplied by the default line-to-line spacing.  I did not explain that in the wiki.

**Comment by Alexustas** [comment]
I think I understand. before update this setting does not seem to work at all. I played with these settings and did not notice significant changes. And after update the setting start work)) so I thought it was all broken.

**Comment by MOARdV** [comment]
> I think I understand. before update this setting does not seem to work at all.

Yes, exactly.  I forgot to use that variable when I first wrote it.  Now it is working.

**Comment by Alexustas** [comment]
I removed all the "lineSpacing" lines 

 and that's what I got

![screenshot153](https://cloud.githubusercontent.com/assets/6713671/15558582/ce79e5d4-22fc-11e6-95f7-130c404e558c.png)

### thank you so much for your help

**Comment by Alexustas** [comment]
JSICallbackAnimator is  also work ok with COLOR_ variable
