### ISSUE TITLE
NRE when entering editor

### ISSUE THREAD

**Issue by Galenmacil** [Mihara/RasterPropMonitor#533]
This sometimes shows up in the log when entering editor:

_[EXC 00:45:56.201] NullReferenceException: Object reference not set to an instance of an object
	JSI.RPMVesselComputer.onVesselWasModified (.Vessel v)
	EventData`1[Vessel].Fire (.Vessel data)
	RemoteTech.Modules.ModuleRTAntenna.AddTransmitter ()
	RemoteTech.Modules.ModuleRTAntenna.SetState (Boolean state)
	RemoteTech.Modules.ModuleRTAntenna.OnStart (StartState state)
	Part.ModulesOnStart ()
	Part+<Start>c__Iterator25.MoveNext ()_

**Comment by MOARdV** [comment]
> This sometimes shows up in the log when entering editor:

Can you please provide a complete log where this occurs?  This exception by itself is insufficient context.

**Comment by MOARdV** [comment]
No additional information, and not reproducible with my installation.  Closing.
