### ISSUE TITLE
JSILabel does not receive shadows

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#535]
Only an issue for non-emissive text.  Opening as a separate issue since JSILabel is feature complete and implemented, other than this shader / material configuration problem.

**Comment by MOARdV** [comment]
While I'm in there, take a look at generating mipmaps and turning on filtering for the texture fonts, since there's some pretty bad aliasing with small fonts.

**Comment by Alexustas** [comment]
I was just going to ask you about this ))

**Comment by MOARdV** [comment]
I don't understand why, yet.  I set the material to receive shadows, but it does not seem to change.

**Comment by MOARdV** [comment]
Mipmaps will require more work.  The Font class does not generate mipmaps, and it marks the texture unreadable, so I will have to do something extra to extract a mipmap.

**Comment by MOARdV** [comment]
Shadow receiving is going to be a problem.  Unity requires geometry to be in the geometry queue to receive shadows.  JSITextMesh was in the Transparent queue. Putting JSITextMesh in the geometry queue causes the text to cut holes in the IVA panel when part of the prop is not behind it (so, ASET small plate is okay, but text for 3 pos. toggle switch is not okay, because the text does not have part of the prop behind it).

I also tried using alpha cutoff for the shader, and that will work, but it will cause the text to be blocky, since there is not smooth alpha blend.

**Comment by MOARdV** [comment]
Actually, using an a = 0.35 looks okay.  The default a = 0.5 did not.

**Comment by Alexustas** [comment]
![screenshot190](https://cloud.githubusercontent.com/assets/6713671/16020882/cd494270-31d1-11e6-95f1-7bc30ca305b6.png)
![screenshot191](https://cloud.githubusercontent.com/assets/6713671/16020881/cd181a24-31d1-11e6-9543-2ec398121d50.png)
![Uploading screenshot188.png…]()

**Comment by Alexustas** [comment]
![screenshot188](https://cloud.githubusercontent.com/assets/6713671/16020952/06395836-31d2-11e6-8007-8bb9efdd2def.png)

**Comment by MOARdV** [comment]
@Alexustas - Do you think text quality is okay?

**Comment by Alexustas** [comment]
I think, yes
at least, I did not notice any visual artifacts
