### ISSUE TITLE
Request. Electricity production variables

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#540]
Can we get the variables for the production of energy through fuel cells, solar panels and alternator?

**Comment by MOARdV** [comment]
I would like to (along with fuel cell consumption rates in game units + mass).  It will take some effort, which is why I didn't do it yet. :)

You want different variables for each, correct? (like ELECTRICITY_FUELCELL, ELECTRICITY_SOLARCELL, only with a better name)

**Comment by Alexustas** [comment]
> You want different variables for each
Yes, I want to track all possible energy sources

**Comment by MOARdV** [comment]
`ELECOUTPUTALTERNATOR` and `ELECOUTPUTGENERATOR` both work.  There is `ELECOUTPUTFUELCELL` for ModuleResourceConverter, but I have not found the right variables for it to work.  I still need to create `ELECOUTPUTSOLAR`.

**Comment by Alexustas** [comment]
variable "ELECOUTPUTFUELCELL" always shows zero, regardless of whether the fuel cell is turned on or not

**Comment by MOARdV** [comment]
Yes.  I have not figured out how to compute energy production yet for it, but I added the variable.

**Comment by Alexustas** [comment]
these variables are measured in the unit/s ?

**Comment by MOARdV** [comment]
Yes.  They measure what the part reports, so if batteries are full, they will still report power generation, unless the part stops producing power (like fuel cells).

**Comment by Alexustas** [comment]
can you make so that the variable returns "-1" if the vessel does not have such devices on board?

**Comment by MOARdV** [comment]
> can you make so that the variables returns "-1" if the vessel does not have such devices on board?

Yes.

**Comment by MOARdV** [comment]
On [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0) now.

**Comment by Alexustas** [comment]
perhaps it is not quite the correct topic, but I do not want to open a new issue.

I made a new switch for deploy / retract solar panels and recorded video how it works in the game.

[VIDEO](https://youtu.be/R5tgqxITbmQ)

config:

```
PROP
{
  name = swTumble_SOLAR_DEPLOY
 
// action

	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = SwitchTumbleAnim
		switchTransform = SwitchColider
		actionName = plugin
		switchSound = ASET/ASET_Props/Sounds/tumbleClick01
		PLUGINACTION
		{
			name = JSIInternalRPMButtons
			actionMethod = SetDeploySolarPanels
			stateMethod = GetDeploySolarPanels  
		}
	}
```

**Comment by MOARdV** [comment]
Yes, this is difficult because the solar panel animation takes time, and GetDeploySolarPanels can only have two values (true / false), so I can use "Solar Panels can be extended", which is what I am using, or I can use "Solar Panels can be retracted", which will make the switch take a long time going from "off" to "on".

Maybe I can change it to "can be extended or is now retracting", which will make it flip immediately.

**Comment by MOARdV** [comment]
I changed GetDeploySolarPanels, so I think it will behave better.

I also added JSIInternalRPMButtons `SolarPanelsState`.  Returns deployable solar panel state:

* -1 = no deployable solar panels
* 0 = retracted
* 1 = extended
* 2 = retracting
* 3 = extending
* 4 = broken

Updated on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by Alexustas** [comment]
> I also added JSIInternalRPMButtons

oh! it's just wonderful!

**Comment by MOARdV** [comment]
Update again, now have PERIODRANDOM_#
