### ISSUE TITLE
Request. Air flow variable

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#541]
IntakeAir  resource is now useless. so can we get a variable for air flow?

**Comment by MOARdV** [comment]
I will look for one.

**Comment by MOARdV** [comment]
Airflow in Units, or Airflow in g/s?  (Or m^3 / s?).  I plan on g/s.  (you saw I have fuel flow in g/s as a variable, too?)

**Comment by MOARdV** [comment]
Actually, airflow at the intakes is a very large number.  The stock Aeris-3 has an airflow of 17.3U while it sits on the runway idle.  If I convert that to g/s, it is 86580 g/s.  I can get that value over 200U at low altitude (1.5km), which is over 1T/s.  Is this going to be okay?

**Comment by Alexustas** [comment]
I plan to use for this [gauge ](https://cloud.githubusercontent.com/assets/12616126/15322558/81965ad6-1c35-11e6-9f90-6a9a5cb2b4fe.png) with two hands and two scales, which requested DepyutiLOL. Of course I'll do other grading of scales. so it can display very large range of values

**Comment by MOARdV** [comment]
If you want to test it, [DLL-only Dropbox](https://www.dropbox.com/s/4npk8dyekmgvvli/RasterPropMonitor-dev0.26.1-dll.zip?dl=0) adds `CURRENTINTAKEAIRFLOW` in g/s.

**Comment by Alexustas** [comment]
correct, please, the name of the variable in the [wiki](https://github.com/Mihara/RasterPropMonitor/wiki/Defined-variables#thrust-and-related-parameters)

**Comment by MOARdV** [comment]
name fixed.
