### ISSUE TITLE
Enable/Disable HUD bars is performance heavy.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#547]
I recently started getting lag spikes in my cockpit and decided to switch my attention to performance. This was really overdue. My cockpit basically switches from 'slow mode' to 'fast mode' every 
I used the RPM config to show the variable updates and I noticed something weird:
**RPMVesselComputer: CUSTOM_ALTITUDEMARKER queried 5864 times 1.6 calls/FixedUpdate**
**RPMVesselComputer: CUSTOM_RADARALT queried 6292 times 1.7 calls/FixedUpdate**
RPMVesselComputer: PERSISTENT_AUTOPILOT_CMD queried 6314 times 1.8 calls/FixedUpdate
**RPMVesselComputer: CUSTOM_PFDOVERSPEEDBAR queried 7208 times 2.0 calls/FixedUpdate
RPMVesselComputer: CUSTOM_PFDSTALLBAR queried 7804 times 2.2 calls/FixedUpdate**
RPMVesselComputer: CUSTOM_AUTOP_VORLOC queried 8622 times 2.4 calls/FixedUpdate
RPMVesselComputer: CUSTOM_STATE_GROUND queried 8990 times 2.5 calls/FixedUpdate
RPMVesselComputer: SYSR_ELECTRICCHARGE queried 9015 times 2.5 calls/FixedUpdate
RPMVesselComputer: CUSTOM_SYSTEMPOWER queried 9676 times 2.7 calls/FixedUpdate
RPMVesselComputer: MATH_VERTSPEED_FEETPERMIN queried 9985 times 2.8 calls/FixedUpdate
RPMVesselComputer: CUSTOM_SYSTEM1 queried 10710 times 3.0 calls/FixedUpdate
**RPMVesselComputer: GEAR queried 11525 times 3.2 calls/FixedUpdate**
**RPMVesselComputer: CUSTOM_PFD_VERTSPEED_FAIL queried 12392 times 3.4 calls/FixedUpdate**
RPMVesselComputer: MATH_ALTITUDE_FEET queried 13081 times 3.6 calls/FixedUpdate
RPMVesselComputer: CUSTOM_BACKLIGHTBRIGHT queried 13280 times 3.7 calls/FixedUpdate
RPMVesselComputer: CUSTOM_POWERTOGGLE queried 16112 times 4.5 calls/FixedUpdate
**RPMVesselComputer: MATH_RADARALTOCEAN_FEET queried 16485 times 4.6 calls/FixedUpdate**
**RPMVesselComputer: PLUGIN_JSIFAR:GetFlapSetting queried 19438 times 5.4 calls/FixedUpdate**
**RPMVesselComputer: CUSTOM_PFD_SPEEDFAIL queried 30760 times 8.5 calls/FixedUpdate**
**RPMVesselComputer: CUSTOM_ALTBARFAIL queried 32112 times 8.9 calls/FixedUpdate**
RPMVesselComputer: MATH_AIRSPEED_KNOTS queried 41465 times 11.5 calls/FixedUpdate

All the variables in bold control the enabling and disabling of certain vertical and horizontal bars for the HUD. What's weird is that the variables that actually control the bars (except for MATH_AIRSPEED_KNOTS) are less heavy than the simply custom variables that toggles the bar on and off. 

Let me know what you think.

**Comment by MOARdV** [comment]
I think that's a lot of queries. :)

I'm glad you found that feature in RPM.  It provides a lot of insight into what may be causing lag in IVA.  As far as a solution, I'll need to do some digging.  I've started adding callback functionality where the master computer tells a prop "this changed, here is the new value" instead of the prop asking every update "what's this value now?", and this may be another place where it makes sense to do so.

**Comment by MOARdV** [comment]
As a follow-on question - do the enabling variables tend to be discrete (like GEAR, that's on or off, and not changing a lot), or continuous (like, I would assume, MATH_RADARALTOCEAN_FEET).  And are they used on multiple displays?  The callback mechanism works best for discrete variables that are used in many places, although continuous variables can benefit, too.

I should see if there are ways to improve CUSTOM, SELECT, and MATH performance, too.  That might require something more radical.

**Comment by DeputyLOL** [comment]
The airspeed one is laggy as quite a few of the planes systems are linked to this.
As for the discrete or continuous question. Most of the variables that the bars use are discrete but most of those discrete variables contain a continuous variable. 
As for the multiple displays, yes and removing one had a huge impact on performance. Before I had 2 seperate PFDs (Captain and First Officer) with all the bars on both of them. They game would run smoothly for about 15 seconds and then slow to crawl for about 15 seconds and then repeat forever. I haven't found anything that causes or stops it, it just starts on its own. I thought it might have been a different mod as the lag continued even when not it IVA. I removed the FOs PFD and gave him a CAPs PFD. The lag spikes still exsist but they don't slow down to a crawl, more like a walk. They also don't seem to last as long.
I'm also in the process of converting all my props to use JSICallbackAnimation and JSILable as they have lower overheads. If the JSICallbackAnimation allows for alarm sounds than I could use it for almost everything. :D

Hope this helps.

**Comment by MOARdV** [comment]
Yes, it helps.  You *definitely* want to use JSICallbackAnimation for anything like backlights or other situations where the variable isn't going to change often but it's used on multiple props.  You have much lower overhead during the updates, and you get instant response to changes (like backlights switching off as soon as you hit the switch, instead of a slight delay later).

**Comment by DeputyLOL** [comment]
would it be ok to use on backlights that don't turn on and off regularly but can flicker when they experience high g forces?

**Comment by MOARdV** [comment]
> would it be ok to use on backlights that don't turn on and off regularly but can flicker when they experience high g forces?

Sure.  I think CUSTOM_ALCOR_BACKLIGHT_ON (I may have the name wrong) does that already.  By "often", I mean "every frame it changes".  Something that changes frequently only during a limited period of time won't be a problem.

**Comment by DeputyLOL** [comment]
ok thanks.

**Comment by MOARdV** [comment]
I've made a lot of changes in the last few days to improve lagginess.  I don't think RPM is entirely the problem in your case, though, because there's nothing in RPM that would turn on and off over a 15 second period.  Dev build on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by DeputyLOL** [comment]
thanks, ill let you know the results

**Comment by DeputyLOL** [comment]
I just downloaded it. there appears to be improvement, the lag spikes still exist but don't last as long.
I would tell you more but I'm currently combatting a bug that makes my camera shake and stops the autopilot working properly

**Comment by DeputyLOL** [comment]
Ok nevermind. there was a huge improvement. I just tried to record the lag to show you and realised that it wasn't lagging. It is like playing in fast motion!
This may just be because Pilot Assistant stopped working.

I noticed that you dropped the resolution for the text :P

**Comment by MOARdV** [comment]
> I noticed that you dropped the resolution for the text :P

Not intentionally.  The custom JSILabel text is at a higher resolution, but it also isn't mip-mapped, which leads to some annoying artifacts when it's small.  I'm still trying to figure out how I create new mipmapped textures without duplicating them extensively.

**Comment by DeputyLOL** [comment]
I meant text on the monitors.
In case your curious, my cockpits running a lot smoother now. There are a few lag spikes but they don't occur as often and don't last as long.
Heres a video. It shows some of the low res text and the lag spikes. I also had some music on in the background and the recording picked it up. :D
https://youtu.be/7-MMM2-4Y9I

**Comment by MOARdV** [comment]
There were no changes to the text rendering on the monitors, though.  Not since well before v0.26.0. :(

I'll get to the HUD offset Soon (TM).

**Comment by DeputyLOL** [comment]
Something changed something on the monitors cause I'm seeing some old issues reappearing. :/

![screenshot83](https://cloud.githubusercontent.com/assets/12616126/15948438/af10e736-2e98-11e6-9980-3b31375b7c22.png)

Those white lines weren't there before.

**Comment by DeputyLOL** [comment]
![screenshot84](https://cloud.githubusercontent.com/assets/12616126/15948636/cd6d0150-2e99-11e6-81b0-08599db494f8.png)
Also, if you didn't change monitor text, why is the text now really weird?

**Comment by MOARdV** [comment]
I don't have an answer for that, unless you're using ASET fonts and alexustas changed some of them.  But I am guessing at that - I really don't know why it would have changed on you.

**Comment by DeputyLOL** [comment]
It only changed when I downloaded the dev build above...

**Comment by DeputyLOL** [comment]
Actually, I just noticed that other things were low res as well so maybe its just me again.

**Comment by MOARdV** [comment]
I think I've made all of the performance improvements that can help this problem.

**Comment by DeputyLOL** [comment]
thank you
