### ISSUE TITLE
GIMBAL LOCK

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#550]
I think in the current dev-build "GIMBAL LOCK" action has broken

```
MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		switchSound = ASET/ASET_Props/Sounds/B_Button01_Click
		actionName = plugin
		PLUGINACTION
		{
			name =  JSIInternalRPMButtons
			actionMethod = GimbalLock  
			stateMethod = GimbalLockState    
		}
	}
```

**Comment by MOARdV** [comment]
You don't need to lock gimbals. :)

I will take a look at it and see what I broke.

**Comment by MOARdV** [comment]
Is actually already fixed.  Latest update on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).  This update has a lot of changes in how RPM works that may make performance a little bit better.  Hopefully not worse.
