### ISSUE TITLE
Monitor Freezes

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#551]
This has happened occasionally before but I finally got video evidence so I thought that I may as well report it. 
So I was flying quite happily when suddenly I experienced an unplanned "rapid disassembly", so on the way down I decided to record the crash unfold. 
During the dramatic plunge all the screens stopped responding except the standby one and stayed frozen until the end. Nothing popped up in the log.

Here is a link to the video (sorry about the pixilation, I have no idea why that's there)
https://youtu.be/R6DM_08EKzs

**Comment by DeputyLOL** [comment]
Also worth mentioning that when the monitors froze, performance went through the roof! :D

**Comment by MOARdV** [comment]
Is this with an official release, or one of the dev builds?  If a dev build, how recent?

**Comment by MOARdV** [comment]
Oh - and if you happen to have the log from that session, it could provide some insight.

**Comment by DeputyLOL** [comment]
It's for a dev build, I'm not too certain which one. I think I got it from the last link of the JSILable issue.
I showed the log during the video and it didn't seem to contain anything. I'll see if can still acess it.

**Comment by MOARdV** [comment]
The part in the failure that's of most interest is the time of failure when the monitors stopped working.  Regardless, having the text log will be far more valuable, since it's easier to search the entirety.

**Comment by DeputyLOL** [comment]
Here is the log.
https://www.dropbox.com/s/rc6k135nunoikyz/KSP.log?dl=0

For reference, the crash happens at [LOG 22:07:06.978]

**Comment by MOARdV** [comment]
Definitely get a newer dev build.  That was one before the major changes I did this week.  The problem you were seeing was probably similar to the undocking bug, or at least had the same underlying cause.

**Comment by DeputyLOL** [comment]
ok thanks, I just downloaded the link you put in the enable/disable HUD bars lag issue.

**Comment by DeputyLOL** [comment]
I haven't seen this bug again so I guess you can close this. I'll post here again if I see it again.

**Comment by MOARdV** [comment]
If you can get a log from a session where that happens, with the latest RPM dev build, it would be useful.
