### ISSUE TITLE
horizontally flipped image from the cameras

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#555]
a strange bug appeared (most likely since the shaders for cameras have been added)

https://youtu.be/gM_otdbfans

https://youtu.be/cn281tnZCJI

1. an image from the camera is flips horizontally in flight (first video)
2. change of the camera on one monitor results of the random change of the camera on the other
3.  as you can see on the big screen to the left, the image spontaneously flips

**Comment by MOARdV** [comment]
Using temporary render textures seems to be the culprit.  Each monitor will allocate its own separate effect rentex (until I implement a pool of textures, so I only have one per pod).
