### ISSUE TITLE
Question. A random number with very low refresh rate

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#556]
I need to get a few CASTOM_ variables that randomly changes its value every few seconds or minutes. That I need to control several fake indicators. 

How can i do this?

**Comment by MOARdV** [comment]
> How can i do this?

Wait for me to make some changes later this weekend. ))

It's a bug with the CUSTOM_ variables that they ignore RANDOM and RANDOMNORMAL caching rules, but I planned on fixing it, and I forgot to fix it sooner.

**Comment by MOARdV** [comment]
ALthough a low-frequency variable may be different.  I will have to look at how to do that.

**Comment by MOARdV** [comment]
JSIVariableAnimator with a very large refreshRate would do this for a prop.  The problem with making this work with a variable is that it would mean all variables using the random number will see the same value.  I can't make different props get different random numbers, all with a low refresh rate, without a very large amount of code work.

**Comment by MOARdV** [comment]
The CUSTOM_ caching I mentioned earlier won't be fixed - it causes a problem with variable evaluations.

**Comment by Alexustas** [comment]
> JSIVariableAnimator with a very large refreshRate would do this for a prop.

as was done previously.

```
	MODULE   
	{
		name = JSIVariableAnimator
		animationName = TabloIndicatorAnim
		variableName = CUSTOM_ALCOR_FAKEEXSUITWATER_ON
		scale = 0,1
		refreshRate = 2500
		threshold = 0.5,1.1
		reverse = true
	}
```

but I moved all indicators on "callback" rails

**Comment by MOARdV** [comment]
Okay.  I will have to think of something.  May require a new custom variable type.

**Comment by MOARdV** [comment]
I have not thought of a good way to implement this with JSICallbackAnimator.  I think I need to recommend using JSIVariableAnimator for now.  I think JSIVariableAnimator is not as bad to use now, since I have made many changes.

**Comment by Alexustas** [comment]
as I wrote earlier, I now use tandem of "JSILabel" + colored background instead of a colored texture with drawn text. "JSICallbackAnimator" is responsible for the change of color and emission of background , and "JSILabel" module creates and manages its label color and emission. This gives greater versatility and flexibility, and allows you to add (or customize) a lot of new indicators, without creating new textures or repainting.

I need a some random predefined variable  which changes its value not in every update, but every few hundred or thousand updates

**Comment by MOARdV** [comment]
Does it need to be a different number for each prop it is used? Or it is okay if every prop gets the same random value?  If all props can have the same random number, then I can make it work.  If each prop needs a different number when it updates, that is not going to work.

I will need to think about it more.

**Comment by Alexustas** [comment]
Now we have a very useful variable `PERIOD_#HZ`. if you can to make something like` RANDOM_[refresh rate]` it should completely solve my problem, I believe

**Comment by MOARdV** [comment]
> Now we have a very useful variable PERIOD_#HZ. if you can to make something like RANDOM_[refresh rate] it should completely solve my problem, I believe

I think I can make a variable like this, but it means all props will see the same random value at the same time if they use the same [refreshrate].

**Comment by Alexustas** [comment]
but I'm not going to use this variable directly in the indicator config.
I'll create a set of custom variables, for example:

```
RPM_CUSTOM_VARIABLE

	{
	  name = ALCOR_FAKEEXCABINWATER_ON
	  operator = AND

	  SOURCE_VARIABLE
	  {
		name = name_of_new_RANDOM_variable
		range = 0.1, 0.20
	  }
	  SOURCE_VARIABLE
	  {
		name = CUSTOM_ALCOR_POWEROFF
		range = -0.1, 0.1
	  }
	}
```

in  the next config, I do a little bit different range etc.

**Comment by MOARdV** [comment]
> but I'm not going to use this variable directly in the indicator config.

Okay.

**Comment by MOARdV** [comment]
`PERIODRANDOM_#`.  '#' is an integer, indicates refresh rate (update ticks) for the random number, so it will be similar to JSIVariableAnimator with a higher refresh rate.  All PERIODRANDOM with the same '#' will have the same value, and they will update at the same time.

**Comment by Alexustas** [comment]
I just tested it and it works exactly as I wanted

once again thank you very much!
