### ISSUE TITLE
JSIPilotAssistant confused throttle for horizontal autopilot

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#559]
I've been having this issue for a while now relating to the autopilot. This is the config for the SPEED button;

	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = transfer
		masterVariableName = CUSTOM_AUTOT_ON
		masterVariableRange = 0.5, 1.5
		perPodPersistenceName = AUTOT_SPEED_BUTTON
		switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		TRANSFERACTION
		{
		    name = JSIPilotAssistant
		    setMethod = SetThrottleMode
		    perPodPersistenceName = AUTOP_SPEEDMODE_2
		    stateVariable = CUSTOM_AUTOT_ON
		}
	}

Pressing the button should turn on the autothrottle (using separate trigger variables) and set the autothrottle to 'speed' mode. (BTW it would be very useful if we could just put numbers into the getVariable or perPodPersistenceName range, instead of having to make a 'dummy' JSINumericalInput)

Whenever the autothrottle speed mode is toggled, it messes with the horizontal autopilot. I finally got round to this as I thought it might be my fault, or some silly copy/paste error on my part. 

I looked at the trigger variables for both the speed and horz pilots, nothing wrong.
I looked at the transfers of both the heading and speed button, nothing wrong. 
I then ran out of things to look at so I started tearing apart the autopilot to find something, I couldn't.

Eventually I did this to rule out the problem being with pilot assistant or RPM itself;

	MODULE
	{
		name = JSIActionGroupSwitch
		animationName = switch_B_ButtonPushAnim
		switchTransform = switch_B_ButtonBody
		actionName = dummy //transfer
		masterVariableName = CUSTOM_AUTOT_ON
		masterVariableRange = 0.5, 1.5
		perPodPersistenceName = AUTOT_SPEED_BUTTON
		switchSound = AdvancedCockpit/Sounds/B_Button01_Click
		//TRANSFERACTION
		//{
		//    name = JSIPilotAssistant
		//    setMethod = SetThrottleMode
		//    perPodPersistenceName = AUTOP_SPEEDMODE_2
		//    stateVariable = CUSTOM_AUTOT_ON
		//}
	}

I pressed the button and nothing happened which meant that it couldn't be a hidden or wrong variable somewhere. I kept digging and found that when I press the button, the speed autopilot doesn't change only the horizontal one. BUT WE MUST GO DOOPER!!!!!

I had a look at RPMS code and I think I found the issue.

https://github.com/Mihara/RasterPropMonitor/blob/master/RasterPropMonitor/Handlers/JSIPilotAssistant.cs

       public void SetThrottleMode(double dmode) 
781         { 
782             if (!paFound) 
783             { 
784                 return; 
785             } 
786 
 
787             ThrottleMode throttleMode; 
788             switch ((int)dmode) 
789             { 
790                 case 0: 
791                     throttleMode = ThrottleMode.Direct; 
792                     break; 
793                 case 1: 
794                     throttleMode = ThrottleMode.Acceleration; 
795                     break; 
796                 case 2: 
797                     throttleMode = ThrottleMode.Speed; 
798                     break; 
799                 default: 
800                     return; 
801             } 
802 
 
803             try 
804             { 
805                 object pilotAssistant = GetPilotAssistant(); 
806                 object throttleActive = throttleActive_t.GetValue(pilotAssistant); 
807 
 
808                 **_SetHorz_**(pilotAssistant, new object[] { throttleActive, false, throttleMode, 0.0 }); 
809             } 
810             catch (Exception e) 
811             { 
812                 JUtil.LogMessage(this, "SetThrottleMode: {0}", e); 
813             } 
814         } 

The problem was with RPM. It was just my messy autopilot that made it difficult to find.
:D

**Comment by MOARdV** [comment]
Ah, that's what we call a "copy-pasta" error.  Some spaghetti code that copied from one place and pasted in another, and some subtle detail got overlooked fixing it up for its new location.

Also an easy fix, since you've already done the work. :)

**Comment by DeputyLOL** [comment]
Glad I'm helpful!

**Comment by MOARdV** [comment]
Updated with the fix on [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by DeputyLOL** [comment]
Thank you. Quick question, is the ability to use variables from seperate cockpits of the same ship still there. I recently discovered that my 'fasten seatbelt' sign isn't working. *dramatic pause. 
I know that you have been tweaking the way persistents work trying to fix the undocking bug and i was wondering if this was intentional or not.

Thanks.

**Comment by MOARdV** [comment]
> Thank you. Quick question, is the ability to use variables from seperate cockpits of the same ship still there. I recently discovered that my 'fasten seatbelt' sign isn't working. *dramatic pause. 

Yeah, I broke that with the fixes I had to do for the docking and undocking bugs.  I have thought about creating some "GLOBAL" variables that work like persistents, but are shared by all parts, but I haven't gotten around to implementing them.
