### ISSUE TITLE
Request. Landing gear state

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#562]
> I also added JSIInternalRPMButtons SolarPanelsState. Returns deployable solar panel state:

this is a very cool feature. Can you make the same variable for the landing gear/wheels??

**Comment by DeputyLOL** [comment]
Yes please!!!

**Comment by MOARdV** [comment]
No,

I am joking.  I think the answer is "maybe".  I am studying the modules now, and I will need to do some tests.

**Comment by MOARdV** [comment]
I can provide a variable same as the solar panels (retracting, extending, retracted, extended, broken) *and* I can provide a variable reporting gear position (0 = retracted, 1 = extended, in between is movement).

**Comment by MOARdV** [comment]
JSIInternalRPMButtons `LandingGearState`, same as solar panels state (-1 = none, 0 = retracted, 1 = deployed, 2 = deploying, 3 = retracting, 4 = inoperable / broken). `LandingGearPosition` returns 0 when gear are retracted, 1 when extended, otherwise a number between those indicating gear position.

On [DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0).

**Comment by Alexustas** [comment]
> JSIInternalRPMButtons LandingGearState,

this variable does not track the rover wheels?

**Comment by MOARdV** [comment]
> this variable does not track the rover wheels?

It tracks wheels with ModuleWheelDeployment.

**Comment by Alexustas** [comment]
I was hoping to use this variable also to keep track of damage rovers wheels

**Comment by MOARdV** [comment]
> I was hoping to use this variable also to keep track of damage rovers wheels

Needs to be a different variable.  ModuleWheelDamage tracks damage (and if it is repairable).  I can add variables for it, also.

**Comment by Alexustas** [comment]
>  I can add variables for it, also.

I will be very grateful to you ))

**Comment by MOARdV** [comment]
[Untested DropBox](https://www.dropbox.com/s/qocogwy8qm1qxi2/RasterPropMonitor-dev.0.26.1.zip?dl=0)

JSIInternalRPMButtons `GetWheelsDamaged` - returns true if any wheel is damaged.  `GetWheelsRepairable` - returns true if any wheel is repairable.  `GetWheelStress` - returns largest "stress percent" of the wheels. That is the name of the variable in the ModuleWheelDamage - I do not know if it is 0 - 1, or 0 - 100.

**Comment by Alexustas** [comment]
`PLUGIN_JSIInternalRPMButtons:LandingGearState ` always gives "-1"
`PLUGIN_JSIInternalRPMButtons:GetWheelsRepairable` always show "1" regardless of whether all the wheels intact or all broken 
`PLUGIN_JSIInternalRPMButtons:GetWheelStress` works normal

**Comment by MOARdV** [comment]
What landing gear  / wheels?  I tested with one of the aircraft gear (Aeris 3A stock aircraft) and I got correct numbers for LandingGearState.  If the wheels can not retract, then LandingGearState returns -1 - it only works with landing gear that can be extended / retracted.

GetWheelsRepairable means "can someone fix the wheels?", not "are wheels broken?".  If it returns 1, then a Kerbal is allowed to repair the wheel if the wheel is broken.

What does GetWheelStress return?  is it 0-1 or 0-100?

**Comment by Alexustas** [comment]
> What landing gear / wheels?

this is my test "rover"

![2016-06-16 04-49-47-435](https://cloud.githubusercontent.com/assets/6713671/16100108/e6ad94c0-337d-11e6-8dfe-ab4e4c42e459.jpg)

> If it returns 1, then a Kerbal is allowed to repair...

ok

>What does GetWheelStress return? is it 0-1 or 0-100?

in my case it return about 10...14, so "1-100"

**Comment by MOARdV** [comment]
Okay.  LandingGearState is always -1, because wheels can not retract.  Only GetWheelsDamaged is going to work for rover wheels.

**Comment by Alexustas** [comment]
> PLUGIN_JSIInternalRPMButtons:LandingGearState always gives "-1"

Oh, I made a mistake in that post. I actually used the variable `"PLUGIN_JSIInternalRPMButtons: GetWheelsDamage"` and it always returns "-1"

**Comment by Alexustas** [comment]
that's broken wheel at the rover

![screenshot201](https://cloud.githubusercontent.com/assets/6713671/16100356/a2d47604-337f-11e6-9a70-a4e3da951f94.png)

that's what the display shows (Wheel dam: -1 )

![screenshot199](https://cloud.githubusercontent.com/assets/6713671/16100410/e9472d0c-337f-11e6-8256-05c11fb511fd.png)

Wheel dam:{0} $&$ PLUGIN_JSIInternalRPMButtons:GetWheelsDamage

**Comment by MOARdV** [comment]
I wonder if the wheel damage in that module is inaccurate.  I will have to try some more tests.

**Comment by MOARdV** [comment]
Oh!  try GetWheelsDamage**d**, not GetWheelsDamage?

**Comment by Alexustas** [comment]
Oh! you're right. stupid mistake, I'm sorry. 
everything works fine now

**Comment by DeputyLOL** [comment]
Could we add the ability to set brake force?

**Comment by MOARdV** [comment]
Added JSIInternalRPMButtons `GetWheelBrakes` and `SetWheelBrakes`.  Get method returns a number from 0 - 200 that is the averaged setting of the brake tweakable on enabled wheels.  Set method takes a number from 0 - 200 and applies it to all enabled wheel brakes.

**Comment by DeputyLOL** [comment]
Thank you!
