### ISSUE TITLE
JSIVertical/Horizontal Bars?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#567]
Is it possible to use the vertical and horizontal bars without needing to use JSIHUD?

**Comment by MOARdV** [comment]
No, they're part of the JSIHUD code.  You could set up a HUD that doesn't draw the ladder, I suppose.

**Comment by DeputyLOL** [comment]
Ok thank you

**Comment by DeputyLOL** [comment]
Yeah, works great. I hope that the new KSP update hasn't undone all your work on the undocking bug. :P
