### ISSUE TITLE
MM reload database will ignore changes to texture if the name isn't changed.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#574]
Put simply, a full reload or quick reload wont update any sounds or textures if the name isn't changed.
For example:
I have a texture called MFD.png
There is something wrong with it so I edit the texture and save it as MFD.png
I reload database.
Texture hasn't changed.
I rage.
I have to restart KSP in order for the new texture to be loaded.

Same goes for sound files.

I am posting this here because this hasn't happened before and the only thing I've updated is RPM.

**Comment by MOARdV** [comment]
Not sure how I could have affected that.  Are you at the space center for the reload?  None of the RPM code is active when that happens.

**Comment by DeputyLOL** [comment]
I am at the space centre. The reason I ask is that it hasn't happened before. It can be fixed by changing the name of the texture/sound file.
