### ISSUE TITLE
Smooth changing variable.

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#576]
I don't really know how this would work but it would be very useful to have a 'ratechange' option for variables. Sometimes its better if variables slowly go change from their old variable to their new one. It might have to be its own separate variable type.
As always, I'm better at just presenting what the config could look like.
RPM_RATE_VARIABLE
{
   name = SELECT_BLAH <-- Input to be smoothed
   rate = 0.1 <-- How fast it changes from its old number to a new number
   output = SMOOTHBLAH <-- what the output is called.
}
The output would be RATE_SMOOTHBLAH.

Please let me know what you think.

**Comment by MOARdV** [comment]
JSIVariableAnimator has that capability.  Applying the smoothing to a variable will be a bit trickier.  I'll have to see what I can come up with.

**Comment by DeputyLOL** [comment]
thank you. 
I know about JSIVariableAnimator but having the ability to use it on variables has a number of uses and advantages.
1. It can be used as a short delay/timer.
2. It can smooth out animations that don't use JSIVariableAnimator. Such as vertical + horizontal bars.
3. It can be used to make momentarily active variables.

**Comment by MOARdV** [comment]
Closing this, since the feature will be in MAS once it's implemented.
