### ISSUE TITLE
Math "POWER" don't work?

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#583]
a simple test configuration:

```
RPM_MATH_VARIABLE
{
   name = ASET_ALT_PWR2
   operator = POWER   

   sourceVariable = ALTITUDE
   sourceVariable = 2
}
```

returns  _"{0}MATH_ASET_ALT_PWR2"_

**Comment by MOARdV** [comment]
It works for me:
```
ASET_ALT_PWR2 = {0} $&$ MATH_ASET_ALT_PWR2
```
see 5817.xxxxx while on the launch pad using that math variable..

**Comment by Alexustas** [comment]
Oh! I'm sorry, it was my stupid mistake. everything works perfectly. Thank you!
