### ISSUE TITLE
JSITexture Animator?

### ISSUE THREAD

**Issue by DeputyLOL** [Mihara/RasterPropMonitor#584]
Taken from #418 

> quick question. I recall you saying that the round monitor gauges would be very hard to implement. So instead of making something that functions like a round version of the vertical and horizontal bars, do you think it would be possible to control a texture using the same kind of methods that we can use for props with JSIVariableAnimator? E.g. transform, rotate, scale, maybe even colour?. The only real difference would be that it is 2D and it uses a texture rather than a prop. It would give a lot more flexibility. I don't know how hard that would be to implement.

 If your not busy, this would be a VERY useful and helpful feature to have in RPM. Let me know what you think.

> A texture on the screen? That'd be new functionality (that is, we don't currently), although I am pretty sure alexustas has expressed interest in something similar as well. I suspect it wouldn't be hard to do, really..

**Comment by MOARdV** [comment]
I can't commit to it just yet - work is promising to become very busy for the next month or so.

**Comment by MOARdV** [comment]
Not implementing in RPM - MAS is a better candidate for the feature.
