### ISSUE TITLE
Issues Installing mod!

### ISSUE THREAD

**Issue by MrMaplePie** [Mihara/RasterPropMonitor#585]
Hello, 

     

 I am have a problem install the mod for 1.1.3. I have look at countless guilds on Youtube, Web, and 
on forums without any luck. I place both files into Kerbal Space Program/Gamedata. Started the game 
up with no errors until I went to the launchpad and can't access IVA and also can't see the Kerbal's in 
the bottom right corner of the screen. Also if I try to launch any ships in sandbox mode say's locked or Invalid Parts! When I first install the mod, I did have a problem with the mod place into the Kerbal 
Space Program/Squad/Gamedata. So I correct it by removing the folder Squad but make note that 
the files for Gamedata is still the same. So it's place Kerbal Space Program/Gamedata. I have the 
game from KSP and not steam not sure if thats the problem or not I doubt it. Thanks for you hard 
work hope to enjoy the mod soon.

Thanks, 
MrMaplePie

**Comment by Bear67** [comment]
**both files?** the Archive contains 109 files. Do you have more than one version of ModuleManager in your GameData directory?

**Comment by MrMaplePie** [comment]
As for the ModuleManager I have 2.6.25, ConfigCache, ConfigSHA, Physics, and TechTree Located in the GameData and also JSI

**Comment by MOARdV** [comment]
> So I correct it by removing the folder Squad but make note that the files for Gamedata is still the same

The Gamedata/Squad folder contains all of the KSP assets.  If you removed that folder, you removed most of the game.  Please reinstall KSP, and then unzip the RasterPropMonitor files into the Gamedata folder, so both it and the Squad folder are present.

**Comment by MrMaplePie** [comment]
Thanks MOARdV! :]
