### ISSUE TITLE
New color tags question

### ISSUE THREAD

**Issue by Alexustas** [Mihara/RasterPropMonitor#598]
in some of my props I used this setting.
`labelText = [#<=1:"FF0000";"FFFF00";"0055FF"=>] ...`

 And how I can do the same thing now ?

**Comment by MOARdV** [comment]
> And how I can do the same thing now ?

I think

`labelText = <color=# <=1:"ff0000"; "ffff00";"0055ff"=> >`

(have not tested it).

Sorry to have to change it - the old way does not work, and it would be tricky to replace strings automatically (and make it slower, too).

**Comment by DeputyLOL** [comment]
where do you put the thing you want to write?
<color=# <=1:"333333"; "FF0000";"FFFFFF"=> >       START $&$ CUSTOM_BACKLIGHTLABEL
<color=# <=1:"333333"; "FF0000";"FFFFFF"=>          START >$&$ CUSTOM_BACKLIGHTLABEL

**Comment by MOARdV** [comment]
> where do you put the thing you want to write?

<color= <=1:"333333";"ff0000";"ffffff"=> > START

Outside the color tag.
