### ISSUE TITLE
Screen artifacts in camera view.

### ISSUE THREAD

**Issue by Nukeboyt** [Mihara/RasterPropMonitor#604]
RPM 0.28.0.13911
Between these two screen captures, the only change was mouse-wheel zoom in.
![screenshot44](https://cloud.githubusercontent.com/assets/20101603/20042856/19beb616-a447-11e6-9ae7-ba97092136a2.png)
![screenshot45](https://cloud.githubusercontent.com/assets/20101603/20042857/19bee03c-a447-11e6-8d91-8de0549adc5d.png)

Theses are from ASET screens

![screenshot41](https://cloud.githubusercontent.com/assets/20101603/20042866/40d1c720-a447-11e6-9a79-d8f10f630440.png)

![screenshot34](https://cloud.githubusercontent.com/assets/20101603/20042879/76856ba6-a447-11e6-9f24-70cad41191a8.png)

Note:
Upon removing mods (Scatterer, SVE, EVE) I was unable to reproduce the above effects.

**Comment by MOARdV** [comment]
> Upon removing mods (Scatterer, SVE, EVE) I was unable to reproduce the above effects.

I suspect it's an artifact of the way those mods work.  They don't know anything about the RPM cameras, so they don't know to undo whatever they were doing for the out-the-window view.  I don't know if there is something RPM can do to say "reset the camera" before it renders.
