### ISSUE TITLE
Mod not showing new IVA's in fresh install of KSP 1.2; log file provided

### ISSUE THREAD

**Issue by odd135** [Mihara/RasterPropMonitor#607]
The game appears to start up fine, but the interior view only shows the stock IVA's (I've checked every interior view; I can't find a single one that appears to have changed). I've tried reinstalling the mod multiple times manually (just the JSI folder and its contents, right in the GameData folder alongside the Squad folder, as per instructions), and most recently I tried reinstalling KSP 1.2 entirely, all to no avail. I'm attaching a log file in a compressed folder; I hope that this helps.
[KSP.zip](https://github.com/Mihara/RasterPropMonitor/files/593535/KSP.zip)

**Comment by MOARdV** [comment]
You do not have any mod DLLs.  There should be a DLL for RasterPropMonitor, and a DLL for ModuleManager, but they're not showing up.  It looks like you have the game installed to the default Steam install location (Program Files (x86)/Steam/steamapps), which may be the problem.  Installing mods to Program Files tends to cause problems with virus scanners.  If you can copy the entire Kerbal Space Program to another directory, and run it from there, you may have better success (after re-installing the mods).  Squad was kind enough to leave DRM out of KSP, so you can run the game from another directory without running Steam.

**Comment by odd135** [comment]
I'll go ahead and try that. I don't have any virus software, though, and both kerbal engineer and the alarm clock mod were working fine. I'll post the log file for this attempt as well, once I've done it.

**Comment by odd135** [comment]
Okay, I've moved it to the desktop and stopped the steam bootstrapper manually from task manager, and I'm still having the same problem. Log file:
[KSP (2).zip](https://github.com/Mihara/RasterPropMonitor/files/593593/KSP.2.zip)

**Comment by MOARdV** [comment]
The mod is not installed correctly.  According to that log, you have no mod DLLs installed.  RPM requires Module Manager to be installed in the GameData directory, and it requires the RasterPropMonitor DLL installed in GameData/JSI/RasterPropMonitor/Plugins directory.  How are you installing this mod?

**Comment by odd135** [comment]
I found that the file that you mentioned wasn't there in my most recent download for some reason, so I went and downloaded it again from the releases page, and it was there in that download. It still didn't work with the download that had the file, so here's a screenshot showing where it is:
![screenshot1](https://cloud.githubusercontent.com/assets/23489646/20353383/a8c569ba-abe8-11e6-8576-c2f4a30f11fb.png)
And here's the most recent log file:
[KSP (3).zip](https://github.com/Mihara/RasterPropMonitor/files/595050/KSP.3.zip)
Thanks for sticking with me so far, though.

**Comment by MOARdV** [comment]
You still need to install [Module Manager](http://forum.kerbalspaceprogram.com/index.php?/topic/50533-121-module-manager-274-november-14th-better-late-than-never/).  RPM (and many other mods) will not work without it.

**Comment by odd135** [comment]
I'm sorry it's taken so long to respond, but it worked after installing module manager! Why isn't module manager mentioned in the installation instructions or FAQ, though?

**Comment by MOARdV** [comment]
> I'm sorry it's taken so long to respond, but it worked after installing module manager! Why isn't module manager mentioned in the installation instructions or FAQ, though? Either way, thanks for the help.

I changed the installation process, but I didn't update the FAQ.  Glad it's working.
