### ISSUE TITLE
Mouse events to Background Handlers?

### ISSUE THREAD

**Issue by WazWaz** [Mihara/RasterPropMonitor#608]
I'm working on the GUI for kOS and it could be eventually possible to support displaying the GUI on RPM screens, but that's only really useful if the user can click on buttons in that GUI and have that event passed to the handler, which currently appears to not be possible.

**Comment by MOARdV** [comment]
RPM only knows that a collider on a prop has been hit.  There is no hit location information, so the only way to emulate a touchscreen-style interface would be to create a prop that has multiple colliders (one for each potential "button" position) and a convoluted page definition to control the behavior.
