### ISSUE TITLE
PLUGIN_JSIMechJeb:GetLandingLongitude in JSIVariableAnimator is broken

### ISSUE THREAD

**Issue by InsaneDruid** [Mihara/RasterPropMonitor#616]
When you use a variable like PLUGIN_JSIMechJeb:GetLandingLongitude (or -Latitude etc.) to drive a JSIVariableAnimator, the Variable pulled from MechJeb will be -1/not working.

I set up a RPM Monitor page outputting these variables pulled from Mechjeb and they are working as intended displaying the same content as the MechJeb windows as long as they are not also used inside a JSIVariableAnimator module. Even if used "indirectly" via a mapped variable that then is put inside the JSIVariableAnimator they will output -1. The JSIVariableAnimator is working fine using RPMs own variables (like LATITUDE and LONGITUDE) so it is set up correctly.

You can see this effect in other props, too, like the ASET_IMP. This is working in all modes but those using the variables pulled from MechJeb. (Landing prediction). Even with MechJeb working and the Landing prediction turned on and the craft on a sub-orbital trajectory (i.e. the landing predictor working and outputting a correct landing spot)

**Comment by InsaneDruid** [comment]
As a side note, when  ButtonEnableLandingPredictionState is used in a RPM_CUSTOM_VARIABLE it will read -1 constantly, whether the prediction is actually on or off in MechJeb. Just using it in a RPM Page (via a page definition file) works fine and corresponds with the state of MechJeb by outputting 0 or 1. But when it is used in a (otherwise perfectly working variable like 	
 SOURCE_VARIABLE
 {
 	name = PLUGIN_MechJebRPMButtons:ButtonEnableLandingPredictionState
 	range = 0.1, 1.1
 }
it will just show -1.

**Comment by MOARdV** [comment]
I checked into this one while I was looking at the SELECT variable you reported, and it is working for me here.  I suspect both of these problems have the same root cause.

**Comment by InsaneDruid** [comment]
As said in #618 it is working now with the 0.28.1 dev build.
