### ISSUE TITLE
Feature Request:Ability to have a prop in a webpage

### ISSUE THREAD

**Issue by RacerXx** [Mihara/RasterPropMonitor#617]
having the ability to have for example a MultiFunctionDisplay (or other props) in a webpage using websocket or something like that to send recieve updates to the MFD. This would in turn allow for running a prop or MFD in this case on external cell phones or tablets which also have native touchscreen displays.

**Comment by MOARdV** [comment]
Sorry, but that is completely outside the scope of RPM.  It would entail a completely new plugin, possibly with supporting apps.  RPM is all about enhancing the IVA experience in-game, not extracting that data or generating web pages.
