### ISSUE TITLE
TIMETOIMPACTSECS used in RPM_SELECT_VARIABLE throws RPM initialization error

### ISSUE THREAD

**Issue by InsaneDruid** [Mihara/RasterPropMonitor#618]
When trying to to things like this:
`RPM_SELECT_VARIABLE
{
	name = HGA_SNI_ETA_SECONDS
	defaultValue = 3600
        VARIABLE_DEFINITION // -- IMPACT PREDICTION --
	{
		name = CUSTOM_HGA_SNI_MODE_LNDG_IMPACT
		range = 0.1, 1.1
		value = TIMETOIMPACTSECS
	}
}`
which works using other time variables (like TIMETOATMOSPHERESECS) throws an RPM initialization error when entering the craft, breaking the prop

**Comment by MOARdV** [comment]
Can you put the log with that failure somewhere?  There are several conditions involved in determining time to impact, and it would be helpful having the full log so I can determine the environment where it's failing.

**Comment by InsaneDruid** [comment]
https://www.dropbox.com/s/glagn7cg3bwbfiu/KSP.log?dl=0

Here you go.

**Comment by MOARdV** [comment]
I think I found the problem.  Terminal Velocity had the same issue.  Dev build on [Dropbox](https://www.dropbox.com/s/7bsgaob2diwoylk/RasterPropMonitor-dev.0.28.1.zip?dl=0).

**Comment by InsaneDruid** [comment]
Unfortunately, still brakes for me.
https://www.dropbox.com/s/df145sf1uej9wx9/KSP_V2.log?dl=0

**Comment by MOARdV** [comment]
I checked TIMETOIMPACTSECS locally on an MFD using a select variable:

(MFD display:)
```
Test: {0} $&$ SELECT_TEST
```

(SELECT config:)
```
RPM_SELECT_VARIABLE
{
	name = TEST
	defaultValue = 1
	
	VARIABLE_DEFINITION
	{
		name = GEAR
		range = 0.1,1.1
		value = TIMETOIMPACTSECS
	}
}
```

TIMETOIMPACTSECS does not throw an exception for me.  So, to check a couple of other things:

Does the part config that uses this IVA include
```
MODULE
{
	name = RasterPropMonitorComputer
}
```
If not, add that in and check again.

The other possibility is that one of the other props is failing to initialize, and it's having a knock-on effect that's causing this particular prop to behave very badly.  I see some other RPM errors right above the exception in your log.  You might edit GameData/JSI/RasterPropMonitor/Plugins/PluginData/rpm-config/cfg so it has `DebugLogging = True` so we can figure out what the other RPM errors are about.

**Comment by InsaneDruid** [comment]
It was missing RasterPropMonitorComputer (doh!) and my font texture had the same name as one of the default JSI fonts. With these issues sorted out and using the dev build everything works as expected. Thanks!
