### ISSUE TITLE
cameraTransform - camera alpha & content problems

### ISSUE THREAD

**Issue by InsaneDruid** [Mihara/RasterPropMonitor#621]
Adding a camera directly to a page (without background handler), ie something like:
PAGE
{
	name = tks_va_vzor_zoom_page
	cameraTransform = va_capsule_nodeVzor
	cameraAspect = 1.0
	zoomFov = 25,65,3
	zoomButtons = 0,1
}
does sometimes produce images that contain several errors:

- the planets are rendered (semi)transparent against the background skybox
- atmosphere layers are rendered incorrectly or are missing completely
- "ghost" planets (that are at least not transparent) appear near the actual planets

This error can most likely be  reproduced (if not present since launch) by switching from a vessel to the tracking station and back to the vessel.

Included are some screenshots from a LKO that show the issues and compare them to a camera set up via a background handler. The content of the images are as follows:

- camera_transparency_error.png -  shows the transparency error against the background of the skybox. This error is most visible during night at the oceans, but is also present during daylight on every surface.
- camera_transparency_error_monitor.png is the same as above, but the direct output of the camera-generated texture.  The ring like structure is the boundary of the inner and outer camera used in my test craft - I have two pages defined with  2 different screenTransforms and a camera on each of these pages using the same cameraTransform) as this is used to simulate the vzor of a va (or sojuz, or saljut etc).
- ghost_kerbin.png shows a raw capture of a "ghost" kerbin appearing in the camera image that does not have the transparency issue but has distorted atmosphere layers.
- out_bckgrnd_ hdlr_inr_cam.png shows the difference in a camera used as described above and - in the outer ring - a camera set up as a background handler. The Background handler cam shows correct atmospheric haze, no transparency issue and no ghost kerbin, while the (inner) cam set up directly in the page shows all of the problems.
- camera_transparency_error.png -  shows the transparency error against the background of the skybox. This error is most visible during night at the oceans, but is also present during daylight on every surface.
- camera_transparency_error_monitor.png is the same as above, but the direct output of the camera-generated texture.  The ring like structure is the boundary of the inner and outer camera used in my test craft - I have two pages defined with  2 different screenTransforms and a camera on each of these pages using the same cameraTransform) as this is used to simulate the vzor of a va (or sojuz, or saljut etc).
- ghost_kerbin.png shows a raw capture of a "ghost" kerbin appearing in the camera image that does not have the transparency issue but has distorted atmosphere layers.
- out_background_ handler_inner_direct_cam.png shows the difference in a camera used as described above and - in the outer ring - a camera set up as a background handler. The Background handler cam shows correct atmospheric haze, no transparency issue and no ghost kerbin, while the (inner) cam set up directly in the page shows all of the problems.

camera_transparency_error.png
![camera_transparency_error](https://cloud.githubusercontent.com/assets/11518812/22064969/3ed6657a-dd86-11e6-8e41-456a4cc00890.png)
camera_transparency_error_monitor.png
![camera_transparency_error_monitor](https://cloud.githubusercontent.com/assets/11518812/22064967/3ecdf87c-dd86-11e6-85be-25fca18b58a2.png)
ghost_kerbin.png
![ghost_kerbin](https://cloud.githubusercontent.com/assets/11518812/22064970/3eda8dc6-dd86-11e6-8152-87582a981769.png)
out_background_ handler_inner_direct_cam.png
![out_background_ handler_inner_direct_cam](https://cloud.githubusercontent.com/assets/11518812/22064968/3ed259bc-dd86-11e6-8239-7ba9cba6bb6a.png)

**Comment by MOARdV** [comment]
I'm not entirely surprised.  That's an older implementation of the camera, and it hasn't been maintained, nor does it have the same features as the steerable camera background handler.  I suspect the issue is that the camera in that mode renders directly to the same screen texture, and both pages are drawing to the same location with different parameters.  I really need to deprecate that mode.
