### ISSUE TITLE
My IVA screens are black. HELP!!!

### ISSUE THREAD

**Issue by DarkAbomination** [Mihara/RasterPropMonitor#622]
My IVA screens are black. I use 1.2.2 (I have tried clicking the buttons on the display and install latest version of the mod)

Please help, my email address is: arhab_n@hotmail.com

**Comment by MOARdV** [comment]
I need to see the KSP.log before I can provide any help.  Please refer to [this KSP forum post](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/) for instructions.

**Comment by DarkAbomination** [comment]
output_log.txt:
[output_log.txt](https://github.com/Mihara/RasterPropMonitor/files/785155/output_log.txt)

**Comment by MOARdV** [comment]
You did not completely install RasterPropMonitor.  There is no JSI/RasterPropMonitor/Plugins/RasterPropMonitor.dll, so the mod doesn't work.  Please fully install RPM, not just the props.
