### ISSUE TITLE
Shaders don't work in Linux

### ISSUE THREAD

**Issue by MOARdV** [Mihara/RasterPropMonitor#634]
Forum user martinmike2 reports shaders failing to load on Linux.  I can use -force-glcore and view everything just fine locally, and I have no other Linux users reporting anything either way (seeing the problem, or seeing it work).  I've tweaked the bundle export code in Unity as far as I can, and nothing has changed.

At this point, I do not have a path forward to resolve the issue, and I can't even determine if it's isolated to one user.

**Comment by Technologicat** [comment]
Just documenting here that, as already posted on the forum, I'm also seeing this issue on Linux.

Linux Mint 17.2, KSP 1.3.0 (64-bit), NVIDIA GTX 960m, driver version 352.79 running OpenGL 4.5.
