### ISSUE TITLE
JSIVariableAnimator prop module: after switching between vessels, props play active state animation even if out of ElectricCharge

### ISSUE THREAD

**Issue by sumghai** [Mihara/RasterPropMonitor#635]
**KSP Version:** 1.3.0
**Mods installed:**
- RasterPropMonitor v0.29.0 beta 2
- ModuleManager 2.8.0
- FusTek Station Parts dev build (sumghai/FusTek_StationParts@29ba4fddbe759dcdf5ab7bb6a0ecc0164209a531)

**Description**

A vessel IVA with props powered by JSIVariableAnimator plays the active state animations when sufficient ElectricCharge is present, and then plays the off state animations once ElectricCharge runs out. However, after switching to another vessel and back, the IVA props resume playing the active state animations even with no ElectricCharge present.

**Reproduction Steps**
 - Setup a KSP game installation with the aforementioned mods
 - Create a test vessel consisting of a Kuest Airlock and a Large Probe Core
 - Crew the vessel with one Kerbal
 - Launch the vessel to the Flight Scene
 - Enter IVA
 - Observe that the props currently play the active state animation as there is sufficient ElectricCharge **(normal behaviour)**
 - Time warp until ElectricCharge runs out
 - Observe that the props now play the off state animation as there is no ElectricCharge **(normal behaviour)**
 - Switch to another vessel and back -OR- switch to the Space Center Scene and back
 - Enter IVA
 - Observe that the props return to playing the active state animation, even when there is no ElectricCharge **(unexpected behaviour)**

**Notes**

I've only just recently returned to KSP modding, so I suspect I may be using outdated syntax for JSIVariableAnimator; however, there is also the possibility that KSP 1.3.0 changed the way the state of a vessel with no ElectricCharge is flagged internally.

**Comment by MOARdV** [comment]
It is also likely that I didn't account for checking the state of electric charge at prop initialization.  I will take a look at it, hopefully this weekend.

**Comment by MOARdV** [comment]
Fixed in beta 3 - the initialization code didn't account for starting in the "off" state.
