### ISSUE TITLE
[Linux] [1.3.x] Purple bars where characters should be 

### ISSUE THREAD

**Issue by SirRolls** [Mihara/RasterPropMonitor#637]
Might be related to the shaders not working, but where ever a character should be, or even graphs, there is just a purple bar. Running linux mint, cinnamon

**Comment by MOARdV** [comment]
This is a duplicate of Issue #634 .  Note that I posted a test build today in the RPM thread that may have fixed this issue.  You do not indicate which version of RPM you were using.

**Comment by SirRolls** [comment]
Running RPM Build #11864 beta 3. I'll try the test build ITT now

**Comment by SirRolls** [comment]
Test build works for me!

**Comment by MOARdV** [comment]
Closing as a duplicate.  Thank you for the feedback.
