### ISSUE TITLE
IVA doesn't display the plugin

### ISSUE THREAD

**Issue by weird6969** [Mihara/RasterPropMonitor#640]
Hello! I have installed the mod according to the instructions (i.e Placing JSI folder inside GameData folder). I can see the JSI radial mounted camera in the tools menu of the vehicle assembly building, which for me means that the plugin is installed, but whenever I launch a vessel with crew and I go IVA (on the ground), I still see the KSP default displays and not the rasterpropmod screens. Im running the latest original version of KSP x64 (1.30.1804) and the latest version of RPM (0.29.0). Any help will be appreciated.
Thank you

**Comment by weird6969** [comment]
Just uninstalled the mod manually, downloaded CKAN, fresh install of RPM and now it works. I've realized that together with RPM it has installed required? mods, like ModuleManager. RPM now fully functional.

**Comment by MOARdV** [comment]
Yes, as mentioned in the readme, ModuleManager is a required mod, and it is not included in the RPM distribution.
