### ISSUE TITLE
Monitors showing in some IVAs, but are not functional.

### ISSUE THREAD

**Issue by bubbadoobop** [Mihara/RasterPropMonitor#641]
I'm running [Manjaro](https://manjaro.org/) 17.0.2. I could install the mod fine, but the monitors would not show up in some cockpits (like the Mk.1 inline cockpit), and would not function at all. I installed the latest version of Module Manager, so I'm not totally sure what went wrong.

**Comment by MOARdV** [comment]
I need more information,  At the very least, please follow the recommendations from [this thread](https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/) on the KSP forum, and provide logs.

**Comment by bubbadoobop** [comment]
I got the logs after a bit of debugging;

```
[LOG 14:56:51.024] LoadInternalPart 'JSI/RPMPodPatches/PatchesStock/mk2-sh-cockpit-remade-internal/SH_mk2CockpitInternalRPM' FAILED: Cannot find model
[LOG 14:56:51.024] PartLoader: Compiling Internal Space 'JSI/RPMPodPatches/PatchesStock/mk2-sh-cockpit-remade-internal/mk2CockpitInternal'
[ERR 14:56:51.025] PartCompiler: Cannot clone model from 'JSI/RPMPodPatches/PatchesStock' directory as model does not exist

[LOG 14:56:51.025] LoadInternalPart 'JSI/RPMPodPatches/PatchesStock/mk2-sh-cockpit-remade-internal/mk2CockpitInternal' FAILED: Cannot find model
[LOG 14:56:51.025] PartLoader: Compiling Internal Space 'JSI/RPMPodPatches/PatchesStock/mk2-spp-cockpits/mk2CockpitStandardInternalsRPM'
[LOG 14:56:51.038] PartLoader: Compiling Internal Space 'JSI/RPMPodPatches/PatchesStock/mk2landercan-remade-internal/landerCabinInternalsRPM'
[ERR 14:56:51.039] Cannot find an InternalModule of typename 'InternalCameraTargetHelper'

[ERR 14:56:51.039] Cannot find an InternalModule of typename 'JSISetInternalCameraFOV'
```

It looks like there's a/some missing model(s) somewhere in the gamedata directory. I think it may effect the interactivity in the IVA somehow.

**Comment by MOARdV** [comment]
WIthout the full log described in the thread I referenced earlier, I have inadequate data to diagnose the problem.  The last two lines of that excerpt ('Cannot find an InternalModule...') suggest RPM was not installed correctly, since those internal modules are both part of RasterPropMonitor.

**Comment by Ruedii** [comment]
Airplane Plus has this issue, as do a few others.  

I'm not sure if they are all the same issue, though.
