### ISSUE TITLE
Can't interact with any of the monitors/buttons from RPM for 1.1.3

### ISSUE THREAD

**Issue by ben04peters** [Mihara/RasterPropMonitor#652]
Using RPM for 1.1.3 - have ASET Props, BDArmoryMK22 (for 1.1), and ModuleManager v2.6.25

Can't interact with the monitors, buttons, or switches in the IVA of the MK22 parts or the Mk1-2 Command Pod.

**Comment by MOARdV** [comment]
Assuming the 1.1.3 is not a typo, you are using a very old version of KSP - the last version of RPM that worked with it came out over two years ago.  If you provide the logs as [described in this forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/), I can at least determine if you have the right RPM version and it is correctly installed.  Beyond that, there's not much support I can provide on such an old version of the game and mod.
