### ISSUE TITLE
Engine Ignitor Integration Not Functioning

### ISSUE THREAD

**Issue by MeadeRobert** [Mihara/RasterPropMonitor#655]

**Comment by MOARdV** [comment]
Engine Ignitor has its own DLL that RPM uses.  If that DLL is not current, the integration will not work.  This is an issue that the Engine Ignitor mod maker needs to look into.

**Comment by MeadeRobert** [comment]
The maker of Engine Ignitor linuxgurugamer claims that EngineIgnitor has nothing to do with RPM and closed my issue. What do I do? Forget about it?

**Comment by MOARdV** [comment]
The code that enables EngineIgnitor functionality in RasterPropMonitor is a module called EngineIgnitorRPM.  Since it is not a part of RPM, it's outside the scope of this mod for me to fix it.  I can talk to LGG about it, but it's not an RPM bug.
