### ISSUE TITLE
Inverted MFD textures with -force-d3d11

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [Mihara/RasterPropMonitor#668]
You mentioned the inversion affected both DX9 and DX11 in #659 (and DX12 in #665), but only fixed it for DX9 and DX12: https://github.com/Mihara/RasterPropMonitor/blob/fadbce1b41d4c0593cca375d312e3c654aa078d0/RasterPropMonitor/Core/RasterPropMonitor.cs#L181

**Comment by MOARdV** [comment]
The last time I checked, it didn't reproduce.  I'll check it again (been busy on other things) and push an update if needed.

**Comment by MOARdV** [comment]
Okay, just checked again.  I must have messed up in my previous test, because it definitely isn't working right.  Fix will be out "soon".
